import { assert, cliPath, resolve, runGeneratedProject, runNode, tempRoot, test, writeProject } from "./harness.mjs";

test("CLI runs generated C# executable for module constants and variable declarations", async () => {
  const assemblyName = "SmokeGeneratedE2EVariables";
  const projectDirectory = resolve(tempRoot, "e2e-variables");
  await writeProject(projectDirectory, {
    "tsonic.json": JSON.stringify({
      entryPoint: "index.ts",
      rootDir: "src",
      outDir: "out",
      targets: [{ id: "csharp", options: { namespace: "Smoke.Generated", assemblyName, outputType: "Exe" } }],
    }, null, 2),
    "src/index.ts": [
      "import type { byte, float, int, long, short } from \"@tsonic/csharp/types.js\";",
      "import { Console } from \"@tsonic/dotnet/System.js\";",
      "",
      "const PI = 3.14159;",
      "const MESSAGE = \"Hello, World!\";",
      "const COUNT = 42;",
      "const IS_ENABLED = true;",
      "const explicitInt: int = 42;",
      "const explicitByte: byte = 255;",
      "const explicitShort: short = 1000;",
      "const explicitLong: long = 1000000;",
      "const explicitFloat: float = 1.5;",
      "const explicitDouble: number = 1.5;",
      "let mutableInt: int = 0;",
      "let mutableString: string = \"\";",
      "mutableInt = 100;",
      "mutableString = \"updated\";",
      "",
      "Console.WriteLine(`PI: ${PI}`);",
      "Console.WriteLine(`MESSAGE: ${MESSAGE}`);",
      "Console.WriteLine(`COUNT: ${COUNT}`);",
      "Console.WriteLine(`IS_ENABLED: ${IS_ENABLED}`);",
      "Console.WriteLine(`Explicit int: ${explicitInt}`);",
      "Console.WriteLine(`Explicit byte: ${explicitByte}`);",
      "Console.WriteLine(`Explicit short: ${explicitShort}`);",
      "Console.WriteLine(`Explicit long: ${explicitLong}`);",
      "Console.WriteLine(`Explicit float: ${explicitFloat}`);",
      "Console.WriteLine(`Explicit double: ${explicitDouble}`);",
      "Console.WriteLine(`Mutable int: ${mutableInt}`);",
      "Console.WriteLine(`Mutable string: ${mutableString}`);",
      "",
    ].join("\n"),
  });

  const build = runNode([cliPath, "build", "--project", resolve(projectDirectory, "tsonic.json")]);
  assert.equal(build.status, 0, build.stdout + build.stderr);
  assert.equal(runGeneratedProject(projectDirectory, assemblyName), [
    "PI: 3.14159",
    "MESSAGE: Hello, World!",
    "COUNT: 42",
    "IS_ENABLED: True",
    "Explicit int: 42",
    "Explicit byte: 255",
    "Explicit short: 1000",
    "Explicit long: 1000000",
    "Explicit float: 1.5",
    "Explicit double: 1.5",
    "Mutable int: 100",
    "Mutable string: updated",
    "",
  ].join("\n"));
});

test("CLI runs generated C# executable for functions, switches, and nested scopes", async () => {
  const assemblyName = "SmokeGeneratedE2EControlFlow";
  const projectDirectory = resolve(tempRoot, "e2e-control-flow");
  await writeProject(projectDirectory, {
    "tsonic.json": JSON.stringify({
      entryPoint: "index.ts",
      rootDir: "src",
      outDir: "out",
      targets: [{ id: "csharp", options: { namespace: "Smoke.Generated", assemblyName, outputType: "Exe" } }],
    }, null, 2),
    "src/index.ts": [
      "import type { int } from \"@tsonic/csharp/types.js\";",
      "import { Console } from \"@tsonic/dotnet/System.js\";",
      "",
      "function greet(name: string): string {",
      "  return `Hello ${name}`;",
      "}",
      "",
      "function add(a: number, b: number): number {",
      "  return a + b;",
      "}",
      "",
      "function isEven(n: number): boolean {",
      "  return n % 2 === 0;",
      "}",
      "",
      "function getDayType(day: number): string {",
      "  switch (day) {",
      "    case 0:",
      "    case 6:",
      "      return \"weekend\";",
      "    case 1:",
      "    case 2:",
      "    case 3:",
      "    case 4:",
      "    case 5:",
      "      return \"weekday\";",
      "    default:",
      "      return \"invalid\";",
      "  }",
      "}",
      "",
      "function nestedScopes(x: number): number {",
      "  const a = 10;",
      "  {",
      "    const b = 20;",
      "    {",
      "      const c = 30;",
      "      return a + b + c + x;",
      "    }",
      "  }",
      "}",
      "",
      "const arrowAdd = (left: number, right: number): number => left + right;",
      "",
      "function applyOperation(x: number, y: number, op: (left: number, right: number) => number): number {",
      "  return op(x, y);",
      "}",
      "",
      "function makeCounter(): () => number {",
      "  let count = 0;",
      "  return (): number => {",
      "    count++;",
      "    return count;",
      "  };",
      "}",
      "",
      "function makeAdder(value: number): (other: number) => number {",
      "  return (other: number): number => value + other;",
      "}",
      "",
      "type Callback = (result: int) => void;",
      "",
      "function compute(value: int, callback?: Callback): int {",
      "  const result = value * 2;",
      "  if (callback !== undefined) {",
      "    callback(result);",
      "  }",
      "  return result;",
      "}",
      "",
      "function maybeTransform(value: int, transform: ((input: int) => int) | null): int {",
      "  if (transform !== null) {",
      "    return transform(value);",
      "  }",
      "  return value;",
      "}",
      "",
      "type BinaryOperation = (left: number, right: number) => number;",
      "",
      "const operations: BinaryOperation[] = [",
      "  arrowAdd,",
      "  (left: number, right: number): number => left * right,",
      "];",
      "",
      "function runOperation(index: int, left: number, right: number): number {",
      "  return operations[index](left, right);",
      "}",
      "",
      "function chooseOperation(useAdd: boolean): BinaryOperation {",
      "  return useAdd ? arrowAdd : (left: number, right: number): number => left / right;",
      "}",
      "",
      "function makePipeline(offset: number): (input: number) => (scale: number) => number {",
      "  return (input: number): (scale: number) => number => {",
      "    return (scale: number): number => (input + offset) * scale;",
      "  };",
      "}",
      "",
      "interface Formatter {",
      "  format: (value: string) => string;",
      "}",
      "",
      "const formatter: Formatter = {",
      "  format: (value: string): string => `**${value}**`,",
      "};",
      "",
      "function useFormatter(value: string, formatter: Formatter): string {",
      "  return formatter.format(value);",
      "}",
      "",
      "interface Calculator {",
      "  add(left: number, right: number): number;",
      "  scale(value: number): number;",
      "}",
      "",
      "const calculator: Calculator = {",
      "  add(left, right) {",
      "    return left + right;",
      "  },",
      "  scale(value) {",
      "    return value * 2;",
      "  },",
      "};",
      "",
      "function useCalculator(calculator: Calculator): number {",
      "  return calculator.add(4, 5) + calculator.scale(3);",
      "}",
      "",
      "type Point = { x: int; y: int; label: string };",
      "const point: Point = { x: 3, y: 4, label: \"p\" };",
      "",
      "function describePoint(point: Point): string {",
      "  return `${point.label}:${point.x + point.y}`;",
      "}",
      "",
      "function describeInline(value: { name: string; count: int }): string {",
      "  return `${value.name}:${value.count}`;",
      "}",
      "",
      "type IntBox = { value: int };",
      "const intBox: IntBox = { value: 41 };",
      "",
      "function readIntBox(box: IntBox): int {",
      "  return box.value + 1;",
      "}",
      "",
      "Console.WriteLine(greet(\"World\"));",
      "Console.WriteLine(`Add: ${add(3, 7)}`);",
      "Console.WriteLine(`Is 4 even: ${isEven(4)}`);",
      "Console.WriteLine(`Is 5 even: ${isEven(5)}`);",
      "Console.WriteLine(`Day 0: ${getDayType(0)}`);",
      "Console.WriteLine(`Day 3: ${getDayType(3)}`);",
      "Console.WriteLine(`Day 6: ${getDayType(6)}`);",
      "Console.WriteLine(`Day 7: ${getDayType(7)}`);",
      "Console.WriteLine(`Nested scopes result: ${nestedScopes(5)}`);",
      "Console.WriteLine(`Nested scopes result: ${nestedScopes(0)}`);",
      "Console.WriteLine(`Arrow add: ${arrowAdd(3, 5)}`);",
      "Console.WriteLine(`Arrow contextual sum: ${applyOperation(10, 5, (left, right) => left + right)}`);",
      "Console.WriteLine(`Arrow contextual diff: ${applyOperation(10, 5, (left, right) => left - right)}`);",
      "const counterFn = makeCounter();",
      "Console.WriteLine(`Closure count 1: ${counterFn()}`);",
      "Console.WriteLine(`Closure count 2: ${counterFn()}`);",
      "const add5 = makeAdder(5);",
      "Console.WriteLine(`Closure add5: ${add5(3)}`);",
      "Console.WriteLine(`Optional without callback: ${compute(5)}`);",
      "compute(10, (result) => {",
      "  Console.WriteLine(`Optional callback received: ${result}`);",
      "});",
      "Console.WriteLine(`Optional transformed: ${maybeTransform(7, (input) => input + 3)}`);",
      "Console.WriteLine(`Optional not transformed: ${maybeTransform(7, null)}`);",
      "Console.WriteLine(`Function array add: ${runOperation(0, 6, 2)}`);",
      "Console.WriteLine(`Function array multiply: ${runOperation(1, 6, 2)}`);",
      "Console.WriteLine(`Chosen add: ${chooseOperation(true)(9, 3)}`);",
      "Console.WriteLine(`Chosen divide: ${chooseOperation(false)(9, 3)}`);",
      "const pipeline = makePipeline(2);",
      "Console.WriteLine(`Nested returned function: ${pipeline(4)(3)}`);",
      "Console.WriteLine(`Interface function property: ${useFormatter(\"ok\", formatter)}`);",
      "Console.WriteLine(`Object method interface: ${useCalculator(calculator)}`);",
      "Console.WriteLine(`Object point: ${describePoint(point)}`);",
      "Console.WriteLine(`Inline object: ${describeInline({ name: \"items\", count: 3 })}`);",
      "Console.WriteLine(`Int object prop: ${readIntBox(intBox)}`);",
      "",
    ].join("\n"),
  });

  const build = runNode([cliPath, "build", "--project", resolve(projectDirectory, "tsonic.json")]);
  assert.equal(build.status, 0, build.stdout + build.stderr);
  assert.equal(runGeneratedProject(projectDirectory, assemblyName), [
    "Hello World",
    "Add: 10",
    "Is 4 even: True",
    "Is 5 even: False",
    "Day 0: weekend",
    "Day 3: weekday",
    "Day 6: weekend",
    "Day 7: invalid",
    "Nested scopes result: 65",
    "Nested scopes result: 60",
    "Arrow add: 8",
    "Arrow contextual sum: 15",
    "Arrow contextual diff: 5",
    "Closure count 1: 1",
    "Closure count 2: 2",
    "Closure add5: 8",
    "Optional without callback: 10",
    "Optional callback received: 20",
    "Optional transformed: 10",
    "Optional not transformed: 7",
    "Function array add: 8",
    "Function array multiply: 12",
    "Chosen add: 12",
    "Chosen divide: 3",
    "Nested returned function: 18",
    "Interface function property: **ok**",
    "Object method interface: 15",
    "Object point: p:7",
    "Inline object: items:3",
    "Int object prop: 42",
    "",
  ].join("\n"));
});

test("CLI runs generated C# executable preserving shadowed lexical bindings", async () => {
  const assemblyName = "SmokeGeneratedE2EShadowing";
  const projectDirectory = resolve(tempRoot, "e2e-shadowing");
  await writeProject(projectDirectory, {
    "tsonic.json": JSON.stringify({
      entryPoint: "index.ts",
      rootDir: "src",
      outDir: "out",
      targets: [{ id: "csharp", options: { namespace: "Smoke.Generated", assemblyName, outputType: "Exe" } }],
    }, null, 2),
    "src/index.ts": [
      "import { Console } from \"@tsonic/dotnet/System.js\";",
      "",
      "function shadowedVariable(): number {",
      "  const x = 10;",
      "  {",
      "    const x = 20;",
      "    return x;",
      "  }",
      "}",
      "",
      "function shadowInFunction(): number {",
      "  const value = 5;",
      "  const inner = (): number => {",
      "    const value = 10;",
      "    return value;",
      "  };",
      "  return value + inner();",
      "}",
      "",
      "Console.WriteLine(`Shadowed: ${shadowedVariable()}`);",
      "Console.WriteLine(`Shadow in function: ${shadowInFunction()}`);",
      "",
    ].join("\n"),
  });

  const build = runNode([cliPath, "build", "--project", resolve(projectDirectory, "tsonic.json")]);
  assert.equal(build.status, 0, build.stdout + build.stderr);
  assert.equal(runGeneratedProject(projectDirectory, assemblyName), [
    "Shadowed: 20",
    "Shadow in function: 15",
    "",
  ].join("\n"));
});
