import { assert, cliPath, resolve, runGeneratedProject, runNode, tempRoot, test, writeProject } from "./harness.mjs";

test("CLI runs generated C# executable for array literals, spreads, destructuring, and primitive element carriers", async () => {
  const assemblyName = "SmokeGeneratedE2EArrays";
  const projectDirectory = resolve(tempRoot, "e2e-arrays");
  await writeProject(projectDirectory, {
    "tsonic.json": JSON.stringify({
      entryPoint: "index.ts",
      rootDir: "src",
      outDir: "out",
      targets: [
        {
          id: "csharp",
          surfaces: ["js"],
          options: {
            namespace: "Smoke.Generated",
            assemblyName,
            outputType: "Exe",
          },
        },
      ],
    }, null, 2),
    "src/index.ts": [
      "import type { byte, decimal, float, int, long, short, uint, ulong } from \"@tsonic/csharp/types.js\";",
      "import { Console } from \"@tsonic/dotnet/System.js\";",
      "",
      "function createArray(): int[] {",
      "  const arr: int[] = [1, 2, 3];",
      "  return arr;",
      "}",
      "",
      "function destructure(arr: int[]): int {",
      "  const [first, second] = arr;",
      "  return first + second;",
      "}",
      "",
      "function createDoubleArray(): number[] {",
      "  const arr: number[] = [1, 2, 3];",
      "  return arr;",
      "}",
      "",
      "function returnDoubleArray(): number[] {",
      "  return [4, 5, 6];",
      "}",
      "",
      "function spreadArray(arr1: int[], arr2: int[]): int[] {",
      "  return [...arr1, ...arr2];",
      "}",
      "",
      "function getElement(matrix: number[][]): number {",
      "  return matrix[0][1];",
      "}",
      "",
      "function createMatrix(): number[][] {",
      "  return [",
      "    [1, 2],",
      "    [3, 4],",
      "  ];",
      "}",
      "",
      "const arr = createArray();",
      "Console.WriteLine(`Array: ${arr[0]}, ${arr[1]}, ${arr[2]}`);",
      "Console.WriteLine(`Length: ${arr.length}`);",
      "",
      "const destructInput: int[] = [10, 20, 30];",
      "Console.WriteLine(`Destructured sum: ${destructure(destructInput)}`);",
      "const directDestructureInput: int[] = [1, 2, 3];",
      "const [a, b, c] = directDestructureInput;",
      "Console.WriteLine(`Direct destructure: ${a}, ${b}, ${c}`);",
      "",
      "const arr1 = createDoubleArray();",
      "const arr2 = returnDoubleArray();",
      "Console.WriteLine(`Array1: ${arr1[0]}, ${arr1[1]}, ${arr1[2]}`);",
      "Console.WriteLine(`Array2: ${arr2[0]}, ${arr2[1]}, ${arr2[2]}`);",
      "",
      "const left: int[] = [1, 2, 3];",
      "const right: int[] = [4, 5, 6];",
      "const combined = spreadArray(left, right);",
      "Console.WriteLine(`Combined length: ${combined.length}`);",
      "Console.WriteLine(`Combined: ${combined[0]}, ${combined[1]}, ${combined[2]}, ${combined[3]}, ${combined[4]}, ${combined[5]}`);",
      "",
      "const matrix = createMatrix();",
      "Console.WriteLine(`Matrix[0][0]: ${matrix[0][0]}`);",
      "Console.WriteLine(`Matrix[0][1]: ${getElement(matrix)}`);",
      "Console.WriteLine(`Matrix[1][0]: ${matrix[1][0]}`);",
      "Console.WriteLine(`Matrix[1][1]: ${matrix[1][1]}`);",
      "",
      "const intArr: int[] = [1, 2, 3];",
      "Console.WriteLine(`int[]: ${intArr[0]}, ${intArr[1]}, ${intArr[2]}`);",
      "const longArr: long[] = [1, 2, 3];",
      "Console.WriteLine(`long[]: ${longArr[0]}, ${longArr[1]}, ${longArr[2]}`);",
      "const byteArr: byte[] = [1, 2, 3];",
      "Console.WriteLine(`byte[]: ${byteArr[0]}, ${byteArr[1]}, ${byteArr[2]}`);",
      "const shortArr: short[] = [1, 2, 3];",
      "Console.WriteLine(`short[]: ${shortArr[0]}, ${shortArr[1]}, ${shortArr[2]}`);",
      "const floatArr: float[] = [1.5, 2.5, 3.5];",
      "Console.WriteLine(`float[]: ${floatArr[0]}, ${floatArr[1]}, ${floatArr[2]}`);",
      "const doubleArr: number[] = [1.5, 2.5, 3.5];",
      "Console.WriteLine(`number[]: ${doubleArr[0]}, ${doubleArr[1]}, ${doubleArr[2]}`);",
      "const decimalArr: decimal[] = [1.5, 2.5, 3.5];",
      "Console.WriteLine(`decimal[]: ${decimalArr[0]}, ${decimalArr[1]}, ${decimalArr[2]}`);",
      "const uintArr: uint[] = [1, 2, 3];",
      "Console.WriteLine(`uint[]: ${uintArr[0]}, ${uintArr[1]}, ${uintArr[2]}`);",
      "const ulongArr: ulong[] = [1, 2, 3];",
      "Console.WriteLine(`ulong[]: ${ulongArr[0]}, ${ulongArr[1]}, ${ulongArr[2]}`);",
      "const longMatrix: long[][] = [[1, 2], [3, 4]];",
      "Console.WriteLine(`long[0][0]: ${longMatrix[0][0]}`);",
      "Console.WriteLine(`long[1][1]: ${longMatrix[1][1]}`);",
      "const floatMatrix: float[][] = [[1.5, 2.5], [3.5, 4.5]];",
      "Console.WriteLine(`float[0][0]: ${floatMatrix[0][0]}`);",
      "Console.WriteLine(`float[1][1]: ${floatMatrix[1][1]}`);",
      "Console.WriteLine(\"All array types compiled successfully!\");",
      "",
    ].join("\n"),
  });

  const build = runNode([cliPath, "build", "--project", resolve(projectDirectory, "tsonic.json")]);
  assert.equal(build.status, 0, build.stdout + build.stderr);
  assert.equal(runGeneratedProject(projectDirectory, assemblyName), [
    "Array: 1, 2, 3",
    "Length: 3",
    "Destructured sum: 30",
    "Direct destructure: 1, 2, 3",
    "Array1: 1, 2, 3",
    "Array2: 4, 5, 6",
    "Combined length: 6",
    "Combined: 1, 2, 3, 4, 5, 6",
    "Matrix[0][0]: 1",
    "Matrix[0][1]: 2",
    "Matrix[1][0]: 3",
    "Matrix[1][1]: 4",
    "int[]: 1, 2, 3",
    "long[]: 1, 2, 3",
    "byte[]: 1, 2, 3",
    "short[]: 1, 2, 3",
    "float[]: 1.5, 2.5, 3.5",
    "number[]: 1.5, 2.5, 3.5",
    "decimal[]: 1.5, 2.5, 3.5",
    "uint[]: 1, 2, 3",
    "ulong[]: 1, 2, 3",
    "long[0][0]: 1",
    "long[1][1]: 4",
    "float[0][0]: 1.5",
    "float[1][1]: 4.5",
    "All array types compiled successfully!",
    "",
  ].join("\n"));
});
