import { assert, cliPath, repoRoot, resolve, runGeneratedProject, runNode, tempRoot, test, writeProject } from "./harness.mjs";

test("CLI runs generated C# executable for module constants and variable declarations", async () => {
  const assemblyName = "SmokeGeneratedE2EVariables";
  const projectDirectory = resolve(tempRoot, "e2e-variables");
  await writeProject(projectDirectory, {
    "tsonic.json": JSON.stringify({
      entryPoint: "index.ts",
      rootDir: "src",
      outDir: "out",
      targets: [{ id: "csharp", options: { namespace: "Smoke.Generated", assemblyName, outputType: "Exe" } }],
    }, null, 2),
    "src/index.ts": [
      "import type { int32, uint8, int16, int64, float32 } from \"@tsonic/core/types.js\";",
      "import { Console } from \"@tsonic/dotnet/System.js\";",
      "",
      "const PI = 3.14159;",
      "const MESSAGE = \"Hello, World!\";",
      "const COUNT = 42;",
      "const IS_ENABLED = true;",
      "const explicitInt: int32 = 42;",
      "const explicitByte: uint8 = 255;",
      "const explicitShort: int16 = 1000;",
      "const explicitLong: int64 = 1000000;",
      "const explicitFloat: float32 = 1.5;",
      "const explicitDouble: number = 1.5;",
      "let mutableInt: int32 = 0;",
      "let mutableString: string = \"\";",
      "mutableInt = 100;",
      "mutableString = \"updated\";",
      "",
      "Console.writeLine(`PI: ${PI}`);",
      "Console.writeLine(`MESSAGE: ${MESSAGE}`);",
      "Console.writeLine(`COUNT: ${COUNT}`);",
      "Console.writeLine(`IS_ENABLED: ${IS_ENABLED}`);",
      "Console.writeLine(`Explicit int: ${explicitInt}`);",
      "Console.writeLine(`Explicit byte: ${explicitByte}`);",
      "Console.writeLine(`Explicit short: ${explicitShort}`);",
      "Console.writeLine(`Explicit long: ${explicitLong}`);",
      "Console.writeLine(`Explicit float: ${explicitFloat}`);",
      "Console.writeLine(`Explicit double: ${explicitDouble}`);",
      "Console.writeLine(`Mutable int: ${mutableInt}`);",
      "Console.writeLine(`Mutable string: ${mutableString}`);",
      "",
    ].join("\n"),
  });

  const build = runNode([cliPath, "build", "--project", resolve(projectDirectory, "tsonic.json")]);
  assert.equal(build.status, 0, build.stdout + build.stderr);
  assert.equal(runGeneratedProject(projectDirectory, assemblyName), [
    "PI: 3.14159",
    "MESSAGE: Hello, World!",
    "COUNT: 42",
    "IS_ENABLED: True",
    "Explicit int: 42",
    "Explicit byte: 255",
    "Explicit short: 1000",
    "Explicit long: 1000000",
    "Explicit float: 1.5",
    "Explicit double: 1.5",
    "Mutable int: 100",
    "Mutable string: updated",
    "",
  ].join("\n"));
});

test("CLI runs generated C# executable for functions, switches, and nested scopes", async () => {
  const assemblyName = "SmokeGeneratedE2EControlFlow";
  const projectDirectory = resolve(tempRoot, "e2e-control-flow");
  await writeProject(projectDirectory, {
    "tsonic.json": JSON.stringify({
      entryPoint: "index.ts",
      rootDir: "src",
      outDir: "out",
      targets: [{ id: "csharp", options: { namespace: "Smoke.Generated", assemblyName, outputType: "Exe" } }],
    }, null, 2),
    "src/index.ts": [
      "import type { int32 } from \"@tsonic/core/types.js\";",
      "import { Console } from \"@tsonic/dotnet/System.js\";",
      "",
      "function greet(name: string): string {",
      "  return `Hello ${name}`;",
      "}",
      "",
      "function add(a: number, b: number): number {",
      "  return a + b;",
      "}",
      "",
      "function isEven(n: number): boolean {",
      "  return n % 2 === 0;",
      "}",
      "",
      "function getDayType(day: number): string {",
      "  switch (day) {",
      "    case 0:",
      "    case 6:",
      "      return \"weekend\";",
      "    case 1:",
      "    case 2:",
      "    case 3:",
      "    case 4:",
      "    case 5:",
      "      return \"weekday\";",
      "    default:",
      "      return \"invalid\";",
      "  }",
      "}",
      "",
      "function nestedScopes(x: number): number {",
      "  const a = 10;",
      "  {",
      "    const b = 20;",
      "    {",
      "      const c = 30;",
      "      return a + b + c + x;",
      "    }",
      "  }",
      "}",
      "",
      "const arrowAdd = (left: number, right: number): number => left + right;",
      "",
      "function applyOperation(x: number, y: number, op: (left: number, right: number) => number): number {",
      "  return op(x, y);",
      "}",
      "",
      "function makeCounter(): () => number {",
      "  let count = 0;",
      "  return (): number => {",
      "    count++;",
      "    return count;",
      "  };",
      "}",
      "",
      "function makeAdder(value: number): (other: number) => number {",
      "  return (other: number): number => value + other;",
      "}",
      "",
      "type Callback = (result: int32) => void;",
      "",
      "function compute(value: int32, callback?: Callback): int32 {",
      "  const result = value * 2;",
      "  if (callback !== undefined) {",
      "    callback(result);",
      "  }",
      "  return result;",
      "}",
      "",
      "function maybeTransform(value: int32, transform: ((input: int32) => int32) | null): int32 {",
      "  if (transform !== null) {",
      "    return transform(value);",
      "  }",
      "  return value;",
      "}",
      "",
      "Console.writeLine(greet(\"World\"));",
      "Console.writeLine(`Add: ${add(3, 7)}`);",
      "Console.writeLine(`Is 4 even: ${isEven(4)}`);",
      "Console.writeLine(`Is 5 even: ${isEven(5)}`);",
      "Console.writeLine(`Day 0: ${getDayType(0)}`);",
      "Console.writeLine(`Day 3: ${getDayType(3)}`);",
      "Console.writeLine(`Day 6: ${getDayType(6)}`);",
      "Console.writeLine(`Day 7: ${getDayType(7)}`);",
      "Console.writeLine(`Nested scopes result: ${nestedScopes(5)}`);",
      "Console.writeLine(`Nested scopes result: ${nestedScopes(0)}`);",
      "Console.writeLine(`Arrow add: ${arrowAdd(3, 5)}`);",
      "Console.writeLine(`Arrow contextual sum: ${applyOperation(10, 5, (left, right) => left + right)}`);",
      "Console.writeLine(`Arrow contextual diff: ${applyOperation(10, 5, (left, right) => left - right)}`);",
      "const counterFn = makeCounter();",
      "Console.writeLine(`Closure count 1: ${counterFn()}`);",
      "Console.writeLine(`Closure count 2: ${counterFn()}`);",
      "const add5 = makeAdder(5);",
      "Console.writeLine(`Closure add5: ${add5(3)}`);",
      "Console.writeLine(`Optional without callback: ${compute(5)}`);",
      "compute(10, (result) => {",
      "  Console.writeLine(`Optional callback received: ${result}`);",
      "});",
      "Console.writeLine(`Optional transformed: ${maybeTransform(7, (input) => input + 3)}`);",
      "Console.writeLine(`Optional not transformed: ${maybeTransform(7, null)}`);",
      "",
    ].join("\n"),
  });

  const build = runNode([cliPath, "build", "--project", resolve(projectDirectory, "tsonic.json")]);
  assert.equal(build.status, 0, build.stdout + build.stderr);
  assert.equal(runGeneratedProject(projectDirectory, assemblyName), [
    "Hello World",
    "Add: 10",
    "Is 4 even: True",
    "Is 5 even: False",
    "Day 0: weekend",
    "Day 3: weekday",
    "Day 6: weekend",
    "Day 7: invalid",
    "Nested scopes result: 65",
    "Nested scopes result: 60",
    "Arrow add: 8",
    "Arrow contextual sum: 15",
    "Arrow contextual diff: 5",
    "Closure count 1: 1",
    "Closure count 2: 2",
    "Closure add5: 8",
    "Optional without callback: 10",
    "Optional callback received: 20",
    "Optional transformed: 10",
    "Optional not transformed: 7",
    "",
  ].join("\n"));
});

test("CLI runs generated C# executable preserving shadowed lexical bindings", async () => {
  const assemblyName = "SmokeGeneratedE2EShadowing";
  const projectDirectory = resolve(tempRoot, "e2e-shadowing");
  await writeProject(projectDirectory, {
    "tsonic.json": JSON.stringify({
      entryPoint: "index.ts",
      rootDir: "src",
      outDir: "out",
      targets: [{ id: "csharp", options: { namespace: "Smoke.Generated", assemblyName, outputType: "Exe" } }],
    }, null, 2),
    "src/index.ts": [
      "import { Console } from \"@tsonic/dotnet/System.js\";",
      "",
      "function shadowedVariable(): number {",
      "  const x = 10;",
      "  {",
      "    const x = 20;",
      "    return x;",
      "  }",
      "}",
      "",
      "function shadowInFunction(): number {",
      "  const value = 5;",
      "  const inner = (): number => {",
      "    const value = 10;",
      "    return value;",
      "  };",
      "  return value + inner();",
      "}",
      "",
      "Console.writeLine(`Shadowed: ${shadowedVariable()}`);",
      "Console.writeLine(`Shadow in function: ${shadowInFunction()}`);",
      "",
    ].join("\n"),
  });

  const build = runNode([cliPath, "build", "--project", resolve(projectDirectory, "tsonic.json")]);
  assert.equal(build.status, 0, build.stdout + build.stderr);
  assert.equal(runGeneratedProject(projectDirectory, assemblyName), [
    "Shadowed: 20",
    "Shadow in function: 15",
    "",
  ].join("\n"));
});

test("CLI runs generated C# executable for classes, inheritance, static members, and generic methods", async () => {
  const assemblyName = "SmokeGeneratedE2EClasses";
  const projectDirectory = resolve(tempRoot, "e2e-classes");
  await writeProject(projectDirectory, {
    "tsonic.json": JSON.stringify({
      entryPoint: "index.ts",
      rootDir: "src",
      outDir: "out",
      targets: [{ id: "csharp", options: { namespace: "Smoke.Generated", assemblyName, outputType: "Exe" } }],
    }, null, 2),
    "src/index.ts": [
      "import type { int32 } from \"@tsonic/core/types.js\";",
      "import { Console } from \"@tsonic/dotnet/System.js\";",
      "",
      "class Person {",
      "  name!: string;",
      "  age!: number;",
      "",
      "  greet(): string {",
      "    return `Hello, I'm ${this.name}`;",
      "  }",
      "",
      "  birthday(): void {",
      "    this.age++;",
      "  }",
      "}",
      "",
      "class User {",
      "  name: string;",
      "  email: string;",
      "  #password: string;",
      "",
      "  constructor(name: string, email: string, password: string) {",
      "    this.name = name;",
      "    this.email = email;",
      "    this.#password = password;",
      "  }",
      "",
      "  authenticate(input: string): boolean {",
      "    return input === this.#password;",
      "  }",
      "}",
      "",
      "class Counter {",
      "  count = 0;",
      "  name = \"default\";",
      "  active = true;",
      "",
      "  increment(): void {",
      "    this.count++;",
      "  }",
      "}",
      "",
      "class Animal {",
      "  name: string;",
      "",
      "  constructor(name: string) {",
      "    this.name = name;",
      "  }",
      "",
      "  makeSound(): string {",
      "    return \"Some sound\";",
      "  }",
      "}",
      "",
      "class Dog extends Animal {",
      "  breed: string;",
      "",
      "  constructor(name: string, breed: string) {",
      "    super(name);",
      "    this.breed = breed;",
      "  }",
      "",
      "  makeSound(): string {",
      "    return \"Woof!\";",
      "  }",
      "}",
      "",
      "class MathHelper {",
      "  static pi: number = 3.14159;",
      "  static e: number = 2.71828;",
      "",
      "  static square(x: number): number {",
      "    return x * x;",
      "  }",
      "",
      "  static cube(x: number): number {",
      "    return x * x * x;",
      "  }",
      "}",
      "",
      "function pick<T>(left: T, right: T, useRight: boolean): T {",
      "  return useRight ? right : left;",
      "}",
      "",
      "class Container<T> {",
      "  value: T;",
      "",
      "  constructor(value: T) {",
      "    this.value = value;",
      "  }",
      "",
      "  getValue(): T {",
      "    return this.value;",
      "  }",
      "}",
      "",
      "class IntContainer extends Container<int32> {",
      "  constructor(value: int32) {",
      "    super(value);",
      "  }",
      "",
      "  double(): int32 {",
      "    return this.value * 2;",
      "  }",
      "}",
      "",
      "class NamedEntity<TId> extends Container<TId> {",
      "  name: string;",
      "",
      "  constructor(id: TId, name: string) {",
      "    super(id);",
      "    this.name = name;",
      "  }",
      "}",
      "",
      "class Account extends NamedEntity<int32> {",
      "  email: string;",
      "",
      "  constructor(id: int32, name: string, email: string) {",
      "    super(id, name);",
      "    this.email = email;",
      "  }",
      "}",
      "",
      "interface Identifiable<T> {",
      "  id: T;",
      "}",
      "",
      "interface Named<T> extends Identifiable<T> {",
      "  name: string;",
      "}",
      "",
      "class Product implements Named<string> {",
      "  id: string;",
      "  name: string;",
      "",
      "  constructor(id: string, name: string) {",
      "    this.id = id;",
      "    this.name = name;",
      "  }",
      "}",
      "",
      "class GenericNamedItem<T> implements Named<T> {",
      "  id: T;",
      "  name: string;",
      "",
      "  constructor(id: T, name: string) {",
      "    this.id = id;",
      "    this.name = name;",
      "  }",
      "}",
      "",
      "class Wrapper<T> {",
      "  inner: T;",
      "",
      "  constructor(inner: T) {",
      "    this.inner = inner;",
      "  }",
      "}",
      "",
      "class NestedContainer<T> {",
      "  wrapped: Wrapper<T>;",
      "",
      "  constructor(value: T) {",
      "    this.wrapped = new Wrapper<T>(value);",
      "  }",
      "",
      "  getInner(): T {",
      "    return this.wrapped.inner;",
      "  }",
      "}",
      "",
      "class WrappedIntContainer extends NestedContainer<int32> {",
      "  constructor(value: int32) {",
      "    super(value);",
      "  }",
      "",
      "  addOne(): int32 {",
      "    const inner: int32 = this.getInner();",
      "    return inner + 1;",
      "  }",
      "}",
      "",
      "class Transformer<T> {",
      "  value: T;",
      "",
      "  constructor(value: T) {",
      "    this.value = value;",
      "  }",
      "",
      "  map<U>(fn: (x: T) => U): Transformer<U> {",
      "    return new Transformer<U>(fn(this.value));",
      "  }",
      "",
      "  replace(value: T): Transformer<T> {",
      "    return new Transformer<T>(value);",
      "  }",
      "}",
      "",
      "class GenericHelper {",
      "  transform<T, U>(value: T, fn: (input: T) => U): U {",
      "    return fn(value);",
      "  }",
      "",
      "  wrap<T>(value: T): Transformer<T> {",
      "    return new Transformer<T>(value);",
      "  }",
      "}",
      "",
      "const person = new Person();",
      "person.name = \"Alice\";",
      "person.age = 25;",
      "Console.writeLine(person.greet());",
      "Console.writeLine(`Age before: ${person.age}`);",
      "person.birthday();",
      "Console.writeLine(`Age after: ${person.age}`);",
      "",
      "const user = new User(\"Alice\", \"alice@example.com\", \"secret123\");",
      "Console.writeLine(`Name: ${user.name}`);",
      "Console.writeLine(`Email: ${user.email}`);",
      "Console.writeLine(`Auth correct: ${user.authenticate(\"secret123\")}`);",
      "Console.writeLine(`Auth wrong: ${user.authenticate(\"wrong\")}`);",
      "",
      "const counter = new Counter();",
      "counter.increment();",
      "counter.increment();",
      "Console.writeLine(`Counter: ${counter.count}, ${counter.name}, ${counter.active}`);",
      "",
      "const animal = new Animal(\"Generic\");",
      "const dog = new Dog(\"Buddy\", \"Golden Retriever\");",
      "const pet: Animal = dog;",
      "Console.writeLine(`Animal: ${animal.name}, Sound: ${animal.makeSound()}`);",
      "Console.writeLine(`Dog: ${dog.name}, Breed: ${dog.breed}, Sound: ${dog.makeSound()}`);",
      "Console.writeLine(`Pet sound: ${pet.makeSound()}`);",
      "",
      "Console.writeLine(`PI: ${MathHelper.pi}`);",
      "Console.writeLine(`E: ${MathHelper.e}`);",
      "Console.writeLine(`Square of 5: ${MathHelper.square(5)}`);",
      "Console.writeLine(`Cube of 3: ${MathHelper.cube(3)}`);",
      "Console.writeLine(`Pick int: ${pick<int32>(1, 2, true)}`);",
      "Console.writeLine(`Pick string: ${pick(\"left\", \"right\", false)}`);",
      "",
      "const intBox = new IntContainer(42);",
      "Console.writeLine(`Value: ${intBox.getValue()}`);",
      "Console.writeLine(`Doubled: ${intBox.double()}`);",
      "",
      "const account = new Account(1, \"Ada\", \"ada@example.com\");",
      "Console.writeLine(`Account ${account.value}: ${account.name} (${account.email})`);",
      "",
      "const product = new Product(\"SKU-001\", \"Widget\");",
      "Console.writeLine(`Product: ${product.id} - ${product.name}`);",
      "const namedItem = new GenericNamedItem<int32>(7, \"Seven\");",
      "Console.writeLine(`Named item: ${namedItem.id} - ${namedItem.name}`);",
      "const nested = new WrappedIntContainer(10);",
      "Console.writeLine(`Nested inner: ${nested.getInner()}`);",
      "Console.writeLine(`Nested plus one: ${nested.addOne()}`);",
      "const transformed = new Transformer<int32>(5).map<string>((x) => `Value: ${x}`);",
      "Console.writeLine(transformed.value);",
      "const replaced = new Transformer<int32>(10).replace(15);",
      "Console.writeLine(`Replaced: ${replaced.value}`);",
      "const helper = new GenericHelper();",
      "Console.writeLine(`Helper: ${helper.transform<int32, string>(7, (x) => `N=${x}`)}`);",
      "Console.writeLine(`Wrapped: ${helper.wrap<string>(\"ok\").value}`);",
      "",
    ].join("\n"),
  });

  const build = runNode([cliPath, "build", "--project", resolve(projectDirectory, "tsonic.json")]);
  assert.equal(build.status, 0, build.stdout + build.stderr);
  assert.equal(runGeneratedProject(projectDirectory, assemblyName), [
    "Hello, I'm Alice",
    "Age before: 25",
    "Age after: 26",
    "Name: Alice",
    "Email: alice@example.com",
    "Auth correct: True",
    "Auth wrong: False",
    "Counter: 2, default, True",
    "Animal: Generic, Sound: Some sound",
    "Dog: Buddy, Breed: Golden Retriever, Sound: Woof!",
    "Pet sound: Woof!",
    "PI: 3.14159",
    "E: 2.71828",
    "Square of 5: 25",
    "Cube of 3: 27",
    "Pick int: 2",
    "Pick string: left",
    "Value: 42",
    "Doubled: 84",
    "Account 1: Ada (ada@example.com)",
    "Product: SKU-001 - Widget",
    "Named item: 7 - Seven",
    "Nested inner: 10",
    "Nested plus one: 11",
    "Value: 5",
    "Replaced: 15",
    "Helper: N=7",
    "Wrapped: ok",
    "",
  ].join("\n"));
});

test("CLI runs generated C# executable for array literals, spreads, destructuring, and primitive element carriers", async () => {
  const assemblyName = "SmokeGeneratedE2EArrays";
  const projectDirectory = resolve(tempRoot, "e2e-arrays");
  await writeProject(projectDirectory, {
    "tsonic.json": JSON.stringify({
      entryPoint: "index.ts",
      rootDir: "src",
      outDir: "out",
      targets: [
        {
          id: "csharp",
          surfaces: ["js"],
          options: {
            namespace: "Smoke.Generated",
            assemblyName,
            outputType: "Exe",
            references: {
              projects: [
                resolve(repoRoot, "../csharp-runtime/src/Tsonic.CSharp.Runtime/Tsonic.CSharp.Runtime.csproj"),
              ],
            },
          },
        },
      ],
    }, null, 2),
    "src/index.ts": [
      "import type { decimal, float32, int16, int32, int64, uint8, uint32, uint64 } from \"@tsonic/core/types.js\";",
      "import { Console } from \"@tsonic/dotnet/System.js\";",
      "",
      "function createArray(): int32[] {",
      "  const arr: int32[] = [1, 2, 3];",
      "  return arr;",
      "}",
      "",
      "function destructure(arr: int32[]): int32 {",
      "  const [first, second] = arr;",
      "  return first + second;",
      "}",
      "",
      "function createDoubleArray(): number[] {",
      "  const arr: number[] = [1, 2, 3];",
      "  return arr;",
      "}",
      "",
      "function returnDoubleArray(): number[] {",
      "  return [4, 5, 6];",
      "}",
      "",
      "function spreadArray(arr1: int32[], arr2: int32[]): int32[] {",
      "  return [...arr1, ...arr2];",
      "}",
      "",
      "function getElement(matrix: number[][]): number {",
      "  return matrix[0][1];",
      "}",
      "",
      "function createMatrix(): number[][] {",
      "  return [",
      "    [1, 2],",
      "    [3, 4],",
      "  ];",
      "}",
      "",
      "const arr = createArray();",
      "Console.writeLine(`Array: ${arr[0]}, ${arr[1]}, ${arr[2]}`);",
      "Console.writeLine(`Length: ${arr.length}`);",
      "",
      "const destructInput: int32[] = [10, 20, 30];",
      "Console.writeLine(`Destructured sum: ${destructure(destructInput)}`);",
      "const directDestructureInput: int32[] = [1, 2, 3];",
      "const [a, b, c] = directDestructureInput;",
      "Console.writeLine(`Direct destructure: ${a}, ${b}, ${c}`);",
      "",
      "const arr1 = createDoubleArray();",
      "const arr2 = returnDoubleArray();",
      "Console.writeLine(`Array1: ${arr1[0]}, ${arr1[1]}, ${arr1[2]}`);",
      "Console.writeLine(`Array2: ${arr2[0]}, ${arr2[1]}, ${arr2[2]}`);",
      "",
      "const left: int32[] = [1, 2, 3];",
      "const right: int32[] = [4, 5, 6];",
      "const combined = spreadArray(left, right);",
      "Console.writeLine(`Combined length: ${combined.length}`);",
      "Console.writeLine(`Combined: ${combined[0]}, ${combined[1]}, ${combined[2]}, ${combined[3]}, ${combined[4]}, ${combined[5]}`);",
      "",
      "const matrix = createMatrix();",
      "Console.writeLine(`Matrix[0][0]: ${matrix[0][0]}`);",
      "Console.writeLine(`Matrix[0][1]: ${getElement(matrix)}`);",
      "Console.writeLine(`Matrix[1][0]: ${matrix[1][0]}`);",
      "Console.writeLine(`Matrix[1][1]: ${matrix[1][1]}`);",
      "",
      "const intArr: int32[] = [1, 2, 3];",
      "Console.writeLine(`int32[]: ${intArr[0]}, ${intArr[1]}, ${intArr[2]}`);",
      "const longArr: int64[] = [1, 2, 3];",
      "Console.writeLine(`int64[]: ${longArr[0]}, ${longArr[1]}, ${longArr[2]}`);",
      "const byteArr: uint8[] = [1, 2, 3];",
      "Console.writeLine(`uint8[]: ${byteArr[0]}, ${byteArr[1]}, ${byteArr[2]}`);",
      "const shortArr: int16[] = [1, 2, 3];",
      "Console.writeLine(`int16[]: ${shortArr[0]}, ${shortArr[1]}, ${shortArr[2]}`);",
      "const floatArr: float32[] = [1.5, 2.5, 3.5];",
      "Console.writeLine(`float32[]: ${floatArr[0]}, ${floatArr[1]}, ${floatArr[2]}`);",
      "const doubleArr: number[] = [1.5, 2.5, 3.5];",
      "Console.writeLine(`number[]: ${doubleArr[0]}, ${doubleArr[1]}, ${doubleArr[2]}`);",
      "const decimalArr: decimal[] = [1.5, 2.5, 3.5];",
      "Console.writeLine(`decimal[]: ${decimalArr[0]}, ${decimalArr[1]}, ${decimalArr[2]}`);",
      "const uintArr: uint32[] = [1, 2, 3];",
      "Console.writeLine(`uint32[]: ${uintArr[0]}, ${uintArr[1]}, ${uintArr[2]}`);",
      "const ulongArr: uint64[] = [1, 2, 3];",
      "Console.writeLine(`uint64[]: ${ulongArr[0]}, ${ulongArr[1]}, ${ulongArr[2]}`);",
      "const longMatrix: int64[][] = [[1, 2], [3, 4]];",
      "Console.writeLine(`int64[0][0]: ${longMatrix[0][0]}`);",
      "Console.writeLine(`int64[1][1]: ${longMatrix[1][1]}`);",
      "const floatMatrix: float32[][] = [[1.5, 2.5], [3.5, 4.5]];",
      "Console.writeLine(`float32[0][0]: ${floatMatrix[0][0]}`);",
      "Console.writeLine(`float32[1][1]: ${floatMatrix[1][1]}`);",
      "Console.writeLine(\"All array types compiled successfully!\");",
      "",
    ].join("\n"),
  });

  const build = runNode([cliPath, "build", "--project", resolve(projectDirectory, "tsonic.json")]);
  assert.equal(build.status, 0, build.stdout + build.stderr);
  assert.equal(runGeneratedProject(projectDirectory, assemblyName), [
    "Array: 1, 2, 3",
    "Length: 3",
    "Destructured sum: 30",
    "Direct destructure: 1, 2, 3",
    "Array1: 1, 2, 3",
    "Array2: 4, 5, 6",
    "Combined length: 6",
    "Combined: 1, 2, 3, 4, 5, 6",
    "Matrix[0][0]: 1",
    "Matrix[0][1]: 2",
    "Matrix[1][0]: 3",
    "Matrix[1][1]: 4",
    "int32[]: 1, 2, 3",
    "int64[]: 1, 2, 3",
    "uint8[]: 1, 2, 3",
    "int16[]: 1, 2, 3",
    "float32[]: 1.5, 2.5, 3.5",
    "number[]: 1.5, 2.5, 3.5",
    "decimal[]: 1.5, 2.5, 3.5",
    "uint32[]: 1, 2, 3",
    "uint64[]: 1, 2, 3",
    "int64[0][0]: 1",
    "int64[1][1]: 4",
    "float32[0][0]: 1.5",
    "float32[1][1]: 4.5",
    "All array types compiled successfully!",
    "",
  ].join("\n"));
});

test("CLI runs generated C# executable for nullish, optional, flow, ternary, and void semantics", async () => {
  const assemblyName = "SmokeGeneratedE2EControlFlow";
  const projectDirectory = resolve(tempRoot, "e2e-control-flow");
  await writeProject(projectDirectory, {
    "tsonic.json": JSON.stringify({
      entryPoint: "index.ts",
      rootDir: "src",
      outDir: "out",
      targets: [
        {
          id: "csharp",
          surfaces: ["js"],
          options: {
            namespace: "Smoke.Generated",
            assemblyName,
            outputType: "Exe",
            references: {
              projects: [
                resolve(repoRoot, "../csharp-runtime/src/Tsonic.CSharp.Runtime/Tsonic.CSharp.Runtime.csproj"),
              ],
            },
          },
        },
      ],
    }, null, 2),
    "src/index.ts": [
      "import type { int32 } from \"@tsonic/core/types.js\";",
      "import { Console } from \"@tsonic/dotnet/System.js\";",
      "",
      "class Box {",
      "  value: number = 5;",
      "  read(): number {",
      "    return this.value;",
      "  }",
      "}",
      "class Address {",
      "  city: string = \"Paris\";",
      "}",
      "class User {",
      "  name: string = \"Ada\";",
      "  address: Address | null = new Address();",
      "}",
      "",
      "function lengthOrZero(value: string | null): number {",
      "  if (typeof value === \"string\") {",
      "    return value.length;",
      "  }",
      "  return 0;",
      "}",
      "",
      "function fallbackString(value: string | null): string {",
      "  return value ?? \"missing\";",
      "}",
      "",
      "function fallbackInt(value: int32 | null): int32 {",
      "  return value ?? 42;",
      "}",
      "",
      "function fallbackNumber(value: number | null): number {",
      "  return value ?? 42;",
      "}",
      "",
      "function optionalValue(box: Box | null): number {",
      "  return box?.value ?? 9;",
      "}",
      "",
      "function optionalCall(box: Box | null): number {",
      "  return box?.read() ?? 11;",
      "}",
      "",
      "function optionalCity(user: User | null): string {",
      "  return user?.address?.city ?? \"none\";",
      "}",
      "",
      "function optionalNameLength(user: User | null): number {",
      "  return user?.name.length ?? 0;",
      "}",
      "",
      "function optionalElement(values: int32[] | null, index: int32): int32 {",
      "  return values?.[index] ?? 99;",
      "}",
      "",
      "function classify(value: int32): string {",
      "  if (value < 0) {",
      "    return \"negative\";",
      "  }",
      "  if (value === 0) {",
      "    return \"zero\";",
      "  }",
      "  return \"positive\";",
      "}",
      "",
      "function chooseInt(flag: boolean): int32 {",
      "  return flag ? 7 : 8;",
      "}",
      "",
      "function chooseNumber(flag: boolean): number {",
      "  return flag ? 1 : 2.5;",
      "}",
      "",
      "function returnIntInFlow(value: int32): int32 {",
      "  if (value > 0) {",
      "    return 10;",
      "  }",
      "  return 20;",
      "}",
      "",
      "function getInIf(condition: boolean): int32 {",
      "  if (condition) {",
      "    return 7 / 2;",
      "  }",
      "  return 100;",
      "}",
      "",
      "function getInElse(condition: boolean): int32 {",
      "  if (condition) {",
      "    return 10;",
      "  } else {",
      "    return 9 / 2;",
      "  }",
      "}",
      "",
      "function getInWhile(count: int32): int32 {",
      "  while (count > 0) {",
      "    return 15 / 4;",
      "  }",
      "  return 0;",
      "}",
      "",
      "function getInFor(): int32 {",
      "  for (let i: int32 = 0; i < 10; i++) {",
      "    return 11 / 3;",
      "  }",
      "  return 0;",
      "}",
      "",
      "function getInSwitch(key: int32): int32 {",
      "  switch (key) {",
      "    case 1:",
      "      return 13 / 4;",
      "    case 2:",
      "      return 17 / 5;",
      "    default:",
      "      return 19 / 6;",
      "  }",
      "}",
      "",
      "function getInNestedIf(a: boolean, b: boolean): int32 {",
      "  if (a) {",
      "    if (b) {",
      "      return 21 / 7;",
      "    }",
      "    return 100;",
      "  }",
      "  return 200;",
      "}",
      "",
      "function getWithNullish(value: int32 | null): int32 {",
      "  return value ?? 25 / 2;",
      "}",
      "",
      "function getFirstValid(a: int32 | null, b: int32 | null): int32 {",
      "  return a ?? b ?? 333;",
      "}",
      "",
      "function divideOrDefault(value: int32 | null, divisor: int32): int32 {",
      "  return value ?? 10 / divisor;",
      "}",
      "",
      "function nullishWithExpr(value: int32 | null, fallback: int32): int32 {",
      "  return value ?? fallback;",
      "}",
      "",
      "function nullishInVar(value: int32 | null): int32 {",
      "  const result: int32 = value ?? 42;",
      "  return result;",
      "}",
      "",
      "function nullishInIf(value: int32 | null, condition: boolean): int32 {",
      "  if (condition) {",
      "    return value ?? 50;",
      "  }",
      "  return value ?? 60;",
      "}",
      "",
      "function ternaryReturn(flag: boolean): int32 {",
      "  return flag ? 100 : 200;",
      "}",
      "",
      "function expectedIntThreading(): void {",
      "  const a: int32 = 7;",
      "  const b: int32 = 2;",
      "  const divResult: int32 = true ? a / b : 0;",
      "  const nested: int32 = true ? (false ? 1 : 2) : 3;",
      "  const deepNest: int32 = true ? (true ? (false ? 10 : 20) : 30) : 40;",
      "  const x: int32 = 10;",
      "  const y: int32 = 20;",
      "  const withArith: int32 = true ? x + 5 : y - 5;",
      "  let mutableInt: int32 = 0;",
      "  mutableInt = true ? 42 : 0;",
      "  Console.writeLine(`return if: ${getInIf(true)}`);",
      "  Console.writeLine(`return else: ${getInElse(false)}`);",
      "  Console.writeLine(`return while: ${getInWhile(1)}`);",
      "  Console.writeLine(`return for: ${getInFor()}`);",
      "  Console.writeLine(`return switch: ${getInSwitch(1)}, ${getInSwitch(2)}, ${getInSwitch(99)}`);",
      "  Console.writeLine(`return nested: ${getInNestedIf(true, true)}`);",
      "  Console.writeLine(`return nullish: ${getWithNullish(null)}`);",
      "  Console.writeLine(`first valid: ${getFirstValid(null, null)}, ${getFirstValid(null, 50)}, ${getFirstValid(25, 50)}`);",
      "  Console.writeLine(`divide default: ${divideOrDefault(null, 3)}, ${divideOrDefault(99, 3)}`);",
      "  Console.writeLine(`nullish expr: ${nullishWithExpr(null, 77)}, ${nullishWithExpr(88, 77)}`);",
      "  Console.writeLine(`nullish var: ${nullishInVar(null)}, ${nullishInVar(99)}`);",
      "  Console.writeLine(`nullish if: ${nullishInIf(null, true)}, ${nullishInIf(null, false)}, ${nullishInIf(70, false)}`);",
      "  Console.writeLine(`ternary divide: ${divResult}`);",
      "  Console.writeLine(`ternary nested: ${nested}, ${deepNest}`);",
      "  Console.writeLine(`ternary return: ${ternaryReturn(true)}, ${ternaryReturn(false)}`);",
      "  Console.writeLine(`ternary arithmetic: ${withArith}`);",
      "  Console.writeLine(`ternary assignment: ${mutableInt}`);",
      "}",
      "",
      "function trace(value: string): number {",
      "  Console.writeLine(`trace:${value}`);",
      "  return 123;",
      "}",
      "",
      "function runVoid(): void {",
      "  void trace(\"voided\");",
      "  Console.writeLine(\"after void\");",
      "}",
      "",
      "const box = new Box();",
      "const user = new User();",
      "Console.writeLine(`length string: ${lengthOrZero(\"abcd\")}`);",
      "Console.writeLine(`length null: ${lengthOrZero(null)}`);",
      "Console.writeLine(`fallback string: ${fallbackString(\"kept\")}`);",
      "Console.writeLine(`fallback string null: ${fallbackString(null)}`);",
      "Console.writeLine(`fallback int: ${fallbackInt(7)}`);",
      "Console.writeLine(`fallback int null: ${fallbackInt(null)}`);",
      "Console.writeLine(`fallback value: ${fallbackNumber(3.5)}`);",
      "Console.writeLine(`fallback null: ${fallbackNumber(null)}`);",
      "Console.writeLine(`optional value: ${optionalValue(box)}`);",
      "Console.writeLine(`optional value null: ${optionalValue(null)}`);",
      "Console.writeLine(`optional call: ${optionalCall(box)}`);",
      "Console.writeLine(`optional call null: ${optionalCall(null)}`);",
      "Console.writeLine(`optional city: ${optionalCity(user)}`);",
      "Console.writeLine(`optional city null: ${optionalCity(null)}`);",
      "Console.writeLine(`optional name length: ${optionalNameLength(user)}`);",
      "Console.writeLine(`optional name length null: ${optionalNameLength(null)}`);",
      "Console.writeLine(`optional element: ${optionalElement([4, 5, 6], 1)}`);",
      "Console.writeLine(`optional element null: ${optionalElement(null, 1)}`);",
      "Console.writeLine(`classify negative: ${classify(-1)}`);",
      "Console.writeLine(`classify zero: ${classify(0)}`);",
      "Console.writeLine(`classify positive: ${classify(2)}`);",
      "Console.writeLine(`choose int: ${chooseInt(true)}, ${chooseInt(false)}`);",
      "Console.writeLine(`choose number: ${chooseNumber(true)}, ${chooseNumber(false)}`);",
      "Console.writeLine(`return flow int: ${returnIntInFlow(1)}, ${returnIntInFlow(0)}`);",
      "expectedIntThreading();",
      "runVoid();",
      "",
    ].join("\n"),
  });

  const build = runNode([cliPath, "build", "--project", resolve(projectDirectory, "tsonic.json")]);
  assert.equal(build.status, 0, build.stdout + build.stderr);
  assert.equal(runGeneratedProject(projectDirectory, assemblyName), [
    "length string: 4",
    "length null: 0",
    "fallback string: kept",
    "fallback string null: missing",
    "fallback int: 7",
    "fallback int null: 42",
    "fallback value: 3.5",
    "fallback null: 42",
    "optional value: 5",
    "optional value null: 9",
    "optional call: 5",
    "optional call null: 11",
    "optional city: Paris",
    "optional city null: none",
    "optional name length: 3",
    "optional name length null: 0",
    "optional element: 5",
    "optional element null: 99",
    "classify negative: negative",
    "classify zero: zero",
    "classify positive: positive",
    "choose int: 7, 8",
    "choose number: 1, 2.5",
    "return flow int: 10, 20",
    "return if: 3",
    "return else: 4",
    "return while: 3",
    "return for: 3",
    "return switch: 3, 3, 3",
    "return nested: 3",
    "return nullish: 12",
    "first valid: 333, 50, 25",
    "divide default: 3, 99",
    "nullish expr: 77, 88",
    "nullish var: 42, 99",
    "nullish if: 50, 60, 70",
    "ternary divide: 3",
    "ternary nested: 2, 20",
    "ternary return: 100, 200",
    "ternary arithmetic: 15",
    "ternary assignment: 42",
    "trace:voided",
    "after void",
    "",
  ].join("\n"));
});
