import { assert, cliPath, resolve, runGeneratedProject, runNode, tempRoot, test, writeProject } from "./harness.mjs";

test("CLI runs generated C# executable for classes, inheritance, static members, and generic methods", async () => {
  const assemblyName = "SmokeGeneratedE2EClasses";
  const projectDirectory = resolve(tempRoot, "e2e-classes");
  await writeProject(projectDirectory, {
    "tsonic.json": JSON.stringify({
      entryPoint: "index.ts",
      rootDir: "src",
      outDir: "out",
      targets: [{ id: "csharp", options: { namespace: "Smoke.Generated", assemblyName, outputType: "Exe" } }],
    }, null, 2),
    "src/index.ts": [
      "import type { int } from \"@tsonic/csharp/types.js\";",
      "import { Console } from \"@tsonic/dotnet/System.js\";",
      "",
      "class Person {",
      "  name!: string;",
      "  age!: number;",
      "",
      "  greet(): string {",
      "    return `Hello, I'm ${this.name}`;",
      "  }",
      "",
      "  birthday(): void {",
      "    this.age++;",
      "  }",
      "}",
      "",
      "class User {",
      "  name: string;",
      "  email: string;",
      "  #password: string;",
      "",
      "  constructor(name: string, email: string, password: string) {",
      "    this.name = name;",
      "    this.email = email;",
      "    this.#password = password;",
      "  }",
      "",
      "  authenticate(input: string): boolean {",
      "    return input === this.#password;",
      "  }",
      "}",
      "",
      "class Counter {",
      "  count = 0;",
      "  name = \"default\";",
      "  active = true;",
      "",
      "  increment(): void {",
      "    this.count++;",
      "  }",
      "}",
      "",
      "class Animal {",
      "  name: string;",
      "",
      "  constructor(name: string) {",
      "    this.name = name;",
      "  }",
      "",
      "  makeSound(): string {",
      "    return \"Some sound\";",
      "  }",
      "}",
      "",
      "class Dog extends Animal {",
      "  breed: string;",
      "",
      "  constructor(name: string, breed: string) {",
      "    super(name);",
      "    this.breed = breed;",
      "  }",
      "",
      "  makeSound(): string {",
      "    return \"Woof!\";",
      "  }",
      "}",
      "",
      "class MathHelper {",
      "  static pi: number = 3.14159;",
      "  static e: number = 2.71828;",
      "",
      "  static square(x: number): number {",
      "    return x * x;",
      "  }",
      "",
      "  static cube(x: number): number {",
      "    return x * x * x;",
      "  }",
      "}",
      "",
      "function pick<T>(left: T, right: T, useRight: boolean): T {",
      "  return useRight ? right : left;",
      "}",
      "",
      "class Container<T> {",
      "  value: T;",
      "",
      "  constructor(value: T) {",
      "    this.value = value;",
      "  }",
      "",
      "  getValue(): T {",
      "    return this.value;",
      "  }",
      "}",
      "",
      "class IntContainer extends Container<int> {",
      "  constructor(value: int) {",
      "    super(value);",
      "  }",
      "",
      "  double(): int {",
      "    return this.getValue() * 2;",
      "  }",
      "}",
      "",
      "class NamedEntity<TId> extends Container<TId> {",
      "  name: string;",
      "",
      "  constructor(id: TId, name: string) {",
      "    super(id);",
      "    this.name = name;",
      "  }",
      "}",
      "",
      "class Account extends NamedEntity<int> {",
      "  email: string;",
      "",
      "  constructor(id: int, name: string, email: string) {",
      "    super(id, name);",
      "    this.email = email;",
      "  }",
      "}",
      "",
      "interface Identifiable<T> {",
      "  id: T;",
      "}",
      "",
      "interface Named<T> extends Identifiable<T> {",
      "  name: string;",
      "}",
      "",
      "class Product implements Named<string> {",
      "  id: string;",
      "  name: string;",
      "",
      "  constructor(id: string, name: string) {",
      "    this.id = id;",
      "    this.name = name;",
      "  }",
      "}",
      "",
      "class GenericNamedItem<T> implements Named<T> {",
      "  id: T;",
      "  name: string;",
      "",
      "  constructor(id: T, name: string) {",
      "    this.id = id;",
      "    this.name = name;",
      "  }",
      "}",
      "",
      "class Wrapper<T> {",
      "  inner: T;",
      "",
      "  constructor(inner: T) {",
      "    this.inner = inner;",
      "  }",
      "}",
      "",
      "class NestedContainer<T> {",
      "  wrapped: Wrapper<T>;",
      "",
      "  constructor(value: T) {",
      "    this.wrapped = new Wrapper<T>(value);",
      "  }",
      "",
      "  getInner(): T {",
      "    return this.wrapped.inner;",
      "  }",
      "}",
      "",
      "class WrappedIntContainer extends NestedContainer<int> {",
      "  constructor(value: int) {",
      "    super(value);",
      "  }",
      "",
      "  addOne(): int {",
      "    const inner: int = this.getInner();",
      "    return inner + 1;",
      "  }",
      "}",
      "",
      "class Transformer<T> {",
      "  value: T;",
      "",
      "  constructor(value: T) {",
      "    this.value = value;",
      "  }",
      "",
      "  map<U>(fn: (x: T) => U): Transformer<U> {",
      "    return new Transformer<U>(fn(this.value));",
      "  }",
      "",
      "  replace(value: T): Transformer<T> {",
      "    return new Transformer<T>(value);",
      "  }",
      "",
      "  getValue(): T {",
      "    return this.value;",
      "  }",
      "}",
      "",
      "class GenericHelper {",
      "  transform<T, U>(value: T, fn: (input: T) => U): U {",
      "    return fn(value);",
      "  }",
      "",
      "  wrap<T>(value: T): Transformer<T> {",
      "    return new Transformer<T>(value);",
      "  }",
      "}",
      "",
      "const person = new Person();",
      "person.name = \"Alice\";",
      "person.age = 25;",
      "Console.WriteLine(person.greet());",
      "Console.WriteLine(`Age before: ${person.age}`);",
      "person.birthday();",
      "Console.WriteLine(`Age after: ${person.age}`);",
      "",
      "const user = new User(\"Alice\", \"alice@example.com\", \"secret123\");",
      "Console.WriteLine(`Name: ${user.name}`);",
      "Console.WriteLine(`Email: ${user.email}`);",
      "Console.WriteLine(`Auth correct: ${user.authenticate(\"secret123\")}`);",
      "Console.WriteLine(`Auth wrong: ${user.authenticate(\"wrong\")}`);",
      "",
      "const counter = new Counter();",
      "counter.increment();",
      "counter.increment();",
      "Console.WriteLine(`Counter: ${counter.count}, ${counter.name}, ${counter.active}`);",
      "",
      "const animal = new Animal(\"Generic\");",
      "const dog = new Dog(\"Buddy\", \"Golden Retriever\");",
      "const pet: Animal = dog;",
      "Console.WriteLine(`Animal: ${animal.name}, Sound: ${animal.makeSound()}`);",
      "Console.WriteLine(`Dog: ${dog.name}, Breed: ${dog.breed}, Sound: ${dog.makeSound()}`);",
      "Console.WriteLine(`Pet sound: ${pet.makeSound()}`);",
      "",
      "Console.WriteLine(`PI: ${MathHelper.pi}`);",
      "Console.WriteLine(`E: ${MathHelper.e}`);",
      "Console.WriteLine(`Square of 5: ${MathHelper.square(5)}`);",
      "Console.WriteLine(`Cube of 3: ${MathHelper.cube(3)}`);",
      "Console.WriteLine(`Pick int: ${pick<int>(1, 2, true)}`);",
      "Console.WriteLine(`Pick string: ${pick(\"left\", \"right\", false)}`);",
      "",
      "const intBox = new IntContainer(42);",
      "Console.WriteLine(`Value: ${intBox.getValue()}`);",
      "Console.WriteLine(`Doubled: ${intBox.double()}`);",
      "",
      "const account = new Account(1, \"Ada\", \"ada@example.com\");",
      "Console.WriteLine(`Account ${account.getValue()}: ${account.name} (${account.email})`);",
      "",
      "const product = new Product(\"SKU-001\", \"Widget\");",
      "Console.WriteLine(`Product: ${product.id} - ${product.name}`);",
      "const namedItem = new GenericNamedItem<int>(7, \"Seven\");",
      "Console.WriteLine(`Named item: ${namedItem.id} - ${namedItem.name}`);",
      "const nested = new WrappedIntContainer(10);",
      "Console.WriteLine(`Nested inner: ${nested.getInner()}`);",
      "Console.WriteLine(`Nested plus one: ${nested.addOne()}`);",
      "const transformed = new Transformer<int>(5).map<string>((x) => `Value: ${x}`);",
      "Console.WriteLine(transformed.getValue());",
      "const replaced = new Transformer<int>(10).replace(15);",
      "Console.WriteLine(`Replaced: ${replaced.getValue()}`);",
      "const helper = new GenericHelper();",
      "Console.WriteLine(`Helper: ${helper.transform<int, string>(7, (x) => `N=${x}`)}`);",
      "Console.WriteLine(`Wrapped: ${helper.wrap<string>(\"ok\").value}`);",
      "",
    ].join("\n"),
  });

  const build = runNode([cliPath, "build", "--project", resolve(projectDirectory, "tsonic.json")]);
  assert.equal(build.status, 0, build.stdout + build.stderr);
  assert.equal(runGeneratedProject(projectDirectory, assemblyName), [
    "Hello, I'm Alice",
    "Age before: 25",
    "Age after: 26",
    "Name: Alice",
    "Email: alice@example.com",
    "Auth correct: True",
    "Auth wrong: False",
    "Counter: 2, default, True",
    "Animal: Generic, Sound: Some sound",
    "Dog: Buddy, Breed: Golden Retriever, Sound: Woof!",
    "Pet sound: Woof!",
    "PI: 3.14159",
    "E: 2.71828",
    "Square of 5: 25",
    "Cube of 3: 27",
    "Pick int: 2",
    "Pick string: left",
    "Value: 42",
    "Doubled: 84",
    "Account 1: Ada (ada@example.com)",
    "Product: SKU-001 - Widget",
    "Named item: 7 - Seven",
    "Nested inner: 10",
    "Nested plus one: 11",
    "Value: 5",
    "Replaced: 15",
    "Helper: N=7",
    "Wrapped: ok",
    "",
  ].join("\n"));
});
