/**
 * Generated auxiliary C# file emitters (JSON AOT and module container attribute).
 *
 * Extracted from emitter.ts — contains the logic that generates compiler-internal
 * support files (__tsonic_json.g.cs, __tsonic_module_containers.g.cs) using the
 * backend AST builder and printer.
 */

import type { JsonAotRegistry } from "./types.js";
import { printCompilationUnit } from "./core/format/backend-ast/printer.js";
import {
  identifierType as buildIdentifierType,
  qualifiedName,
} from "./core/format/backend-ast/builders.js";
import type {
  CSharpAttributeAst,
  CSharpCompilationUnitAst,
  CSharpExpressionAst,
  CSharpMemberAst,
  CSharpTriviaAst,
  CSharpTypeAst,
} from "./core/format/backend-ast/types.js";

const commentLine = (text: string): CSharpTriviaAst => ({
  kind: "singleLineCommentTrivia",
  text,
});

const blankLineTrivia = (): CSharpTriviaAst => ({
  kind: "blankLineTrivia",
});

const identifierType = (
  name: string,
  typeArguments?: readonly CSharpTypeAst[]
): CSharpTypeAst => buildIdentifierType(name, typeArguments);

const typeRef = (type: CSharpTypeAst): CSharpExpressionAst => ({
  kind: "typeReferenceExpression",
  type,
});

const memberAccess = (
  expression: CSharpExpressionAst,
  memberName: string
): CSharpExpressionAst => ({
  kind: "memberAccessExpression",
  expression,
  memberName,
});

const assignment = (
  left: CSharpExpressionAst,
  right: CSharpExpressionAst
): CSharpExpressionAst => ({
  kind: "assignmentExpression",
  operatorToken: "=",
  left,
  right,
});

const generatedFileLeadingTrivia = (
  ...lines: readonly string[]
): readonly CSharpTriviaAst[] => [...lines.map(commentLine), blankLineTrivia()];

export const generateModuleContainerAttributeFile = (): string => {
  const attributeUsageType = identifierType(
    "global::System.AttributeUsageAttribute"
  );
  const attributeTargetsType = identifierType(
    "global::System.AttributeTargets"
  );
  const systemAttributeType = identifierType("global::System.Attribute");

  const markerAttribute: CSharpAttributeAst = {
    type: attributeUsageType,
    arguments: [
      memberAccess(typeRef(attributeTargetsType), "Class"),
      assignment(
        { kind: "identifierExpression", identifier: "Inherited" },
        { kind: "booleanLiteralExpression", value: false }
      ),
      assignment(
        { kind: "identifierExpression", identifier: "AllowMultiple" },
        { kind: "booleanLiteralExpression", value: false }
      ),
    ],
  };

  const unit: CSharpCompilationUnitAst = {
    kind: "compilationUnit",
    leadingTrivia: generatedFileLeadingTrivia(
      "<auto-generated/>",
      "Marker attribute for module container types.",
      "Used by tsbindgen to generate flattened named exports for module-level values.",
      "WARNING: Do not modify this file manually"
    ),
    usings: [],
    members: [
      {
        kind: "namespaceDeclaration",
        name: qualifiedName("Tsonic.Internal"),
        members: [
          {
            kind: "classDeclaration",
            attributes: [markerAttribute],
            modifiers: ["internal", "sealed"],
            name: "ModuleContainerAttribute",
            baseType: systemAttributeType,
            interfaces: [],
            members: [],
          },
        ],
      },
    ],
  };

  return printCompilationUnit(unit);
};

/**
 * Generate the __tsonic_json.g.cs file for NativeAOT JSON support.
 * This file contains the JsonSerializerContext and options holder.
 */
export const generateJsonAotFile = (
  registry: JsonAotRegistry,
  rootNamespace: string
): string => {
  const types = [...registry.rootTypes.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([, typeAst]) => typeAst);

  const jsonSerializableType = identifierType(
    "global::System.Text.Json.Serialization.JsonSerializableAttribute"
  );
  const jsonSerializerContextType = identifierType(
    "global::System.Text.Json.Serialization.JsonSerializerContext"
  );
  const jsonSerializerOptionsType = identifierType(
    "global::System.Text.Json.JsonSerializerOptions"
  );
  const jsonNamingPolicyType = identifierType(
    "global::System.Text.Json.JsonNamingPolicy"
  );
  const jsonSerializableAttributes: readonly CSharpAttributeAst[] = types.map(
    (typeAst) => ({
      type: jsonSerializableType,
      arguments: [{ kind: "typeofExpression", type: typeAst }],
    })
  );

  const optionsField: CSharpMemberAst = {
    kind: "fieldDeclaration",
    attributes: [],
    modifiers: ["internal", "static", "readonly"],
    type: jsonSerializerOptionsType,
    name: "Options",
    initializer: {
      kind: "objectCreationExpression",
      type: jsonSerializerOptionsType,
      arguments: [],
      initializer: [
        assignment(
          { kind: "identifierExpression", identifier: "TypeInfoResolver" },
          memberAccess(
            typeRef(identifierType("__TsonicJsonContext")),
            "Default"
          )
        ),
        assignment(
          {
            kind: "identifierExpression",
            identifier: "PropertyNameCaseInsensitive",
          },
          { kind: "booleanLiteralExpression", value: true }
        ),
        assignment(
          { kind: "identifierExpression", identifier: "PropertyNamingPolicy" },
          memberAccess(typeRef(jsonNamingPolicyType), "CamelCase")
        ),
        assignment(
          { kind: "identifierExpression", identifier: "DictionaryKeyPolicy" },
          memberAccess(typeRef(jsonNamingPolicyType), "CamelCase")
        ),
      ],
    },
  };

  const unit: CSharpCompilationUnitAst = {
    kind: "compilationUnit",
    leadingTrivia: generatedFileLeadingTrivia(
      "<auto-generated/>",
      "Generated by Tsonic for NativeAOT JSON serialization support",
      "WARNING: Do not modify this file manually"
    ),
    usings: [],
    members: [
      {
        kind: "namespaceDeclaration",
        name: qualifiedName(rootNamespace),
        members: [
          {
            kind: "classDeclaration",
            attributes: jsonSerializableAttributes,
            modifiers: ["internal", "partial"],
            name: "__TsonicJsonContext",
            baseType: jsonSerializerContextType,
            interfaces: [],
            members: [],
          },
          {
            kind: "classDeclaration",
            attributes: [],
            modifiers: ["internal", "static"],
            name: "TsonicJson",
            interfaces: [],
            members: [optionsField],
          },
        ],
      },
    ],
  };

  return printCompilationUnit(unit);
};
