/**
 * Generated auxiliary C# file emitters (JSON AOT and module container attribute).
 *
 * Extracted from emitter.ts — contains the logic that generates compiler-internal
 * support files (__tsonic_json.g.cs, __tsonic_module_containers.g.cs) using the
 * backend AST builder and printer.
 */

import type { JsonAotRegistry } from "./types.js";
import type { RuntimeUnionRegistry } from "./core/semantic/runtime-union-registry.js";
import { printCompilationUnit } from "./core/format/backend-ast/printer.js";
import {
  identifierType as buildIdentifierType,
  qualifiedName,
} from "./core/format/backend-ast/builders.js";
import type {
  CSharpAttributeAst,
  CSharpCompilationUnitAst,
  CSharpExpressionAst,
  CSharpMemberAst,
  CSharpTriviaAst,
  CSharpTypeAst,
} from "./core/format/backend-ast/types.js";

const commentLine = (text: string): CSharpTriviaAst => ({
  kind: "singleLineCommentTrivia",
  text,
});

const blankLineTrivia = (): CSharpTriviaAst => ({
  kind: "blankLineTrivia",
});

const identifierType = (
  name: string,
  typeArguments?: readonly CSharpTypeAst[]
): CSharpTypeAst => buildIdentifierType(name, typeArguments);

const typeRef = (type: CSharpTypeAst): CSharpExpressionAst => ({
  kind: "typeReferenceExpression",
  type,
});

const memberAccess = (
  expression: CSharpExpressionAst,
  memberName: string
): CSharpExpressionAst => ({
  kind: "memberAccessExpression",
  expression,
  memberName,
});

const assignment = (
  left: CSharpExpressionAst,
  right: CSharpExpressionAst
): CSharpExpressionAst => ({
  kind: "assignmentExpression",
  operatorToken: "=",
  left,
  right,
});

const generatedFileLeadingTrivia = (
  ...lines: readonly string[]
): readonly CSharpTriviaAst[] => [...lines.map(commentLine), blankLineTrivia()];

export const generateModuleContainerAttributeFile = (): string => {
  const attributeUsageType = identifierType(
    "global::System.AttributeUsageAttribute"
  );
  const attributeTargetsType = identifierType(
    "global::System.AttributeTargets"
  );
  const systemAttributeType = identifierType("global::System.Attribute");

  const markerAttribute: CSharpAttributeAst = {
    type: attributeUsageType,
    arguments: [
      memberAccess(typeRef(attributeTargetsType), "Class"),
      assignment(
        { kind: "identifierExpression", identifier: "Inherited" },
        { kind: "booleanLiteralExpression", value: false }
      ),
      assignment(
        { kind: "identifierExpression", identifier: "AllowMultiple" },
        { kind: "booleanLiteralExpression", value: false }
      ),
    ],
  };

  const unit: CSharpCompilationUnitAst = {
    kind: "compilationUnit",
    leadingTrivia: generatedFileLeadingTrivia(
      "<auto-generated/>",
      "Marker attribute for module container types.",
      "Used by tsbindgen to generate flattened named exports for module-level values.",
      "WARNING: Do not modify this file manually"
    ),
    usings: [],
    members: [
      {
        kind: "namespaceDeclaration",
        name: qualifiedName("Tsonic.Internal"),
        members: [
          {
            kind: "classDeclaration",
            attributes: [markerAttribute],
            modifiers: ["internal", "sealed"],
            name: "ModuleContainerAttribute",
            baseType: systemAttributeType,
            interfaces: [],
            members: [],
          },
        ],
      },
    ],
  };

  return printCompilationUnit(unit);
};

export const generateArrayInteropFile = (): string => `// <auto-generated/>
// Compiler-owned native array wrapper interop support.
// WARNING: Do not modify this file manually

namespace Tsonic.Internal
{
    internal static class ArrayInterop
    {
        internal static global::js.Array<T> WrapArray<T>(global::System.Collections.Generic.IEnumerable<T> values)
        {
            var array = new global::js.Array<T>();
            foreach (var value in values)
            {
                array.push(value);
            }
            return array;
        }
    }
}
`;

const generateRuntimeUnionCarrier = (
  name: string,
  arity: number
): string => {
  const typeParameters = Array.from({ length: arity }, (_, index) => `T${index + 1}`);
  const genericParameters = typeParameters.join(", ");
  const carrierType = `${name}<${genericParameters}>`;
  const fromFactories = typeParameters
    .map(
      (typeParameter, index) =>
        `        public static ${carrierType} From${index + 1}(${typeParameter} value) => new ${carrierType}(value, ${index});`
    )
    .join("\n");
  const isChecks = typeParameters
    .map(
      (_, index) =>
        `        public bool Is${index + 1}() => _index == ${index};`
    )
    .join("\n");
  const asCasts = typeParameters
    .map(
      (typeParameter, index) => `        public ${typeParameter} As${index + 1}()
        {
            if (_index != ${index})
                throw new global::System.InvalidOperationException($"Union does not contain type {typeof(${typeParameter}).Name}");
            return (${typeParameter})_value!;
        }`
    )
    .join("\n\n");
  const tryAs = typeParameters
    .map(
      (typeParameter, index) => `        public bool TryAs${index + 1}(out ${typeParameter}? value)
        {
            if (_index == ${index})
            {
                value = (${typeParameter})_value!;
                return true;
            }
            value = default;
            return false;
        }`
    )
    .join("\n\n");
  const matchResultParameters = typeParameters
    .map(
      (typeParameter, index) =>
        `global::System.Func<${typeParameter}, TResult> onT${index + 1}`
    )
    .join(", ");
  const matchVoidParameters = typeParameters
    .map(
      (typeParameter, index) =>
        `global::System.Action<${typeParameter}> onT${index + 1}`
    )
    .join(", ");
  const matchResultCases = typeParameters
    .map(
      (typeParameter, index) =>
        `                ${index} => onT${index + 1}((${typeParameter})_value!),`
    )
    .join("\n");
  const matchVoidCases = typeParameters
    .map(
      (typeParameter, index) =>
        `                case ${index}: onT${index + 1}((${typeParameter})_value!); break;`
    )
    .join("\n");
  const implicitOperators = typeParameters
    .map(
      (typeParameter, index) =>
        `        public static implicit operator ${carrierType}(${typeParameter} value) => From${index + 1}(value);`
    )
    .join("\n");
  const equalityOperators = typeParameters
    .flatMap((typeParameter, index) => [
      `        public static bool operator ==(${carrierType}? left, ${typeParameter} right)
        {
            return left is not null && left._index == ${index} && global::System.Collections.Generic.EqualityComparer<${typeParameter}>.Default.Equals(left.As${index + 1}(), right);
        }`,
      `        public static bool operator !=(${carrierType}? left, ${typeParameter} right) => !(left == right);`,
      `        public static bool operator ==(${typeParameter} left, ${carrierType}? right) => right == left;`,
      `        public static bool operator !=(${typeParameter} left, ${carrierType}? right) => !(left == right);`,
    ])
    .join("\n\n");

  return `    public sealed class ${carrierType}
    {
        private readonly object? _value;
        private readonly int _index;

        private ${name}(object? value, int index)
        {
            _value = value;
            _index = index;
        }

${fromFactories}

${isChecks}

${asCasts}

${tryAs}

        public TResult Match<TResult>(${matchResultParameters})
        {
            return _index switch
            {
${matchResultCases}
                _ => throw new global::System.InvalidOperationException("Invalid union index"),
            };
        }

        public void Match(${matchVoidParameters})
        {
            switch (_index)
            {
${matchVoidCases}
                default:
                    throw new global::System.InvalidOperationException("Invalid union index");
            }
        }

${implicitOperators}

        public override string? ToString()
        {
            return _value?.ToString();
        }

        public override bool Equals(object? obj)
        {
            return obj is ${carrierType} other &&
                _index == other._index &&
                global::System.Collections.Generic.EqualityComparer<object?>.Default.Equals(_value, other._value);
        }

        public override int GetHashCode()
        {
            return global::System.HashCode.Combine(_value, _index);
        }

${equalityOperators}
    }`;
};

export const generateRuntimeUnionFile = (
  registry: RuntimeUnionRegistry
): string => {
  const definitions = [...registry.definitions.values()].sort(
    (left, right) =>
      left.arity - right.arity || left.name.localeCompare(right.name)
  );

  const carriers = definitions
    .map((definition) =>
      generateRuntimeUnionCarrier(definition.name, definition.arity)
    )
    .join("\n\n");

  return `// <auto-generated/>
// Compiler-owned runtime union carriers.
// WARNING: Do not modify this file manually

namespace Tsonic.Internal
{
${carriers}
}
`;
};

/**
 * Generate the __tsonic_json.g.cs file for NativeAOT JSON support.
 * This file contains the JsonSerializerContext and options holder.
 */
export const generateJsonAotFile = (
  registry: JsonAotRegistry,
  rootNamespace: string
): string => {
  const types = [...registry.rootTypes.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([, typeAst]) => typeAst);

  const jsonSerializableType = identifierType(
    "global::System.Text.Json.Serialization.JsonSerializableAttribute"
  );
  const jsonSerializerContextType = identifierType(
    "global::System.Text.Json.Serialization.JsonSerializerContext"
  );
  const jsonSerializerOptionsType = identifierType(
    "global::System.Text.Json.JsonSerializerOptions"
  );
  const jsonNamingPolicyType = identifierType(
    "global::System.Text.Json.JsonNamingPolicy"
  );
  const jsonSerializableAttributes: readonly CSharpAttributeAst[] = types.map(
    (typeAst) => ({
      type: jsonSerializableType,
      arguments: [{ kind: "typeofExpression", type: typeAst }],
    })
  );

  const optionsField: CSharpMemberAst = {
    kind: "fieldDeclaration",
    attributes: [],
    modifiers: ["internal", "static", "readonly"],
    type: jsonSerializerOptionsType,
    name: "Options",
    initializer: {
      kind: "objectCreationExpression",
      type: jsonSerializerOptionsType,
      arguments: [],
      initializer: [
        assignment(
          { kind: "identifierExpression", identifier: "TypeInfoResolver" },
          memberAccess(
            typeRef(identifierType("__TsonicJsonContext")),
            "Default"
          )
        ),
        assignment(
          {
            kind: "identifierExpression",
            identifier: "PropertyNameCaseInsensitive",
          },
          { kind: "booleanLiteralExpression", value: true }
        ),
        assignment(
          { kind: "identifierExpression", identifier: "PropertyNamingPolicy" },
          memberAccess(typeRef(jsonNamingPolicyType), "CamelCase")
        ),
        assignment(
          { kind: "identifierExpression", identifier: "DictionaryKeyPolicy" },
          memberAccess(typeRef(jsonNamingPolicyType), "CamelCase")
        ),
      ],
    },
  };

  const unit: CSharpCompilationUnitAst = {
    kind: "compilationUnit",
    leadingTrivia: generatedFileLeadingTrivia(
      "<auto-generated/>",
      "Generated by Tsonic for NativeAOT JSON serialization support",
      "WARNING: Do not modify this file manually"
    ),
    usings: [],
    members: [
      {
        kind: "namespaceDeclaration",
        name: qualifiedName(rootNamespace),
        members: [
          {
            kind: "classDeclaration",
            attributes: jsonSerializableAttributes,
            modifiers: ["internal", "partial"],
            name: "__TsonicJsonContext",
            baseType: jsonSerializerContextType,
            interfaces: [],
            members: [],
          },
          {
            kind: "classDeclaration",
            attributes: [],
            modifiers: ["internal", "static"],
            name: "TsonicJson",
            interfaces: [],
            members: [optionsField],
          },
        ],
      },
    ],
  };

  return printCompilationUnit(unit);
};

export const generateJsonRuntimeFile = (rootNamespace: string): string => `// <auto-generated/>
// Generated by Tsonic for dynamic JS JSON serialization support
// WARNING: Do not modify this file manually

namespace ${rootNamespace};

internal static class TsonicJsonRuntime
{
    internal static string Stringify(object? value)
    {
        using var stream = new global::System.IO.MemoryStream();
        using var writer = new global::System.Text.Json.Utf8JsonWriter(stream);
        WriteValue(writer, value);
        writer.Flush();
        return global::System.Text.Encoding.UTF8.GetString(stream.ToArray());
    }

    private static void WriteValue(global::System.Text.Json.Utf8JsonWriter writer, object? value)
    {
        switch (value)
        {
            case null:
                writer.WriteNullValue();
                return;
            case bool booleanValue:
                writer.WriteBooleanValue(booleanValue);
                return;
            case string stringValue:
                writer.WriteStringValue(stringValue);
                return;
            case char charValue:
                writer.WriteStringValue(charValue.ToString());
                return;
            case double doubleValue when !double.IsFinite(doubleValue):
                writer.WriteNullValue();
                return;
            case double doubleValue:
                writer.WriteNumberValue(doubleValue);
                return;
            case float floatValue when !float.IsFinite(floatValue):
                writer.WriteNullValue();
                return;
            case float floatValue:
                writer.WriteNumberValue(floatValue);
                return;
            case decimal decimalValue:
                writer.WriteNumberValue(decimalValue);
                return;
            case int intValue:
                writer.WriteNumberValue(intValue);
                return;
            case long longValue:
                writer.WriteNumberValue(longValue);
                return;
            case short shortValue:
                writer.WriteNumberValue(shortValue);
                return;
            case byte byteValue:
                writer.WriteNumberValue(byteValue);
                return;
            case uint uintValue:
                writer.WriteNumberValue(uintValue);
                return;
            case ulong ulongValue:
                writer.WriteNumberValue(ulongValue);
                return;
            case ushort ushortValue:
                writer.WriteNumberValue(ushortValue);
                return;
            case sbyte sbyteValue:
                writer.WriteNumberValue(sbyteValue);
                return;
        }

        if (TryWriteRuntimeUnion(writer, value))
        {
            return;
        }

        if (TryWriteToJsonProtocol(writer, value))
        {
            return;
        }

        switch (value)
        {
            case global::Tsonic.Runtime.DynamicObject dynamicObject:
                WriteDynamicObject(writer, dynamicObject);
                return;
            case global::System.Collections.Generic.IDictionary<string, object?> typedDictionary:
                WriteTypedDictionary(writer, typedDictionary);
                return;
            case global::System.Collections.IDictionary dictionary:
                WriteDictionary(writer, dictionary);
                return;
            case global::System.Collections.IEnumerable enumerable:
                WriteEnumerable(writer, enumerable);
                return;
        }

        throw new global::System.NotSupportedException(
            $"JSON.stringify does not support runtime value of type '{value.GetType().FullName}'.");
    }

    private static bool TryWriteRuntimeUnion(global::System.Text.Json.Utf8JsonWriter writer, object? value)
    {
        if (value == null)
        {
            return false;
        }

        var runtimeType = value.GetType();
        if (!runtimeType.IsGenericType || runtimeType.Namespace != "Tsonic.Runtime")
        {
            return false;
        }

        if (!runtimeType.Name.StartsWith("Union\`", global::System.StringComparison.Ordinal))
        {
            return false;
        }

        var arity = runtimeType.GetGenericArguments().Length;
        for (var index = 1; index <= arity; index += 1)
        {
            var isMethod = runtimeType.GetMethod(
                $"Is{index}",
                global::System.Type.EmptyTypes);
            if (isMethod == null)
            {
                continue;
            }

            if (isMethod.Invoke(value, null) is not bool isMatch || !isMatch)
            {
                continue;
            }

            var asMethod = runtimeType.GetMethod(
                $"As{index}",
                global::System.Type.EmptyTypes);
            if (asMethod == null)
            {
                break;
            }

            WriteValue(writer, asMethod.Invoke(value, null));
            return true;
        }

        throw new global::System.InvalidOperationException(
            $"Unable to read runtime union value from '{runtimeType.FullName}'.");
    }

    private static bool TryWriteToJsonProtocol(global::System.Text.Json.Utf8JsonWriter writer, object value)
    {
        var runtimeType = value.GetType();
        var toJson = runtimeType.GetMethod(
            "toJSON",
            global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public,
            binder: null,
            types: global::System.Type.EmptyTypes,
            modifiers: null);
        if (toJson == null || toJson.ReturnType == typeof(void))
        {
            return false;
        }

        WriteValue(writer, toJson.Invoke(value, null));
        return true;
    }

    private static void WriteDynamicObject(global::System.Text.Json.Utf8JsonWriter writer, global::Tsonic.Runtime.DynamicObject value)
    {
        writer.WriteStartObject();
        foreach (var key in value.GetKeys())
        {
            writer.WritePropertyName(key);
            WriteValue(writer, value[key]);
        }
        writer.WriteEndObject();
    }

    private static void WriteTypedDictionary(
        global::System.Text.Json.Utf8JsonWriter writer,
        global::System.Collections.Generic.IDictionary<string, object?> value)
    {
        writer.WriteStartObject();
        foreach (var entry in value)
        {
            writer.WritePropertyName(entry.Key);
            WriteValue(writer, entry.Value);
        }
        writer.WriteEndObject();
    }

    private static void WriteDictionary(
        global::System.Text.Json.Utf8JsonWriter writer,
        global::System.Collections.IDictionary value)
    {
        writer.WriteStartObject();
        foreach (global::System.Collections.DictionaryEntry entry in value)
        {
            if (entry.Key is not string key)
            {
                throw new global::System.NotSupportedException(
                    $"JSON.stringify only supports string dictionary keys. Got '{entry.Key?.GetType().FullName ?? "<null>"}'.");
            }

            writer.WritePropertyName(key);
            WriteValue(writer, entry.Value);
        }
        writer.WriteEndObject();
    }

    private static void WriteEnumerable(
        global::System.Text.Json.Utf8JsonWriter writer,
        global::System.Collections.IEnumerable value)
    {
        writer.WriteStartArray();
        foreach (var item in value)
        {
            WriteValue(writer, item);
        }
        writer.WriteEndArray();
    }

}
`;
