/**
 * Generated auxiliary C# file emitters (JSON AOT and module container attribute).
 *
 * Extracted from emitter.ts — contains the logic that generates compiler-internal
 * support files (__tsonic_json.g.cs, __tsonic_module_containers.g.cs) using the
 * backend AST builder and printer.
 */

import type { JsonAotRegistry } from "./types.js";
import { printCompilationUnit } from "./core/format/backend-ast/printer.js";
import {
  identifierType as buildIdentifierType,
  qualifiedName,
} from "./core/format/backend-ast/builders.js";
import type {
  CSharpAttributeAst,
  CSharpCompilationUnitAst,
  CSharpExpressionAst,
  CSharpMemberAst,
  CSharpTriviaAst,
  CSharpTypeAst,
} from "./core/format/backend-ast/types.js";

const commentLine = (text: string): CSharpTriviaAst => ({
  kind: "singleLineCommentTrivia",
  text,
});

const blankLineTrivia = (): CSharpTriviaAst => ({
  kind: "blankLineTrivia",
});

const identifierType = (
  name: string,
  typeArguments?: readonly CSharpTypeAst[]
): CSharpTypeAst => buildIdentifierType(name, typeArguments);

const typeRef = (type: CSharpTypeAst): CSharpExpressionAst => ({
  kind: "typeReferenceExpression",
  type,
});

const memberAccess = (
  expression: CSharpExpressionAst,
  memberName: string
): CSharpExpressionAst => ({
  kind: "memberAccessExpression",
  expression,
  memberName,
});

const assignment = (
  left: CSharpExpressionAst,
  right: CSharpExpressionAst
): CSharpExpressionAst => ({
  kind: "assignmentExpression",
  operatorToken: "=",
  left,
  right,
});

const generatedFileLeadingTrivia = (
  ...lines: readonly string[]
): readonly CSharpTriviaAst[] => [...lines.map(commentLine), blankLineTrivia()];

export const generateModuleContainerAttributeFile = (): string => {
  const attributeUsageType = identifierType(
    "global::System.AttributeUsageAttribute"
  );
  const attributeTargetsType = identifierType(
    "global::System.AttributeTargets"
  );
  const systemAttributeType = identifierType("global::System.Attribute");

  const markerAttribute: CSharpAttributeAst = {
    type: attributeUsageType,
    arguments: [
      memberAccess(typeRef(attributeTargetsType), "Class"),
      assignment(
        { kind: "identifierExpression", identifier: "Inherited" },
        { kind: "booleanLiteralExpression", value: false }
      ),
      assignment(
        { kind: "identifierExpression", identifier: "AllowMultiple" },
        { kind: "booleanLiteralExpression", value: false }
      ),
    ],
  };

  const unit: CSharpCompilationUnitAst = {
    kind: "compilationUnit",
    leadingTrivia: generatedFileLeadingTrivia(
      "<auto-generated/>",
      "Marker attribute for module container types.",
      "Used by tsbindgen to generate flattened named exports for module-level values.",
      "WARNING: Do not modify this file manually"
    ),
    usings: [],
    members: [
      {
        kind: "namespaceDeclaration",
        name: qualifiedName("Tsonic.Internal"),
        members: [
          {
            kind: "classDeclaration",
            attributes: [markerAttribute],
            modifiers: ["internal", "sealed"],
            name: "ModuleContainerAttribute",
            baseType: systemAttributeType,
            interfaces: [],
            members: [],
          },
        ],
      },
    ],
  };

  return printCompilationUnit(unit);
};

/**
 * Generate the __tsonic_json.g.cs file for NativeAOT JSON support.
 * This file contains the JsonSerializerContext and options holder.
 */
export const generateJsonAotFile = (
  registry: JsonAotRegistry,
  rootNamespace: string
): string => {
  const types = [...registry.rootTypes.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([, typeAst]) => typeAst);

  const jsonSerializableType = identifierType(
    "global::System.Text.Json.Serialization.JsonSerializableAttribute"
  );
  const jsonSerializerContextType = identifierType(
    "global::System.Text.Json.Serialization.JsonSerializerContext"
  );
  const jsonSerializerOptionsType = identifierType(
    "global::System.Text.Json.JsonSerializerOptions"
  );
  const jsonNamingPolicyType = identifierType(
    "global::System.Text.Json.JsonNamingPolicy"
  );
  const jsonSerializableAttributes: readonly CSharpAttributeAst[] = types.map(
    (typeAst) => ({
      type: jsonSerializableType,
      arguments: [{ kind: "typeofExpression", type: typeAst }],
    })
  );

  const optionsField: CSharpMemberAst = {
    kind: "fieldDeclaration",
    attributes: [],
    modifiers: ["internal", "static", "readonly"],
    type: jsonSerializerOptionsType,
    name: "Options",
    initializer: {
      kind: "objectCreationExpression",
      type: jsonSerializerOptionsType,
      arguments: [],
      initializer: [
        assignment(
          { kind: "identifierExpression", identifier: "TypeInfoResolver" },
          memberAccess(
            typeRef(identifierType("__TsonicJsonContext")),
            "Default"
          )
        ),
        assignment(
          {
            kind: "identifierExpression",
            identifier: "PropertyNameCaseInsensitive",
          },
          { kind: "booleanLiteralExpression", value: true }
        ),
        assignment(
          { kind: "identifierExpression", identifier: "PropertyNamingPolicy" },
          memberAccess(typeRef(jsonNamingPolicyType), "CamelCase")
        ),
        assignment(
          { kind: "identifierExpression", identifier: "DictionaryKeyPolicy" },
          memberAccess(typeRef(jsonNamingPolicyType), "CamelCase")
        ),
      ],
    },
  };

  const unit: CSharpCompilationUnitAst = {
    kind: "compilationUnit",
    leadingTrivia: generatedFileLeadingTrivia(
      "<auto-generated/>",
      "Generated by Tsonic for NativeAOT JSON serialization support",
      "WARNING: Do not modify this file manually"
    ),
    usings: [],
    members: [
      {
        kind: "namespaceDeclaration",
        name: qualifiedName(rootNamespace),
        members: [
          {
            kind: "classDeclaration",
            attributes: jsonSerializableAttributes,
            modifiers: ["internal", "partial"],
            name: "__TsonicJsonContext",
            baseType: jsonSerializerContextType,
            interfaces: [],
            members: [],
          },
          {
            kind: "classDeclaration",
            attributes: [],
            modifiers: ["internal", "static"],
            name: "TsonicJson",
            interfaces: [],
            members: [optionsField],
          },
        ],
      },
    ],
  };

  return printCompilationUnit(unit);
};

export const generateJsonRuntimeFile = (rootNamespace: string): string => `// <auto-generated/>
// Generated by Tsonic for dynamic JS JSON serialization support
// WARNING: Do not modify this file manually

namespace ${rootNamespace};

internal static class TsonicJsonRuntime
{
    internal static string Stringify(object? value)
    {
        using var stream = new global::System.IO.MemoryStream();
        using var writer = new global::System.Text.Json.Utf8JsonWriter(stream);
        WriteValue(writer, value);
        writer.Flush();
        return global::System.Text.Encoding.UTF8.GetString(stream.ToArray());
    }

    private static void WriteValue(global::System.Text.Json.Utf8JsonWriter writer, object? value)
    {
        switch (value)
        {
            case null:
                writer.WriteNullValue();
                return;
            case bool booleanValue:
                writer.WriteBooleanValue(booleanValue);
                return;
            case string stringValue:
                writer.WriteStringValue(stringValue);
                return;
            case char charValue:
                writer.WriteStringValue(charValue.ToString());
                return;
            case double doubleValue when !double.IsFinite(doubleValue):
                writer.WriteNullValue();
                return;
            case double doubleValue:
                writer.WriteNumberValue(doubleValue);
                return;
            case float floatValue when !float.IsFinite(floatValue):
                writer.WriteNullValue();
                return;
            case float floatValue:
                writer.WriteNumberValue(floatValue);
                return;
            case decimal decimalValue:
                writer.WriteNumberValue(decimalValue);
                return;
            case int intValue:
                writer.WriteNumberValue(intValue);
                return;
            case long longValue:
                writer.WriteNumberValue(longValue);
                return;
            case short shortValue:
                writer.WriteNumberValue(shortValue);
                return;
            case byte byteValue:
                writer.WriteNumberValue(byteValue);
                return;
            case uint uintValue:
                writer.WriteNumberValue(uintValue);
                return;
            case ulong ulongValue:
                writer.WriteNumberValue(ulongValue);
                return;
            case ushort ushortValue:
                writer.WriteNumberValue(ushortValue);
                return;
            case sbyte sbyteValue:
                writer.WriteNumberValue(sbyteValue);
                return;
        }

        if (TryWriteRuntimeUnion(writer, value))
        {
            return;
        }

        if (TryWriteToJsonProtocol(writer, value))
        {
            return;
        }

        switch (value)
        {
            case global::Tsonic.Runtime.DynamicObject dynamicObject:
                WriteDynamicObject(writer, dynamicObject);
                return;
            case global::System.Collections.Generic.IDictionary<string, object?> typedDictionary:
                WriteTypedDictionary(writer, typedDictionary);
                return;
            case global::System.Collections.IDictionary dictionary:
                WriteDictionary(writer, dictionary);
                return;
            case global::System.Collections.IEnumerable enumerable:
                WriteEnumerable(writer, enumerable);
                return;
        }

        throw new global::System.NotSupportedException(
            $"JSON.stringify does not support runtime value of type '{value.GetType().FullName}'.");
    }

    private static bool TryWriteRuntimeUnion(global::System.Text.Json.Utf8JsonWriter writer, object? value)
    {
        if (value == null)
        {
            return false;
        }

        var runtimeType = value.GetType();
        if (!runtimeType.IsGenericType || runtimeType.Namespace != "Tsonic.Runtime")
        {
            return false;
        }

        if (!runtimeType.Name.StartsWith("Union\`", global::System.StringComparison.Ordinal))
        {
            return false;
        }

        var arity = runtimeType.GetGenericArguments().Length;
        for (var index = 1; index <= arity; index += 1)
        {
            var isMethod = runtimeType.GetMethod(
                $"Is{index}",
                global::System.Type.EmptyTypes);
            if (isMethod == null)
            {
                continue;
            }

            if (isMethod.Invoke(value, null) is not bool isMatch || !isMatch)
            {
                continue;
            }

            var asMethod = runtimeType.GetMethod(
                $"As{index}",
                global::System.Type.EmptyTypes);
            if (asMethod == null)
            {
                break;
            }

            WriteValue(writer, asMethod.Invoke(value, null));
            return true;
        }

        throw new global::System.InvalidOperationException(
            $"Unable to read runtime union value from '{runtimeType.FullName}'.");
    }

    private static bool TryWriteToJsonProtocol(global::System.Text.Json.Utf8JsonWriter writer, object value)
    {
        var runtimeType = value.GetType();
        var toJson = runtimeType.GetMethod(
            "toJSON",
            global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public,
            binder: null,
            types: global::System.Type.EmptyTypes,
            modifiers: null);
        if (toJson == null || toJson.ReturnType == typeof(void))
        {
            return false;
        }

        WriteValue(writer, toJson.Invoke(value, null));
        return true;
    }

    private static void WriteDynamicObject(global::System.Text.Json.Utf8JsonWriter writer, global::Tsonic.Runtime.DynamicObject value)
    {
        writer.WriteStartObject();
        foreach (var key in value.GetKeys())
        {
            writer.WritePropertyName(key);
            WriteValue(writer, value[key]);
        }
        writer.WriteEndObject();
    }

    private static void WriteTypedDictionary(
        global::System.Text.Json.Utf8JsonWriter writer,
        global::System.Collections.Generic.IDictionary<string, object?> value)
    {
        writer.WriteStartObject();
        foreach (var entry in value)
        {
            writer.WritePropertyName(entry.Key);
            WriteValue(writer, entry.Value);
        }
        writer.WriteEndObject();
    }

    private static void WriteDictionary(
        global::System.Text.Json.Utf8JsonWriter writer,
        global::System.Collections.IDictionary value)
    {
        writer.WriteStartObject();
        foreach (global::System.Collections.DictionaryEntry entry in value)
        {
            if (entry.Key is not string key)
            {
                throw new global::System.NotSupportedException(
                    $"JSON.stringify only supports string dictionary keys. Got '{entry.Key?.GetType().FullName ?? "<null>"}'.");
            }

            writer.WritePropertyName(key);
            WriteValue(writer, entry.Value);
        }
        writer.WriteEndObject();
    }

    private static void WriteEnumerable(
        global::System.Text.Json.Utf8JsonWriter writer,
        global::System.Collections.IEnumerable value)
    {
        writer.WriteStartArray();
        foreach (var item in value)
        {
            WriteValue(writer, item);
        }
        writer.WriteEndArray();
    }

}
`;
