import "./build-tests/ref-dirs.test.js";
import "./build-tests/native-library-port-regressions-1.test.js";
import "./build-tests/native-library-port-regressions-2.test.js";
import "./build-tests/native-library-port-regressions-3.test.js";
import "./build-tests/native-library-port-regressions-4.test.js";
import "./build-tests/native-library-port-regressions-5.test.js";
import "./build-tests/native-library-port-regressions-6.test.js";
import "./build-tests/native-library-port-regressions-7.test.js";
import "./build-tests/native-library-port-regressions-8.test.js";
