import "./build-tests/ref-dirs.suite.js";
import "./build-tests/native-library-port-regressions-1.suite.js";
import "./build-tests/native-library-port-regressions-2.suite.js";
import "./build-tests/native-library-port-regressions-3.suite.js";
import "./build-tests/native-library-port-regressions-4.suite.js";
import "./build-tests/native-library-port-regressions-5.suite.js";
import "./build-tests/native-library-port-regressions-6.suite.js";
import "./build-tests/native-library-port-regressions-7.suite.js";
import "./build-tests/native-library-port-regressions-8.suite.js";
