export const jsRegExpSourceProfileIdentity = Object.freeze({
  owners: Object.freeze({
    regExp: "RegExp",
    regExpConstructor: "RegExpConstructor",
    regExpExecArray: "RegExpExecArray",
    regExpIndicesArray: "RegExpIndicesArray",
    regExpMatchArray: "RegExpMatchArray",
    regExpNamedGroups: "RegExpNamedGroups",
    regExpNamedIndices: "RegExpNamedIndices",
    regExpReplaceCallback: "RegExpReplaceCallback",
    regExpStringIterator: "RegExpStringIterator",
    string: "String",
    symbolConstructor: "SymbolConstructor",
  }),
  regExpMembers: Object.freeze({
    dotAll: "dotAll",
    exec: "exec",
    flags: "flags",
    global: "global",
    hasIndices: "hasIndices",
    ignoreCase: "ignoreCase",
    lastIndex: "lastIndex",
    multiline: "multiline",
    source: "source",
    sticky: "sticky",
    test: "test",
    toString: "toString",
    unicode: "unicode",
    unicodeSets: "unicodeSets",
  }),
  regExpConstructorMembers: Object.freeze({
    escape: "escape",
  }),
  wellKnownMemberKeys: Object.freeze({
    iterator: "@@iterator",
    match: "@@match",
    matchAll: "@@matchAll",
    replace: "@@replace",
    search: "@@search",
    species: "@@species",
    split: "@@split",
  }),
  regExpResultMembers: Object.freeze({
    first: "0",
    groups: "groups",
    index: "index",
    indices: "indices",
    input: "input",
  }),
  stringMembers: Object.freeze({
    match: "match",
    matchAll: "matchAll",
    replace: "replace",
    replaceAll: "replaceAll",
    search: "search",
    split: "split",
  }),
  symbolMembers: Object.freeze({
    match: "match",
    matchAll: "matchAll",
    replace: "replace",
    search: "search",
    species: "species",
    split: "split",
  }),
});
