/**
 * Binary operator expression emitter — main dispatch function.
 *
 * Extracted from binary-emitter.ts — contains the emitBinary entry point
 * that handles comparison, nullish, arithmetic, and standard binary operators.
 * The `in` and `instanceof` special cases are delegated to binary-special-ops.ts.
 *
 * NEW NUMERIC SPEC:
 * - Literals use raw lexeme (no contextual widening)
 * - Integer casts only from IrCastExpression (not inferred from expectedType)
 * - Binary ops: int op int = int, double op anything = double (C# semantics)
 */

import { IrExpression, IrType } from "@tsonic/frontend";
import { EmitterContext } from "../../types.js";
import { emitExpressionAst } from "../../expression-emitter.js";
import {
  resolveTypeAlias,
  stripNullish,
  isDefinitelyValueType,
} from "../../core/semantic/type-resolution.js";
import { willCarryAsRuntimeUnion } from "../../core/semantic/union-semantics.js";
import {
  isCharTyped,
  isCharType,
  isStringTyped,
  getSingleCharLiteral,
  isNullishLiteral,
  getDictionaryComputedAccess,
} from "./helpers.js";
import {
  charLiteral,
  decimalIntegerLiteral,
  identifierExpression,
  identifierType,
  nullLiteral,
} from "../../core/format/backend-ast/builders.js";
import type { CSharpExpressionAst } from "../../core/format/backend-ast/types.js";
import {
  getTransparentComparisonTarget,
  resolveComparisonOperandType,
  isNumericOperandType,
  chooseComparisonExpectedType,
  buildNullishComparisonContext,
} from "./binary-helpers.js";
import { emitInOperator, emitInstanceof } from "./binary-special-ops.js";

/**
 * Emit a binary operator expression as CSharpExpressionAst
 *
 * NEW NUMERIC SPEC: No contextual type propagation for numeric literals.
 * Literals use their raw lexeme - C# will naturally handle int + int = int,
 * int + double = double, etc.
 *
 * Explicit casts come from IrCastExpression nodes (generated by type-checker
 * when user intent allows int -> double coercion).
 *
 * STRING INDEXER FIX: In C#, string[int] returns char, not string.
 * When comparing a string indexer result with a single-character string literal,
 * we emit the string as a char literal to avoid CS0019 (char == string).
 *
 * @param expr - The binary expression
 * @param context - Emitter context
 * @param _expectedType - Currently unused
 */
export const emitBinary = (
  expr: Extract<IrExpression, { kind: "binary" }>,
  context: EmitterContext,
  _expectedType?: IrType
): [CSharpExpressionAst, EmitterContext] => {
  // Map JavaScript operators to C# operators
  const operatorMap: Record<string, string> = {
    "===": "==",
    "!==": "!=",
    "==": "==", // Loose equality - needs special handling
    "!=": "!=", // Loose inequality - needs special handling
    instanceof: "is",
    in: "/* in */", // Needs special handling
  };

  const op = operatorMap[expr.operator] ?? expr.operator;

  // Handle `"prop" in x` (union narrowing / dictionary membership)
  if (expr.operator === "in") {
    return emitInOperator(expr, context);
  }

  // Handle instanceof operator specially
  if (expr.operator === "instanceof") {
    return emitInstanceof(expr, context);
  }

  // CHAR VS STRING COMPARISON FIX:
  // In C#, string[int] returns char, but in TypeScript it returns string.
  // When comparing a char-typed expression with a single-character string literal,
  // emit the string as a char literal to avoid CS0019 (char == string).
  const isComparisonOp =
    op === "==" ||
    op === "!=" ||
    op === "<" ||
    op === ">" ||
    op === "<=" ||
    op === ">=";

  if (isComparisonOp) {
    const charExpectedType: IrType = {
      kind: "primitiveType",
      name: "char",
    };
    const leftIsChar =
      isCharTyped(expr.left) ||
      isCharType(resolveComparisonOperandType(expr.left, context));
    const rightIsChar =
      isCharTyped(expr.right) ||
      isCharType(resolveComparisonOperandType(expr.right, context));
    const leftSingleChar = getSingleCharLiteral(expr.left);
    const rightSingleChar = getSingleCharLiteral(expr.right);

    // Case 1: left is char-typed, right is single-char literal -> emit right as char
    if (leftIsChar && rightSingleChar !== undefined) {
      const [leftAst, leftContext] = emitExpressionAst(
        expr.left,
        context,
        charExpectedType
      );
      const charLiteralAst = charLiteral(rightSingleChar);
      return [
        {
          kind: "binaryExpression",
          operatorToken: op,
          left: leftAst,
          right: charLiteralAst,
        },
        leftContext,
      ];
    }

    // Case 2: right is char-typed, left is single-char literal -> emit left as char
    if (rightIsChar && leftSingleChar !== undefined) {
      const [rightAst, rightContext] = emitExpressionAst(
        expr.right,
        context,
        charExpectedType
      );
      const charLiteralAst = charLiteral(leftSingleChar);
      return [
        {
          kind: "binaryExpression",
          operatorToken: op,
          left: charLiteralAst,
          right: rightAst,
        },
        rightContext,
      ];
    }
  }

  // C# does not support relational operators directly on strings.
  // TypeScript's lexicographic ordering maps to ordinal string comparison.
  if (
    isComparisonOp &&
    (op === "<" || op === ">" || op === "<=" || op === ">=") &&
    isStringTyped(expr.left) &&
    isStringTyped(expr.right)
  ) {
    const [leftAst, leftContext] = emitExpressionAst(expr.left, context);
    const [rightAst, rightContext] = emitExpressionAst(expr.right, leftContext);
    const compareAst: CSharpExpressionAst = {
      kind: "invocationExpression",
      expression: {
        ...identifierExpression("global::System.String.CompareOrdinal"),
      },
      arguments: [leftAst, rightAst],
    };
    return [
      {
        kind: "binaryExpression",
        operatorToken: op,
        left: compareAst,
        right: decimalIntegerLiteral(0),
      },
      rightContext,
    ];
  }

  // NULLISH COMPARISONS:
  //
  // Prefer `== null` / `!= null` for normal reference/nullable types so the result
  // is expression-tree friendly (EF Core query providers do not support pattern matching).
  //
  // For unconstrained generics (T), `== null` is not always valid, so we instead cast
  // to `object` to force reference-equality semantics and avoid operator overloads:
  //   ((object)x) == null
  //
  // TypeScript:  x === undefined  ->  C#: x == null
  // TypeScript:  x !== undefined  ->  C#: x != null
  // TypeScript:  x === null       ->  C#: x == null
  // TypeScript:  x !== null       ->  C#: x != null
  const leftIsNullish = isNullishLiteral(expr.left);
  const rightIsNullish = isNullishLiteral(expr.right);
  const isNullishComparison =
    isComparisonOp &&
    (op === "==" || op === "!=") &&
    (leftIsNullish || rightIsNullish);

  if (isNullishComparison) {
    // One side is null/undefined literal, emit the other side as a C# null check.
    // Suppress only direct nullable unwrapping for the comparison target
    // (e.g. `id.Value == null` should stay `id == null`) while preserving
    // unrelated narrowing such as renamed union members.
    const nonNullishExpr = leftIsNullish ? expr.right : expr.left;
    const nonNullishTarget = getTransparentComparisonTarget(nonNullishExpr);
    const nullishExpr = leftIsNullish ? expr.left : expr.right;

    const isUndefinedLiteral =
      (nullishExpr.kind === "literal" && nullishExpr.value === undefined) ||
      (nullishExpr.kind === "identifier" && nullishExpr.name === "undefined");

    // JS dictionary-style access (`dict[key]`) with undefined comparison should
    // model key existence, not CLR value-type nullability.
    //
    //   dict[key] === undefined  -> !dict.ContainsKey(key)
    //   dict[key] !== undefined  ->  dict.ContainsKey(key)
    const dictionaryTarget = isUndefinedLiteral
      ? getDictionaryComputedAccess(nonNullishTarget, context)
      : undefined;
    if (dictionaryTarget) {
      const nonNullishContext = buildNullishComparisonContext(
        dictionaryTarget,
        context
      );
      const [dictAst, dictContext] = emitExpressionAst(
        dictionaryTarget.object,
        nonNullishContext
      );
      const [keyAst, keyContext] = emitExpressionAst(
        dictionaryTarget.property,
        dictContext
      );
      const containsAst: CSharpExpressionAst = {
        kind: "invocationExpression",
        expression: {
          kind: "memberAccessExpression",
          expression: {
            kind: "parenthesizedExpression",
            expression: dictAst,
          },
          memberName: "ContainsKey",
        },
        arguments: [keyAst],
      };
      const resultAst: CSharpExpressionAst =
        op === "=="
          ? {
              kind: "prefixUnaryExpression",
              operatorToken: "!",
              operand: containsAst,
            }
          : containsAst;
      return [resultAst, keyContext];
    }

    const nonNullishContext = buildNullishComparisonContext(
      nonNullishTarget,
      context
    );
    const [nonNullishAst, resultContext] = emitExpressionAst(
      nonNullishTarget,
      nonNullishContext
    );

    const inferred = resolveComparisonOperandType(
      nonNullishExpr,
      resultContext
    );
    const base = inferred ? stripNullish(inferred) : undefined;
    const hasRuntimeUnionCarrier =
      base !== undefined && willCarryAsRuntimeUnion(base, resultContext);
    const bareTypeParamName = (() => {
      if (!base) return undefined;
      if (base.kind === "typeParameterType") return base.name;
      if (
        base.kind === "referenceType" &&
        (resultContext.typeParameters?.has(base.name) ?? false) &&
        (!base.typeArguments || base.typeArguments.length === 0)
      ) {
        return base.name;
      }
      return undefined;
    })();

    const isDefiniteNonUnionValueType =
      inferred !== undefined &&
      inferred.kind !== "unionType" &&
      isDefinitelyValueType(inferred);

    const typeParamConstraint =
      bareTypeParamName !== undefined
        ? (resultContext.typeParamConstraints?.get(bareTypeParamName) ??
          "unconstrained")
        : undefined;

    const needsObjectCastForTypeParam =
      bareTypeParamName !== undefined &&
      (typeParamConstraint === "unconstrained" ||
        typeParamConstraint === "struct");
    const needsObjectCastForValueType = isDefiniteNonUnionValueType;
    const needsObjectCastForRuntimeUnion = hasRuntimeUnionCarrier;

    const nullLiteralAst = nullLiteral();
    const nullOp = op === "==" ? "==" : "!=";

    if (
      needsObjectCastForTypeParam ||
      needsObjectCastForValueType ||
      needsObjectCastForRuntimeUnion
    ) {
      // ((global::System.Object)(expr)) == null
      const castExpr: CSharpExpressionAst = {
        kind: "castExpression",
        type: identifierType("global::System.Object"),
        expression: {
          kind: "parenthesizedExpression",
          expression: nonNullishAst,
        },
      };
      return [
        {
          kind: "binaryExpression",
          operatorToken: nullOp,
          left: {
            kind: "parenthesizedExpression",
            expression: castExpr,
          },
          right: nullLiteralAst,
        },
        resultContext,
      ];
    }

    return [
      {
        kind: "binaryExpression",
        operatorToken: nullOp,
        left: nonNullishAst,
        right: nullLiteralAst,
      },
      resultContext,
    ];
  }

  const leftResolvedType = resolveComparisonOperandType(expr.left, context);
  const rightResolvedType = resolveComparisonOperandType(expr.right, context);
  const leftResolved = leftResolvedType
    ? resolveTypeAlias(stripNullish(leftResolvedType), context)
    : undefined;
  const rightResolved = rightResolvedType
    ? resolveTypeAlias(stripNullish(rightResolvedType), context)
    : undefined;
  const needsRuntimeEquality =
    (op === "==" || op === "!=") &&
    (leftResolved?.kind === "unknownType" ||
      rightResolved?.kind === "unknownType" ||
      (leftResolved?.kind === "referenceType" &&
        leftResolved.name === "object") ||
      (rightResolved?.kind === "referenceType" &&
        rightResolved.name === "object"));

  if (needsRuntimeEquality) {
    const [leftAst, leftContext] = emitExpressionAst(expr.left, context);
    const [rightAst, rightContext] = emitExpressionAst(expr.right, leftContext);
    const equalsAst: CSharpExpressionAst = {
      kind: "invocationExpression",
      expression: {
        kind: "memberAccessExpression",
        expression: {
          ...identifierExpression("global::System.Object"),
        },
        memberName: "Equals",
      },
      arguments: [leftAst, rightAst],
    };
    if (op === "==") {
      return [equalsAst, rightContext];
    }
    return [
      {
        kind: "prefixUnaryExpression",
        operatorToken: "!",
        operand: equalsAst,
      },
      rightContext,
    ];
  }

  const isArithmeticOp =
    op === "+" || op === "-" || op === "*" || op === "/" || op === "%";
  // Standard emission path
  // Emit operands without contextual type propagation
  // Literals will emit using their raw lexeme (42 vs 42.0)
  // Parenthesization is handled by the printer's precedence system
  const leftExpectedType = isComparisonOp
    ? chooseComparisonExpectedType(leftResolvedType, rightResolvedType, context)
    : isArithmeticOp &&
        expr.left.kind === "conditional" &&
        isNumericOperandType(rightResolvedType)
      ? rightResolvedType
      : undefined;
  const [leftAst, leftContext] = emitExpressionAst(
    expr.left,
    context,
    leftExpectedType
  );
  const rightExpectedType = isComparisonOp
    ? chooseComparisonExpectedType(rightResolvedType, leftResolvedType, context)
    : isArithmeticOp &&
        expr.right.kind === "conditional" &&
        isNumericOperandType(leftResolvedType)
      ? leftResolvedType
      : undefined;
  const [rightAst, rightContext] = emitExpressionAst(
    expr.right,
    leftContext,
    rightExpectedType
  );

  return [
    {
      kind: "binaryExpression",
      operatorToken: op,
      left: leftAst,
      right: rightAst,
    },
    rightContext,
  ];
};
