/**
 * Intermediate Representation (IR) types for Tsonic compiler
 * Main dispatcher - re-exports from specialized modules
 */

// Re-export everything from the split IR type modules.
export type {
  // Module types
  IrModule,
  IrImport,
  IrImportSpecifier,
  IrExport,
  // Statement types
  IrStatement,
  IrVariableDeclaration,
  IrVariableDeclarator,
  IrFunctionDeclaration,
  IrClassDeclaration,
  IrClassMember,
  IrMethodDeclaration,
  IrPropertyDeclaration,
  IrConstructorDeclaration,
  IrInterfaceDeclaration,
  IrEnumDeclaration,
  IrEnumMember,
  IrTypeAliasDeclaration,
  IrExpressionStatement,
  IrReturnStatement,
  IrIfStatement,
  IrWhileStatement,
  IrForStatement,
  IrForOfStatement,
  IrForInStatement,
  IrSwitchStatement,
  IrSwitchCase,
  IrThrowStatement,
  IrTryStatement,
  IrCatchClause,
  IrBlockStatement,
  IrBreakStatement,
  IrContinueStatement,
  IrEmptyStatement,
  IrYieldStatement,
  IrGeneratorReturnStatement,
  IrOverloadOwnerKind,
  IrOverloadFamilyMember,
  // Expression types
  IrExpression,
  IrLiteralExpression,
  IrIdentifierExpression,
  IrArrayExpression,
  IrObjectExpression,
  IrObjectProperty,
  IrFunctionExpression,
  IrArrowFunctionExpression,
  IrMemberExpression,
  IrCallExpression,
  IrNewExpression,
  IrThisExpression,
  IrUpdateExpression,
  IrUnaryExpression,
  IrBinaryExpression,
  IrLogicalExpression,
  IrConditionalExpression,
  IrAssignmentExpression,
  IrTemplateLiteralExpression,
  IrSpreadExpression,
  IrAwaitExpression,
  IrYieldExpression,
  IrNumericNarrowingExpression,
  IrTypeAssertionExpression,
  IrAsInterfaceExpression,
  IrTryCastExpression,
  IrStackAllocExpression,
  IrDefaultOfExpression,
  IrNameOfExpression,
  IrSizeOfExpression,
  NumericProof,
  ProofSource,
  ComputedAccessKind,
  ComputedAccessProtocol,
  // Type system types
  IrType,
  IrPrimitiveType,
  IrReferenceType,
  IrArrayType,
  IrTupleType,
  IrFunctionType,
  IrObjectType,
  IrDictionaryType,
  IrUnionType,
  IrIntersectionType,
  IrLiteralType,
  IrAnyType,
  IrUnknownType,
  IrVoidType,
  IrNeverType,
  // Attribute types
  IrAttributeTarget,
  IrAttribute,
  IrAttributePrimitiveArg,
  IrAttributeArg,
  // Helper types
  IrPattern,
  IrIdentifierPattern,
  IrArrayPattern,
  IrObjectPattern,
  IrObjectPatternProperty,
  IrTypeParameter,
  IrParameter,
  IrInterfaceMember,
  IrPropertySignature,
  IrMethodSignature,
  IrAccessibility,
  IrBinaryOperator,
  IrAssignmentOperator,
  // Numeric types
  NumericKind,
} from "./types/index.js";

// Re-export type guards
export { isStatement, isExpression } from "./types/guards.js";

// Re-export numeric utilities
export {
  TSONIC_TO_NUMERIC_KIND,
  NUMERIC_KIND_TO_CSHARP,
  NUMERIC_RANGES,
  getAwaitedIrType,
  getSpreadTupleShape,
  isIntegerKind,
  isAwaitableIrType,
  isSignedKind,
  getBinaryResultKind,
  literalFitsInKind,
  isWideningConversion,
  stableIrTypeKey,
  stableIrTypeKeyIfDeterministic,
  runtimeUnionCarrierFamilyKey,
  runtimeUnionAliasCarrierFamilyKey,
  hasRuntimeUnionCarrierShape,
  stampRuntimeUnionAliasCarrier,
  irTypesEqual,
  normalizedUnionType,
  substituteIrType,
  getIrMemberPublicName,
  // Numeric helpers (literal type inference)
  isValidIntegerLexeme,
  parseBigIntFromRaw,
  bigIntFitsInKind,
  inferNumericKindFromRaw,
} from "./types/index.js";
