/**
 * Intermediate Representation (IR) types for Tsonic compiler
 * Main dispatcher - re-exports from specialized modules
 */

// Re-export everything from types subdirectory for backward compatibility
export type {
  // Module types
  IrModule,
  IrImport,
  IrImportSpecifier,
  IrExport,
  // Statement types
  IrStatement,
  IrVariableDeclaration,
  IrVariableDeclarator,
  IrFunctionDeclaration,
  IrClassDeclaration,
  IrClassMember,
  IrMethodDeclaration,
  IrPropertyDeclaration,
  IrConstructorDeclaration,
  IrInterfaceDeclaration,
  IrEnumDeclaration,
  IrEnumMember,
  IrTypeAliasDeclaration,
  IrExpressionStatement,
  IrReturnStatement,
  IrIfStatement,
  IrWhileStatement,
  IrForStatement,
  IrForOfStatement,
  IrForInStatement,
  IrSwitchStatement,
  IrSwitchCase,
  IrThrowStatement,
  IrTryStatement,
  IrCatchClause,
  IrBlockStatement,
  IrBreakStatement,
  IrContinueStatement,
  IrEmptyStatement,
  IrYieldStatement,
  IrGeneratorReturnStatement,
  // Expression types
  IrExpression,
  IrLiteralExpression,
  IrIdentifierExpression,
  IrArrayExpression,
  IrObjectExpression,
  IrObjectProperty,
  IrFunctionExpression,
  IrArrowFunctionExpression,
  IrMemberExpression,
  IrCallExpression,
  IrNewExpression,
  IrThisExpression,
  IrUpdateExpression,
  IrUnaryExpression,
  IrBinaryExpression,
  IrLogicalExpression,
  IrConditionalExpression,
  IrAssignmentExpression,
  IrTemplateLiteralExpression,
  IrSpreadExpression,
  IrAwaitExpression,
  IrYieldExpression,
  IrNumericNarrowingExpression,
  IrTypeAssertionExpression,
  IrTryCastExpression,
  IrStackAllocExpression,
  NumericProof,
  ProofSource,
  ComputedAccessKind,
  // Type system types
  IrType,
  IrPrimitiveType,
  IrReferenceType,
  IrArrayType,
  IrTupleType,
  IrFunctionType,
  IrObjectType,
  IrDictionaryType,
  IrUnionType,
  IrIntersectionType,
  IrLiteralType,
  IrAnyType,
  IrUnknownType,
  IrVoidType,
  IrNeverType,
  // Attribute types
  IrAttribute,
  IrAttributePrimitiveArg,
  IrAttributeArg,
  // Helper types
  IrPattern,
  IrIdentifierPattern,
  IrArrayPattern,
  IrObjectPattern,
  IrObjectPatternProperty,
  IrTypeParameter,
  IrParameter,
  IrInterfaceMember,
  IrPropertySignature,
  IrMethodSignature,
  IrAccessibility,
  IrBinaryOperator,
  IrAssignmentOperator,
  // Numeric types
  NumericKind,
} from "./types/index.js";

// Re-export type guards
export { isStatement, isExpression } from "./types/guards.js";

// Re-export numeric utilities
export {
  TSONIC_TO_NUMERIC_KIND,
  NUMERIC_KIND_TO_CSHARP,
  NUMERIC_RANGES,
  isIntegerKind,
  isSignedKind,
  getBinaryResultKind,
  literalFitsInKind,
  isWideningConversion,
  // Numeric helpers (literal type inference)
  isValidIntegerLexeme,
  parseBigIntFromRaw,
  bigIntFitsInKind,
  inferNumericKindFromRaw,
} from "./types/index.js";
