export { CommandLine } from "./internal/execute/tsc.js";
export type { CommandLineResult, CommandLineTesting, ExitStatus, System } from "./internal/execute/tsc/compile.js";
export { LibPath, WrapFS as WrapBundledFileSystem } from "./internal/bundled/bundled.js";
export { NewCachedFSCompilerHost, NewCompilerHost } from "./internal/compiler/host.js";
export type { CompilerHost } from "./internal/compiler/host.js";
export {
  NewProgram,
  Program_BindSourceFiles,
  Program_GetConfigFileParsingDiagnostics,
  Program_GetProgramDiagnostics,
  Program_GetSemanticDiagnostics,
  Program_GetSourceFiles,
  Program_GetSyntacticDiagnostics,
} from "./internal/compiler/program.js";
export type { Program, ProgramLike, ProgramOptions } from "./internal/compiler/program.js";
export { Background } from "./go/context.js";
export { ExtensionConsumerQueries, ExtensionDecisionQuestion, ExtensionDiagnosticStore, ExtensionFactResolver, ExtensionFactStore, ExtensionHost, ExtensionHostDiagnosticCode, ExtensionLifecycleEvent, ProviderRegistry, TstsProviderContractVersion, acceptDecision, argumentPassingFactKey, associatedTypeFactKey, attachExtensionHost, canonicalIdentityFactKey, contextualTargetTypeFactKey, constGenericFactKey, createExtensionConsumerQueries, createSourceSemanticsExtension, defineExtensionFactKey, deferDecision, finalizeExtensionSemantics, flowStateFactKey, functionPointerFactKey, getExtensionHost, hasExtensionHost, instantiatedTargetTypeFactKey, pointerFactKey, providerVirtualDeclarationFactKey, rejectDecision, runtimeCarrierFactKey, selectedTargetSignatureFactKey, sourcePrimitive, sourcePrimitiveFactKey, targetBindingFactKey, targetOperationFactKey, valueTypeFactKey } from "./extensions/index.js";
export type { ArgumentPassingFact, ArgumentPassingMode, AssignabilityRequest, AssociatedTypeFact, AttributeFact, BeforeSemanticsFinalizedLifecycleRequest, CompilerExtension, CompilerExtensionKind, CompilerExtensionIdentity, ConstGenericFact, ContextualTargetTypeFact, ContextualTypeRequest, ContextualTypeResult, ExtendedProgram, ExtensionCanonicalIdentity, ExtensionCanonicalIdentityKind, ExtensionCapabilitySpec, ExtensionCompositionSpec, ExtensionDecision, ExtensionDecisionContext, ExtensionDecisionHook, ExtensionDecisionMap, ExtensionDecisionQuestionName, ExtensionDecisionRequest, ExtensionDecisionResponse, ExtensionDecisionResult, ExtensionDecisionRunOptions, ExtensionDependencySpec, ExtensionDiagnostic, ExtensionDiagnosticCategory, ExtensionDiagnosticRange, ExtensionEvidence, ExtensionFactEntry, ExtensionFactKey, ExtensionFactKeyOptions, ExtensionFactResolution, ExtensionFactResolverCallback, ExtensionFactResolverContext, ExtensionFactSubject, ExtensionFactWriteResult, ExtensionHostOptions, ExtensionImportKind, ExtensionInitializeContext, ExtensionLifecycleContext, ExtensionLifecycleHook, FieldFact, FlowStateFact, FunctionPointerFact, InferTypeArgumentsRequest, InferTypeArgumentsResult, InstantiatedTargetTypeFact, ParameterModeRequest, ParameterModeResult, PointerFact, ProviderDeclarationKind, ProviderDeclarationModel, ProviderExportDeclaration, ProviderIdentity, ProviderMemberDeclaration, ProviderModuleContext, ProviderModuleResolution, ProviderModuleResolveResult, ProviderOwnership, ProviderParameterDeclaration, ProviderResolvedModule, ProviderSignatureDeclaration, ProviderSymbolIdentity, ProviderTypeExpression, ProviderTypeParameterDeclaration, ProviderVirtualDeclarationFact, ResolveCallRequest, ResolveCallResult, ResolveConversionRequest, ResolveConversionResult, ResolveElementAccessRequest, ResolveOperationResult, ResolveOperatorRequest, ResolvePropertyAccessRequest, RuntimeCarrierFact, RuntimeCarrierRequest, RuntimeCarrierResult, SatisfiesConstraintRequest, SelectedTargetSignatureFact, SourceCallMarkerDeclaration, SourceSemanticsExportDeclaration, SourceSemanticsExtensionOptions, SourceSemanticsModule, SourceSemanticsModuleIdentity, SourceFileBoundLifecycleRequest, SourcePointerMutability, SourcePrimitiveDeclaration, SourcePrimitiveFact, SourcePrimitiveKind, SourceTypeMarkerDeclaration, TargetBindingFact, TargetBindingProvider, TargetConstraint, TargetIdentity, TargetMember, TargetOperationFact, TargetParameter, TargetSemanticProvider, TargetTypeParameter, TargetTypeRef, ValidateFlowUseRequest, ValidateFlowUseResult, ValueTypeFact } from "./extensions/index.js";
export { ParseBuildCommandLine, ParseCommandLine } from "./internal/tsoptions/commandlineparser.js";
export type { ParsedBuildCommandLine } from "./internal/tsoptions/parsedbuildcommandline.js";
export type { ParsedCommandLine } from "./internal/tsoptions/parsedcommandline.js";
export { FS as OSFileSystem } from "./internal/vfs/osvfs/os.js";
export type { FS as TstsFileSystem } from "./internal/vfs/vfs.js";
export { barebonesLibContent, formatDiagnostics, transpile, transpileDeclaration, transpileModule } from "./services/transpile.js";
export type { TranspileCompilerOptions, TranspileCompilerOptionValue, TranspileOptions, TranspileOutput } from "./services/transpile.js";
export { createTypeCheckerQueries } from "./services/type-checker.js";
export type { TypeCheckerQueries, TypeCheckerQueryOptions } from "./services/type-checker.js";
export {
  Node_Statements,
  Node_Text,
  SourceFile_FileName,
} from "./internal/ast/ast.js";
export { Node_Name } from "./internal/ast/spine.js";
export {
  AsBinaryExpression,
  AsBlock,
  AsCallExpression,
  AsClassDeclaration,
  AsConstructorDeclaration,
  AsConditionalExpression,
  AsDoStatement,
  AsElementAccessExpression,
  AsExpressionStatement,
  AsForInOrOfStatement,
  AsForStatement,
  AsFunctionDeclaration,
  AsIdentifier,
  AsIfStatement,
  AsIndexSignatureDeclaration,
  AsInterfaceDeclaration,
  AsMethodDeclaration,
  AsMethodSignatureDeclaration,
  AsNewExpression,
  AsNoSubstitutionTemplateLiteral,
  AsParameterDeclaration,
  AsParenthesizedExpression,
  AsPropertyAccessExpression,
  AsPropertyDeclaration,
  AsPropertySignatureDeclaration,
  AsPrefixUnaryExpression,
  AsPostfixUnaryExpression,
  AsReturnStatement,
  AsStringLiteral,
  AsTemplateExpression,
  AsTemplateSpan,
  AsNumericLiteral,
  AsArrayLiteralExpression,
  AsArrayTypeNode,
  AsAsExpression,
  AsVariableDeclaration,
  AsVariableDeclarationList,
  AsVariableStatement,
  AsWhileStatement,
  AsBreakStatement,
  AsCaseBlock,
  AsCaseOrDefaultClause,
  AsCatchClause,
  AsContinueStatement,
  AsDebuggerStatement,
  AsEmptyStatement,
  AsLabeledStatement,
  AsSwitchStatement,
  AsThrowStatement,
  AsTryStatement,
  AsTypeParameterDeclaration,
  AsTypeReferenceNode,
  AsExpressionWithTypeArguments,
  AsHeritageClause,
  AsNonNullExpression,
  AsSatisfiesExpression,
  AsTypeAssertion,
} from "./internal/ast/generated/casts.js";
export {
  KindAmpersandAmpersandToken,
  KindAsExpression,
  KindAsteriskToken,
  KindBarBarToken,
  KindBinaryExpression,
  KindBlock,
  KindCallExpression,
  KindArrayBindingPattern,
  KindArrayLiteralExpression,
  KindArrayType,
  KindAnyKeyword,
  KindBigIntKeyword,
  KindBooleanKeyword,
  KindBreakStatement,
  KindCaseBlock,
  KindCaseClause,
  KindClassDeclaration,
  KindConditionalExpression,
  KindConstructor,
  KindContinueStatement,
  KindDebuggerStatement,
  KindDefaultClause,
  KindDoStatement,
  KindElementAccessExpression,
  KindEmptyStatement,
  KindExclamationEqualsEqualsToken,
  KindExclamationEqualsToken,
  KindExclamationToken,
  KindEqualsEqualsEqualsToken,
  KindEqualsEqualsToken,
  KindEqualsToken,
  KindExportAssignment,
  KindExportDeclaration,
  KindExpressionStatement,
  KindFalseKeyword,
  KindForInStatement,
  KindForOfStatement,
  KindForStatement,
  KindFunctionDeclaration,
  KindGreaterThanEqualsToken,
  KindGreaterThanToken,
  KindIdentifier,
  KindIfStatement,
  KindImportDeclaration,
  KindIndexSignature,
  KindInterfaceDeclaration,
  KindLabeledStatement,
  KindLessThanEqualsToken,
  KindLessThanToken,
  KindMethodDeclaration,
  KindMethodSignature,
  KindMinusToken,
  KindMinusMinusToken,
  KindNeverKeyword,
  KindNullKeyword,
  KindNumericLiteral,
  KindNewExpression,
  KindNumberKeyword,
  KindObjectKeyword,
  KindObjectBindingPattern,
  KindPlusToken,
  KindPlusPlusToken,
  KindParenthesizedExpression,
  KindPercentToken,
  KindPropertyAccessExpression,
  KindPropertyDeclaration,
  KindPropertySignature,
  KindPrefixUnaryExpression,
  KindPostfixUnaryExpression,
  KindQuestionQuestionToken,
  KindReturnStatement,
  KindSlashToken,
  KindStringLiteral,
  KindNoSubstitutionTemplateLiteral,
  KindNonNullExpression,
  KindSatisfiesExpression,
  KindTemplateExpression,
  KindSuperKeyword,
  KindSwitchStatement,
  KindThisKeyword,
  KindThrowStatement,
  KindTrueKeyword,
  KindTryStatement,
  KindTypeAliasDeclaration,
  KindTypeLiteral,
  KindTypeAssertionExpression,
  KindVariableStatement,
  KindVariableDeclarationList,
  KindWhileStatement,
  KindString,
  KindStringKeyword,
  KindTypeReference,
  KindUnknownKeyword,
  KindVoidKeyword,
  KindExpressionWithTypeArguments,
  KindExtendsKeyword,
  KindImplementsKeyword,
} from "./internal/ast/generated/kinds.js";
export type { Node, SourceFile } from "./internal/ast/ast.js";
export type { Symbol } from "./internal/ast/symbol.js";
export {
  TypeFlagsAny,
  TypeFlagsBigIntLike,
  TypeFlagsBooleanLike,
  TypeFlagsNever,
  TypeFlagsNumberLike,
  TypeFlagsStringLike,
  TypeFlagsUnknown,
  TypeFlagsVoidLike,
} from "./internal/checker/types.js";
export type { ContextFlags, Signature, Type } from "./internal/checker/types.js";
