export * from "./navigation.js";
export { sourceLexicalCaptures, sourceDeclarationIsModuleScoped, sourceBindingScope } from "./lexical-captures.js";
export { sourceBindingHasSingleCaptureOwner } from "./capture-ownership.js";
export type { SourceLexicalCapture, SourceLexicalCaptureSelection } from "./lexical-captures.js";
export { sourceMayReadBeforeInitialization } from "./initialization-uses.js";
export { createSourceArrayDensityQuery } from "./array-density.js";
export type { SourceArrayDensityOptions, SourceArrayDensityQueries, SourceArrayMemberEffect } from "./array-density.js";
export { analyzeSourceIntegerRanges } from "./integer-ranges/index.js";
export { sourceIntegerInduction } from "./integer-ranges/induction.js";
export type { SourceIntegerRange, SourceIntegerRangeOptions, SourceIntegerRangeQueries } from "./integer-ranges/index.js";
