export * from "./navigation.js";
export { forEachSourceImmediateEvaluationChild } from "./immediate-evaluation.js";
export { generatedTypeParameterNames, authoredTypeParameterNames } from "./generic-bindings.js";
export { sourceLexicalCaptures, sourceDeclarationIsModuleScoped, sourceBindingScope } from "./lexical-captures.js";
export { sourceBindingHasSingleCaptureOwner } from "./capture-ownership.js";
export { sourceBindingCapturedBeforeInitialization } from "./deferred-captures.js";
export { createSourceSingleInvocationQuery, sourceEnclosingCallable, sourceLexicalFunctionIsUnused } from "./callable-invocations.js";
export { sourceBindingHasMutableExposure } from "./binding-mutation-exposure.js";
export type { SourceLexicalCapture, SourceLexicalCaptureSelection } from "./lexical-captures.js";
export { sourceMayReadBeforeInitialization } from "./initialization-uses.js";
export { createSourceCallOnlyAliasQuery } from "./callable-aliases.js";
export type { SourceCallOnlyAlias } from "./callable-aliases.js";
export { createSourceArrayDensityQuery } from "./array-density.js";
export type { SourceArrayDensityOptions, SourceArrayDensityQueries, SourceArrayMemberEffect } from "./array-density.js";
export { analyzeSourceIntegerRanges } from "./integer-ranges/index.js";
export { sourceIntegerInduction } from "./integer-ranges/induction.js";
export { sourceIntegerIsNonnegative } from "./integer-ranges/guards.js";
export type { SourceIntegerRange, SourceIntegerRangeOptions, SourceIntegerRangeQueries } from "./integer-ranges/index.js";
export { sourceSequenceInputChoice, sourceSequenceConsumptionRoot, sourceSequenceInputIsEmpty } from "./sequence-inputs.js";
export type { SourceSequenceInputChoice } from "./sequence-inputs.js";
