/**
 * Generated auxiliary C# file emitters (JSON AOT and module container attribute).
 *
 * Extracted from emitter.ts — contains the logic that generates compiler-internal
 * support files (__tsonic_json.g.cs, __tsonic_module_containers.g.cs) using the
 * backend AST builder and printer.
 */

import type { JsonAotRegistry } from "./types.js";
import type {
  RuntimeUnionCarrierDefinition,
  RuntimeUnionRegistry,
} from "./core/semantic/runtime-union-registry.js";
import { printCompilationUnit } from "./core/format/backend-ast/printer.js";
import { printType } from "./core/format/backend-ast/printer-precedence.js";
import {
  identifierType as buildIdentifierType,
  qualifiedName,
} from "./core/format/backend-ast/builders.js";
import type {
  CSharpAttributeAst,
  CSharpCompilationUnitAst,
  CSharpExpressionAst,
  CSharpMemberAst,
  CSharpTriviaAst,
  CSharpTypeAst,
} from "./core/format/backend-ast/types.js";

const commentLine = (text: string): CSharpTriviaAst => ({
  kind: "singleLineCommentTrivia",
  text,
});

const blankLineTrivia = (): CSharpTriviaAst => ({
  kind: "blankLineTrivia",
});

const identifierType = (
  name: string,
  typeArguments?: readonly CSharpTypeAst[]
): CSharpTypeAst => buildIdentifierType(name, typeArguments);

const typeRef = (type: CSharpTypeAst): CSharpExpressionAst => ({
  kind: "typeReferenceExpression",
  type,
});

const memberAccess = (
  expression: CSharpExpressionAst,
  memberName: string
): CSharpExpressionAst => ({
  kind: "memberAccessExpression",
  expression,
  memberName,
});

const assignment = (
  left: CSharpExpressionAst,
  right: CSharpExpressionAst
): CSharpExpressionAst => ({
  kind: "assignmentExpression",
  operatorToken: "=",
  left,
  right,
});

const generatedFileLeadingTrivia = (
  ...lines: readonly string[]
): readonly CSharpTriviaAst[] => [...lines.map(commentLine), blankLineTrivia()];

export const generateModuleContainerAttributeFile = (): string => {
  const attributeUsageType = identifierType(
    "global::System.AttributeUsageAttribute"
  );
  const attributeTargetsType = identifierType(
    "global::System.AttributeTargets"
  );
  const systemAttributeType = identifierType("global::System.Attribute");

  const markerAttribute: CSharpAttributeAst = {
    type: attributeUsageType,
    arguments: [
      memberAccess(typeRef(attributeTargetsType), "Class"),
      assignment(
        { kind: "identifierExpression", identifier: "Inherited" },
        { kind: "booleanLiteralExpression", value: false }
      ),
      assignment(
        { kind: "identifierExpression", identifier: "AllowMultiple" },
        { kind: "booleanLiteralExpression", value: false }
      ),
    ],
  };

  const unit: CSharpCompilationUnitAst = {
    kind: "compilationUnit",
    leadingTrivia: generatedFileLeadingTrivia(
      "<auto-generated/>",
      "Marker attribute for module container types.",
      "Used by tsbindgen to generate flattened named exports for module-level values.",
      "WARNING: Do not modify this file manually"
    ),
    usings: [],
    members: [
      {
        kind: "namespaceDeclaration",
        name: qualifiedName("Tsonic.Internal"),
        members: [
          {
            kind: "classDeclaration",
            attributes: [markerAttribute],
            modifiers: ["internal", "sealed"],
            name: "ModuleContainerAttribute",
            baseType: systemAttributeType,
            interfaces: [],
            members: [],
          },
        ],
      },
    ],
  };

  return printCompilationUnit(unit);
};

export const generateArrayInteropFile = (): string => `// <auto-generated/>
// Compiler-owned native array wrapper interop support.
// WARNING: Do not modify this file manually

namespace Tsonic.Internal
{
    internal static class ArrayInterop
    {
        internal static global::js.Array<T> WrapArray<T>(global::System.Collections.Generic.IEnumerable<T> values)
        {
            var array = new global::js.Array<T>();
            foreach (var value in values)
            {
                array.push(value);
            }
            return array;
        }
    }
}
`;

const generateRuntimeUnionCarrier = (
  definition: RuntimeUnionCarrierDefinition
): string => {
  const { name, memberTypeAsts, typeParameters, accessModifier } = definition;
  const genericParameters = typeParameters.join(", ");
  const genericSuffix =
    genericParameters.length > 0 ? `<${genericParameters}>` : "";
  const carrierType = `${name}${genericSuffix}`;
  const memberTypes = memberTypeAsts.map(printType);
  const stripTopLevelNullableSuffix = (typeText: string): string =>
    typeText.endsWith("?") ? typeText.slice(0, -1) : typeText;
  const fromFactories = memberTypes
    .map(
      (typeParameter, index) =>
        `        public static ${carrierType} From${index + 1}(${typeParameter} value) => new ${carrierType}(value, ${index});`
    )
    .join("\n");
  const isChecks = memberTypes
    .map(
      (_, index) =>
        `        public bool Is${index + 1}() => _index == ${index};`
    )
    .join("\n");
  const asCasts = memberTypes
    .map(
      (
        typeParameter,
        index
      ) => `        public ${typeParameter} As${index + 1}()
        {
            if (_index != ${index})
                throw new global::System.InvalidOperationException($"Union does not contain type {typeof(${stripTopLevelNullableSuffix(typeParameter)}).Name}");
            return (${typeParameter})_value!;
        }`
    )
    .join("\n\n");
  const tryAs = memberTypes
    .map(
      (
        typeParameter,
        index
      ) => `        public bool TryAs${index + 1}(out ${typeParameter} value)
        {
            if (_index == ${index})
            {
                value = (${typeParameter})_value!;
                return true;
            }
            value = default;
            return false;
        }`
    )
    .join("\n\n");
  const matchResultParameters = memberTypes
    .map(
      (typeParameter, index) =>
        `global::System.Func<${typeParameter}, TResult> onT${index + 1}`
    )
    .join(", ");
  const matchVoidParameters = memberTypes
    .map(
      (typeParameter, index) =>
        `global::System.Action<${typeParameter}> onT${index + 1}`
    )
    .join(", ");
  const matchResultCases = memberTypes
    .map(
      (typeParameter, index) =>
        `                ${index} => onT${index + 1}((${typeParameter})_value!),`
    )
    .join("\n");
  const matchVoidCases = memberTypes
    .map(
      (typeParameter, index) =>
        `                case ${index}: onT${index + 1}((${typeParameter})_value!); break;`
    )
    .join("\n");
  return `    ${accessModifier} sealed class ${carrierType}
    {
        private readonly object? _value;
        private readonly int _index;

        private ${name}(object? value, int index)
        {
            _value = value;
            _index = index;
        }

${fromFactories}

${isChecks}

${asCasts}

${tryAs}

        public TResult Match<TResult>(${matchResultParameters})
        {
            return _index switch
            {
${matchResultCases}
                _ => throw new global::System.InvalidOperationException("Invalid union index"),
            };
        }

        public void Match(${matchVoidParameters})
        {
            switch (_index)
            {
${matchVoidCases}
                default:
                    throw new global::System.InvalidOperationException("Invalid union index");
            }
        }

        public override string? ToString()
        {
            return _value?.ToString();
        }

        public override bool Equals(object? obj)
        {
            return obj is ${carrierType} other &&
                _index == other._index &&
                global::System.Collections.Generic.EqualityComparer<object?>.Default.Equals(_value, other._value);
        }

        public override int GetHashCode()
        {
            return global::System.HashCode.Combine(_value, _index);
        }
    }`;
};

export const generateRuntimeUnionFile = (
  registry: RuntimeUnionRegistry
): string => {
  const definitions = [...registry.definitions.values()].sort(
    (left, right) =>
      left.namespaceName.localeCompare(right.namespaceName) ||
      left.arity - right.arity ||
      left.name.localeCompare(right.name)
  );

  const namespaces = new Map<string, readonly (typeof definitions)[number][]>();
  for (const definition of definitions) {
    namespaces.set(definition.namespaceName, [
      ...(namespaces.get(definition.namespaceName) ?? []),
      definition,
    ]);
  }

  const namespaceBlocks = [...namespaces.entries()]
    .map(([namespaceName, namespaceDefinitions]) => {
      const carriers = namespaceDefinitions
        .map((definition) => generateRuntimeUnionCarrier(definition))
        .join("\n\n");
      return `namespace ${namespaceName}
{
${carriers}
}`;
    })
    .join("\n\n");

  return `// <auto-generated/>
// Compiler-owned runtime union carriers.
// WARNING: Do not modify this file manually

${namespaceBlocks}
`;
};

/**
 * Generate the __tsonic_json.g.cs file for NativeAOT JSON support.
 * This file contains the JsonSerializerContext and options holder.
 */
export const generateJsonAotFile = (
  registry: JsonAotRegistry,
  rootNamespace: string
): string => {
  const types = [...registry.rootTypes.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([, typeAst]) => typeAst);

  const jsonSerializableType = identifierType(
    "global::System.Text.Json.Serialization.JsonSerializableAttribute"
  );
  const jsonSerializerContextType = identifierType(
    "global::System.Text.Json.Serialization.JsonSerializerContext"
  );
  const jsonSerializerOptionsType = identifierType(
    "global::System.Text.Json.JsonSerializerOptions"
  );
  const jsonNamingPolicyType = identifierType(
    "global::System.Text.Json.JsonNamingPolicy"
  );
  const jsonSerializableAttributes: readonly CSharpAttributeAst[] = types.map(
    (typeAst) => ({
      type: jsonSerializableType,
      arguments: [{ kind: "typeofExpression", type: typeAst }],
    })
  );

  const optionsField: CSharpMemberAst = {
    kind: "fieldDeclaration",
    attributes: [],
    modifiers: ["internal", "static", "readonly"],
    type: jsonSerializerOptionsType,
    name: "Options",
    initializer: {
      kind: "objectCreationExpression",
      type: jsonSerializerOptionsType,
      arguments: [],
      initializer: [
        assignment(
          { kind: "identifierExpression", identifier: "TypeInfoResolver" },
          memberAccess(
            typeRef(identifierType("__TsonicJsonContext")),
            "Default"
          )
        ),
        assignment(
          {
            kind: "identifierExpression",
            identifier: "PropertyNameCaseInsensitive",
          },
          { kind: "booleanLiteralExpression", value: true }
        ),
        assignment(
          { kind: "identifierExpression", identifier: "PropertyNamingPolicy" },
          memberAccess(typeRef(jsonNamingPolicyType), "CamelCase")
        ),
        assignment(
          { kind: "identifierExpression", identifier: "DictionaryKeyPolicy" },
          memberAccess(typeRef(jsonNamingPolicyType), "CamelCase")
        ),
      ],
    },
  };

  const unit: CSharpCompilationUnitAst = {
    kind: "compilationUnit",
    leadingTrivia: generatedFileLeadingTrivia(
      "<auto-generated/>",
      "Generated by Tsonic for NativeAOT JSON serialization support",
      "WARNING: Do not modify this file manually"
    ),
    usings: [],
    members: [
      {
        kind: "namespaceDeclaration",
        name: qualifiedName(rootNamespace),
        members: [
          {
            kind: "classDeclaration",
            attributes: jsonSerializableAttributes,
            modifiers: ["internal", "partial"],
            name: "__TsonicJsonContext",
            baseType: jsonSerializerContextType,
            interfaces: [],
            members: [],
          },
          {
            kind: "classDeclaration",
            attributes: [],
            modifiers: ["internal", "static"],
            name: "TsonicJson",
            interfaces: [],
            members: [optionsField],
          },
        ],
      },
    ],
  };

  return printCompilationUnit(unit);
};
