import { writeFileSync } from "node:fs";
import { moduleNamespaceToInternalSpecifier } from "../binding-semantics.js";
import {
  normalizeTypeReferenceName,
  primitiveImportLine,
  printTypeParameters,
  renderPortableType,
  renderUnknownParameters,
  selectSourceTypeImportsForRenderedText,
} from "../portable-types.js";
import {
  renderSourceFunctionSignatures,
  renderSourceFunctionType,
  renderSourceValueType,
} from "../source-type-text.js";
import type {
  AnonymousStructuralAliasInfo,
  FirstPartyBindingsExport,
  FirstPartyBindingsType,
  NamespacePlan,
} from "../types.js";

export const writeNamespaceInternalFile = (opts: {
  readonly internalIndexPath: string;
  readonly namespace: string;
  readonly outputName: string;
  readonly internalBodyLines: readonly string[];
  readonly sourceAliasLines: readonly string[];
  readonly internalTypeImports: NamespacePlan["internalTypeImports"];
  readonly wrapperImports: NamespacePlan["wrapperImports"];
}): void => {
  const internalSourceAliasLines =
    opts.sourceAliasLines.length > 0
      ? [
          "",
          "// Tsonic source type aliases (generated)",
          ...opts.sourceAliasLines,
          "// End Tsonic source type aliases",
        ]
      : [];
  const requiredInternalTypeImports = selectSourceTypeImportsForRenderedText(
    [...internalSourceAliasLines, ...opts.internalBodyLines].join("\n"),
    opts.internalTypeImports
  );

  const internalLines: string[] = [];
  internalLines.push("// Generated by Tsonic - Source bindings");
  internalLines.push(`// Namespace: ${opts.namespace}`);
  internalLines.push(`// Assembly: ${opts.outputName}`);
  internalLines.push("");
  internalLines.push(primitiveImportLine);
  if (requiredInternalTypeImports.length > 0) {
    internalLines.push("");
    internalLines.push("// Tsonic source type imports (generated)");
    for (const typeImport of requiredInternalTypeImports) {
      if (typeImport.importedName === typeImport.localName) {
        internalLines.push(
          `import type { ${typeImport.importedName} } from '${typeImport.source}';`
        );
        continue;
      }
      internalLines.push(
        `import type { ${typeImport.importedName} as ${typeImport.localName} } from '${typeImport.source}';`
      );
    }
    internalLines.push("// End Tsonic source type imports");
  }
  if (opts.wrapperImports.length > 0) {
    internalLines.push("");
    internalLines.push("// Tsonic source member type imports (generated)");
    for (const wrapperImport of opts.wrapperImports) {
      if (wrapperImport.importedName === wrapperImport.aliasName) {
        internalLines.push(
          `import type { ${wrapperImport.importedName} } from '${wrapperImport.source}';`
        );
        continue;
      }
      internalLines.push(
        `import type { ${wrapperImport.importedName} as ${wrapperImport.aliasName} } from '${wrapperImport.source}';`
      );
    }
    internalLines.push("// End Tsonic source member type imports");
  }
  internalLines.push("");
  if (internalSourceAliasLines.length > 0) {
    internalLines.push(...internalSourceAliasLines);
    internalLines.push("");
  }
  internalLines.push(...opts.internalBodyLines);

  writeFileSync(
    opts.internalIndexPath,
    internalLines.join("\n").trimEnd() + "\n",
    "utf-8"
  );
};

export const writeNamespaceFacadeFiles = (opts: {
  readonly facadeDtsPath: string;
  readonly facadeJsPath: string;
  readonly namespace: string;
  readonly plan: NamespacePlan;
  readonly sourceAliasLines: readonly string[];
  readonly sourceAliasInternalImports: readonly string[];
  readonly anonymousStructuralAliases: ReadonlyMap<
    string,
    AnonymousStructuralAliasInfo
  >;
}): ReadonlyMap<string, FirstPartyBindingsExport> => {
  const internalSpecifier = moduleNamespaceToInternalSpecifier(opts.namespace);
  const facadeLines: string[] = [];
  facadeLines.push(`// Namespace: ${opts.namespace}`);
  facadeLines.push("// Generated by Tsonic - Source bindings");
  facadeLines.push("");
  facadeLines.push(`import * as Internal from '${internalSpecifier}';`);
  facadeLines.push("");

  for (const symbol of opts.plan.typeDeclarations) {
    if (symbol.kind === "typeAlias") continue;
    const isValueType = symbol.kind === "class" || symbol.kind === "enum";
    const isSyntheticAnonymousClass =
      symbol.kind === "class" && symbol.localName.startsWith("__Anon_");
    const specifier =
      symbol.exportName === symbol.localName
        ? symbol.exportName
        : `${symbol.localName} as ${symbol.exportName}`;
    if (isValueType) {
      if (!isSyntheticAnonymousClass) {
        facadeLines.push(
          `export { ${specifier} } from '${internalSpecifier}';`
        );
      }
      facadeLines.push(
        `export type { ${specifier} } from '${internalSpecifier}';`
      );
      if (symbol.kind === "class") {
        facadeLines.push(
          `export type { ${symbol.localName}$instance } from '${internalSpecifier}';`
        );
      }
      continue;
    }

    facadeLines.push(
      `export type { ${specifier} } from '${internalSpecifier}';`
    );
    if (symbol.kind === "interface") {
      facadeLines.push(
        `export type { ${symbol.localName}$instance } from '${internalSpecifier}';`
      );
    }
  }

  for (const container of opts.plan.moduleContainers) {
    facadeLines.push(
      `export { ${container.module.className}$instance as ${container.module.className} } from '${internalSpecifier}';`
    );
  }

  const valueBindings = new Map<string, FirstPartyBindingsExport>();
  const localTypeImports = new Set<string>();
  for (const symbol of opts.plan.typeDeclarations) {
    if (symbol.kind === "typeAlias") continue;
    localTypeImports.add(symbol.localName);
    if (symbol.kind === "class" || symbol.kind === "interface") {
      localTypeImports.add(`${symbol.localName}$instance`);
    }
  }
  for (const internalImport of opts.sourceAliasInternalImports) {
    localTypeImports.add(internalImport);
  }
  for (const helper of opts.plan.internalHelperTypeDeclarations) {
    localTypeImports.add(helper.emittedName);
  }

  if (localTypeImports.size > 0) {
    facadeLines.push("");
    facadeLines.push("// Tsonic source alias imports (generated)");
    facadeLines.push(
      `import type { ${Array.from(localTypeImports.values())
        .sort((left, right) => left.localeCompare(right))
        .join(", ")} } from '${internalSpecifier}';`
    );
    facadeLines.push("// End Tsonic source alias imports");
  }

  if (opts.sourceAliasLines.length > 0) {
    facadeLines.push("");
    facadeLines.push("// Tsonic source type aliases (generated)");
    facadeLines.push(...opts.sourceAliasLines);
    facadeLines.push("// End Tsonic source type aliases");
  }

  if (opts.plan.crossNamespaceReexports.dtsStatements.length > 0) {
    facadeLines.push("");
    facadeLines.push("// Tsonic cross-namespace re-exports (generated)");
    facadeLines.push(...opts.plan.crossNamespaceReexports.dtsStatements);
    facadeLines.push("// End Tsonic cross-namespace re-exports");
  }

  for (const valueExport of opts.plan.valueExports) {
    valueBindings.set(valueExport.exportName, valueExport.binding);
    if (
      opts.plan.crossNamespaceReexports.valueExportNames.has(
        valueExport.exportName
      )
    ) {
      continue;
    }
    if (valueExport.facade.kind === "function") {
      const sourceSignatures = renderSourceFunctionSignatures({
        sourceSignatures: valueExport.facade.sourceSignatures ?? [],
        localTypeNameRemaps: valueExport.facade.localTypeNameRemaps,
        anonymousStructuralAliases: opts.anonymousStructuralAliases,
      });
      if (sourceSignatures.length > 0) {
        for (const sourceSignature of sourceSignatures) {
          facadeLines.push(
            `export declare function ${valueExport.exportName}${sourceSignature.typeParametersText}(${sourceSignature.parametersText}): ${sourceSignature.returnTypeText};`
          );
        }
      } else {
        facadeLines.push(
          `export declare function ${valueExport.exportName}${printTypeParameters(
            valueExport.facade.declaration.typeParameters
          )}(${renderUnknownParameters(
            valueExport.facade.declaration.parameters,
            valueExport.facade.declaration.typeParameters?.map(
              (typeParameter) => typeParameter.name
            ) ?? [],
            valueExport.facade.localTypeNameRemaps,
            opts.anonymousStructuralAliases
          )}): ${renderPortableType(
            valueExport.facade.declaration.returnType,
            valueExport.facade.declaration.typeParameters?.map(
              (typeParameter) => typeParameter.name
            ) ?? [],
            valueExport.facade.localTypeNameRemaps,
            opts.anonymousStructuralAliases
          )};`
        );
      }
      continue;
    }

    const sourceFunctionTypeText = renderSourceFunctionType({
      sourceSignatures: valueExport.facade.sourceSignatures ?? [],
      localTypeNameRemaps: valueExport.facade.localTypeNameRemaps,
      anonymousStructuralAliases: opts.anonymousStructuralAliases,
    });
    const sourceTypeText =
      sourceFunctionTypeText ??
      renderSourceValueType(
        valueExport.facade.sourceType,
        valueExport.facade.localTypeNameRemaps,
        opts.anonymousStructuralAliases
      );
    facadeLines.push(
      `export declare const ${valueExport.exportName}: ${
        sourceTypeText ??
        renderPortableType(
          valueExport.facade.declarator?.type,
          [],
          valueExport.facade.localTypeNameRemaps,
          opts.anonymousStructuralAliases
        )
      };`
    );
  }

  const requiredFacadeTypeImports = selectSourceTypeImportsForRenderedText(
    facadeLines.join("\n"),
    opts.plan.facadeTypeImports
  );
  if (requiredFacadeTypeImports.length > 0) {
    facadeLines.splice(
      4,
      0,
      "",
      "// Tsonic source type imports (generated)",
      ...requiredFacadeTypeImports.map((typeImport) =>
        typeImport.importedName === typeImport.localName
          ? `import type { ${typeImport.importedName} } from '${typeImport.source}';`
          : `import type { ${typeImport.importedName} as ${typeImport.localName} } from '${typeImport.source}';`
      ),
      "// End Tsonic source type imports"
    );
  }

  if (
    opts.plan.typeDeclarations.length === 0 &&
    opts.plan.moduleContainers.length === 0 &&
    opts.plan.valueExports.length === 0 &&
    opts.sourceAliasLines.length === 0 &&
    opts.plan.crossNamespaceReexports.dtsStatements.length === 0
  ) {
    facadeLines.push("export {};");
  }

  writeFileSync(
    opts.facadeDtsPath,
    facadeLines.join("\n").trimEnd() + "\n",
    "utf-8"
  );

  writeFileSync(
    opts.facadeJsPath,
    [
      `// Namespace: ${opts.namespace}`,
      "// Generated by Tsonic - Source bindings",
      "// Module Stub - Do Not Execute",
      "",
      ...(opts.plan.crossNamespaceReexports.jsValueStatements.length > 0
        ? [
            "// Tsonic cross-namespace value re-exports (generated)",
            ...opts.plan.crossNamespaceReexports.jsValueStatements,
            "// End Tsonic cross-namespace value re-exports",
            "",
          ]
        : []),
      "throw new Error(",
      `  'Cannot import CLR namespace ${opts.namespace} in JavaScript runtime. ' +`,
      "  'This module provides TypeScript type definitions only. ' +",
      "  'Actual implementation requires .NET runtime via Tsonic compiler.'",
      ");",
      "",
    ].join("\n"),
    "utf-8"
  );

  return valueBindings;
};

export const buildClrAliasLookup = (
  typeBindings: readonly FirstPartyBindingsType[]
): Map<string, string> => {
  const clrNamesByAlias = new Map<string, string>();
  for (const typeBinding of typeBindings) {
    clrNamesByAlias.set(typeBinding.alias, typeBinding.clrName);
    clrNamesByAlias.set(
      normalizeTypeReferenceName(typeBinding.alias, typeBinding.arity),
      typeBinding.clrName
    );
  }
  return clrNamesByAlias;
};
