import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  buildModuleDependencyGraph,
  type CompilerOptions,
  type IrModule,
  type IrStatement,
} from "@tsonic/frontend";
import * as ts from "typescript";
import { resolveSurfaceCapabilities } from "../../surface/profiles.js";
import type { ResolvedConfig, Result } from "../../types.js";
import type { SourceFunctionSignatureSurface as SourceFunctionSignatureDef } from "../../aikya/source-function-surfaces.js";
import {
  collectSourceTypeImportsForSignature,
  ensureInternalTypeImportsForFacade,
  ensureSourceTypeImportsForFacade,
  indexFacadeFiles,
  patchFacadeWithSourceFunctionSignatures,
  patchInternalIndexBrandMarkersOptional,
  patchInternalIndexWithMemberOverrides,
} from "./facade-patches.js";
import {
  getPropertyNameText,
  normalizeModuleFileKey,
  printTypeNodeText,
  renderDiagnostics,
  stripExistingSection,
  typeNodeUsesImportedTypeNames,
  unwrapParens,
  upsertSection,
  upsertSectionAfterImports,
} from "./shared.js";
import {
  classifyExportKind,
  collectExtensionWrapperImportsFromSourceType,
  discoverSourceModuleInfos,
  renderExportedTypeAlias,
  resolveLocalModuleFile,
} from "./source-modules.js";
import type {
  FacadeInfo,
  MemberOverride,
  ModuleSourceIndex,
  SourceTypeImportBinding,
} from "./types.js";

export const augmentLibraryBindingsFromSource = (
  config: ResolvedConfig,
  bindingsOutDir: string
): Result<void, string> => {
  const entryPoint = config.entryPoint;
  if (!entryPoint) {
    return { ok: true, value: undefined };
  }

  const absoluteEntryPoint = resolve(config.projectRoot, entryPoint);
  const absoluteSourceRoot = resolve(config.projectRoot, config.sourceRoot);
  const surfaceCapabilities = resolveSurfaceCapabilities(config.surface, {
    workspaceRoot: config.workspaceRoot,
  });

  const typeLibraries = config.libraries.filter((lib) => !lib.endsWith(".dll"));
  const allTypeRoots = [...config.typeRoots, ...typeLibraries].map((p) =>
    resolve(config.workspaceRoot, p)
  );

  const compilerOptions: CompilerOptions = {
    projectRoot: config.projectRoot,
    sourceRoot: absoluteSourceRoot,
    rootNamespace: config.rootNamespace,
    typeRoots: allTypeRoots,
    surface: config.surface,
    useStandardLib: surfaceCapabilities.useStandardLib,
    verbose: false,
  };

  const sourceModulesResult = discoverSourceModuleInfos({
    absoluteEntryPoint,
    absoluteSourceRoot,
    rootNamespace: config.rootNamespace,
  });
  if (!sourceModulesResult.ok) {
    return sourceModulesResult;
  }

  const sourceModulesByFile = sourceModulesResult.value.modulesByFileKey;
  const entrySourceModule = sourceModulesByFile.get(
    sourceModulesResult.value.entryFileKey
  );
  if (!entrySourceModule) {
    return {
      ok: false,
      error: `Failed to discover entry source module for bindings augmentation: ${absoluteEntryPoint}`,
    };
  }

  const needsFullGraph = sourceModulesResult.value.requiresFullGraph;
  const graphResult = needsFullGraph
    ? buildModuleDependencyGraph(absoluteEntryPoint, compilerOptions)
    : undefined;
  if (graphResult && !graphResult.ok) {
    return {
      ok: false,
      error: `Failed to analyze library sources:\n${renderDiagnostics(graphResult.error)}`,
    };
  }

  const irModules = graphResult?.ok ? graphResult.value.modules : [];
  const entryModule = graphResult?.ok ? graphResult.value.entryModule : undefined;
  const facadesByNamespace = new Map(indexFacadeFiles(bindingsOutDir));
  const modulesByFile = new Map<string, IrModule>();
  for (const m of irModules) {
    const key = normalizeModuleFileKey(m.filePath);
    modulesByFile.set(key, m);
  }

  const ensureFacade = (namespace: string): FacadeInfo => {
    const existing = facadesByNamespace.get(namespace);
    if (existing) return existing;

    const baseName = namespace;
    const facadeDtsPath = join(bindingsOutDir, `${baseName}.d.ts`);
    const facadeJsPath = join(bindingsOutDir, `${baseName}.js`);
    const moduleSpecifier = `./${baseName}.js`;
    const internalIndexDtsPath = join(bindingsOutDir, "internal", "index.d.ts");

    const internalImport = existsSync(internalIndexDtsPath)
      ? `import * as Internal from './internal/index.js';\n\n`
      : "";

    if (!existsSync(facadeDtsPath)) {
      let content = `// Namespace: ${namespace}\n// Generated by Tsonic (source bindings augmentation)\n\n`;
      if (internalImport) content += internalImport;
      content += "export {};\n";
      writeFileSync(facadeDtsPath, content, "utf-8");
    }

    if (!existsSync(facadeJsPath)) {
      writeFileSync(
        facadeJsPath,
        [
          `// Namespace: ${namespace}`,
          `// Generated by Tsonic (source bindings augmentation)`,
          ``,
          `export {};`,
          ``,
        ].join("\n"),
        "utf-8"
      );
    }

    const created: FacadeInfo = {
      namespace,
      facadeDtsPath,
      facadeJsPath,
      moduleSpecifier,
      internalIndexDtsPath,
    };
    facadesByNamespace.set(namespace, created);
    return created;
  };

  const exportedAliasesByNamespace = new Map<
    string,
    {
      readonly lines: string[];
      readonly internalAliasImports: Set<string>;
    }
  >();
  const sourceIndexByFileKeyForAliases = new Map<string, ModuleSourceIndex>();
  if (needsFullGraph) {
    for (const m of irModules) {
      const isExportedTypeAlias = (
        stmt: IrStatement
      ): stmt is Extract<IrStatement, { kind: "typeAliasDeclaration" }> =>
        stmt.kind === "typeAliasDeclaration" && stmt.isExported;

      const exportedAliases = m.body.filter(isExportedTypeAlias);
      if (exportedAliases.length === 0) continue;

      const info = ensureFacade(m.namespace);

      const internalIndexDts = existsSync(info.internalIndexDtsPath)
        ? readFileSync(info.internalIndexDtsPath, "utf-8")
        : "";
      const moduleKey = normalizeModuleFileKey(m.filePath);
      const sourceModule = sourceModulesByFile.get(moduleKey);
      if (!sourceModule) {
        return {
          ok: false,
          error: `Failed to locate source module metadata for ${moduleKey} during bindings augmentation.`,
        };
      }
      const sourceIndex = (() => {
        const cached = sourceIndexByFileKeyForAliases.get(moduleKey);
        if (cached) return { ok: true as const, value: cached };
        sourceIndexByFileKeyForAliases.set(moduleKey, sourceModule.sourceIndex);
        return { ok: true as const, value: sourceModule.sourceIndex };
      })();

      for (const stmt of exportedAliases) {
        const rendered = renderExportedTypeAlias(
          stmt,
          internalIndexDts,
          sourceIndex.value.typeAliasesByName.get(stmt.name)
        );
        if (!rendered.ok) return rendered;

        const current = exportedAliasesByNamespace.get(m.namespace) ?? {
          lines: [],
          internalAliasImports: new Set<string>(),
        };
        current.lines.push(rendered.value.line);
        if (rendered.value.internalAliasImport) {
          current.internalAliasImports.add(rendered.value.internalAliasImport);
        }
        exportedAliasesByNamespace.set(m.namespace, current);
      }
    }
  }

  const aliasStart = "// Tsonic source type aliases (generated)";
  const aliasEnd = "// End Tsonic source type aliases";
  const aliasImportsStart = "// Tsonic source alias imports (generated)";
  const aliasImportsEnd = "// End Tsonic source alias imports";
  for (const [ns, aliasData] of exportedAliasesByNamespace) {
    const info = facadesByNamespace.get(ns);
    if (!info) continue;
    if (aliasData.lines.length === 0) continue;

    const unique = Array.from(new Set(aliasData.lines)).sort((a, b) =>
      a.localeCompare(b)
    );
    const body = unique.join("\n");

    const current = readFileSync(info.facadeDtsPath, "utf-8");
    const internalImportMatch = current.match(
      /^import\s+\*\s+as\s+Internal\s+from\s+['"](.+)['"];\s*$/m
    );
    let next = current;
    if (internalImportMatch?.[1] && aliasData.internalAliasImports.size > 0) {
      const internalAliasImportLine = `import type { ${Array.from(
        aliasData.internalAliasImports
      )
        .sort((a, b) => a.localeCompare(b))
        .join(", ")} } from '${internalImportMatch[1]}';`;
      next = upsertSectionAfterImports(
        next,
        aliasImportsStart,
        aliasImportsEnd,
        internalAliasImportLine
      );
    } else {
      next = stripExistingSection(next, aliasImportsStart, aliasImportsEnd);
    }
    next = upsertSectionAfterImports(next, aliasStart, aliasEnd, body);
    writeFileSync(info.facadeDtsPath, next, "utf-8");
  }

  const entryFacade = ensureFacade(entrySourceModule.namespace);

  if (needsFullGraph && entryModule) {
    const reexports = entryModule.exports.filter((e) => e.kind === "reexport");
    if (reexports.length > 0) {
      type GroupKey = `${string}|${"type" | "value"}`;
      const grouped = new Map<GroupKey, string[]>();

      for (const exp of reexports) {
        const targetModule = resolveLocalModuleFile(
          exp.fromModule,
          entryModule.filePath,
          modulesByFile
        );
        if (!targetModule) {
          return {
            ok: false,
            error:
              `Failed to resolve re-export '${exp.name}' from '${exp.fromModule}' in ${entryModule.filePath}.\n` +
              `Ensure the target module is within sourceRoot and is part of the build graph.`,
          };
        }

        if (targetModule.namespace === entryModule.namespace) {
          continue;
        }

        const targetFacade = ensureFacade(targetModule.namespace);

        const kind = classifyExportKind(targetModule, exp.originalName);
        if (kind === "unknown") {
          return {
            ok: false,
            error:
              `Failed to classify re-export '${exp.name}' from '${exp.fromModule}'.\n` +
              `Could not find an exported declaration named '${exp.originalName}' in ${targetModule.filePath}.`,
          };
        }
        const spec =
          exp.name === exp.originalName
            ? exp.name
            : `${exp.originalName} as ${exp.name}`;
        const isTypeOnly = kind === "type";
        const key: GroupKey = `${targetFacade.moduleSpecifier}|${
          isTypeOnly ? "type" : "value"
        }`;
        const list = grouped.get(key) ?? [];
        list.push(spec);
        grouped.set(key, list);
      }

      const start = "// Tsonic entrypoint re-exports (generated)";
      const end = "// End Tsonic entrypoint re-exports";

      const statements: string[] = [];
      for (const [key, specs] of Array.from(grouped.entries()).sort((a, b) =>
        a[0].localeCompare(b[0])
      )) {
        const [moduleSpecifier, kind] = key.split("|") as [
          string,
          "type" | "value",
        ];
        const unique = Array.from(new Set(specs)).sort((a, b) =>
          a.localeCompare(b)
        );
        if (kind === "type") {
          statements.push(
            `export type { ${unique.join(", ")} } from '${moduleSpecifier}';`
          );
        } else {
          statements.push(
            `export { ${unique.join(", ")} } from '${moduleSpecifier}';`
          );
        }
      }

      if (statements.length > 0) {
        const current = readFileSync(entryFacade.facadeDtsPath, "utf-8");
        const next = upsertSection(current, start, end, statements.join("\n"));
        writeFileSync(entryFacade.facadeDtsPath, next, "utf-8");
      }

      const valueStatements = statements.filter(
        (s) => !s.startsWith("export type ")
      );
      if (valueStatements.length > 0) {
        const jsStart = "// Tsonic entrypoint value re-exports (generated)";
        const jsEnd = "// End Tsonic entrypoint value re-exports";
        const current = existsSync(entryFacade.facadeJsPath)
          ? readFileSync(entryFacade.facadeJsPath, "utf-8")
          : "";
        const next = upsertSection(
          current,
          jsStart,
          jsEnd,
          valueStatements.join("\n")
        );
        writeFileSync(entryFacade.facadeJsPath, next, "utf-8");
      }
    }
  }

  const sourceIndexByFileKey = new Map<string, ModuleSourceIndex>();
  for (const sourceModule of sourceModulesByFile.values()) {
    sourceIndexByFileKey.set(sourceModule.fileKey, sourceModule.sourceIndex);
  }

  const overridesByInternalIndex = new Map<string, MemberOverride[]>();
  const brandOptionalTypesByInternalIndex = new Map<string, Set<string>>();
  const functionSignaturesByFacade = new Map<
    string,
    Map<string, SourceFunctionSignatureDef[]>
  >();
  const sourceTypeImportsByFacade = new Map<
    string,
    Map<string, SourceTypeImportBinding>
  >();

  for (const sourceModule of sourceModulesByFile.values()) {
    const sourceIndex = sourceModule.sourceIndex;
    const hasExportedSourceFunctions =
      sourceIndex.exportedFunctionSignaturesByName.size > 0;
    if (
      sourceModule.exportedClassNames.length === 0 &&
      sourceModule.exportedInterfaceNames.length === 0 &&
      sourceModule.exportedTypeAliasNames.length === 0 &&
      sourceModule.allInterfaceNames.length === 0 &&
      sourceModule.allTypeAliasNames.length === 0 &&
      !hasExportedSourceFunctions
    ) {
      continue;
    }

    const info =
      facadesByNamespace.get(sourceModule.namespace) ??
      ensureFacade(sourceModule.namespace);

    const brandTargets =
      brandOptionalTypesByInternalIndex.get(info.internalIndexDtsPath) ??
      new Set<string>();
    for (const ifaceName of sourceModule.allInterfaceNames) {
      brandTargets.add(ifaceName);
    }
    for (const aliasName of sourceModule.allTypeAliasNames) {
      const sourceAlias = sourceIndex.typeAliasesByName.get(aliasName);
      if (!sourceAlias) continue;
      const aliasType = unwrapParens(sourceAlias.type);
      if (!ts.isTypeLiteralNode(aliasType)) continue;
      const arity = sourceAlias.typeParameters.length;
      const internalAliasName = `${aliasName}__Alias${arity > 0 ? `_${arity}` : ""}`;
      brandTargets.add(aliasName);
      brandTargets.add(internalAliasName);
    }
    if (brandTargets.size > 0) {
      brandOptionalTypesByInternalIndex.set(info.internalIndexDtsPath, brandTargets);
    }

    for (const [name, signatures] of sourceIndex.exportedFunctionSignaturesByName) {
      if (signatures.length === 0) continue;
      const byName =
        functionSignaturesByFacade.get(info.facadeDtsPath) ??
        new Map<string, SourceFunctionSignatureDef[]>();
      const list = byName.get(name) ?? [];
      list.push(...signatures);
      byName.set(name, list);
      functionSignaturesByFacade.set(info.facadeDtsPath, byName);

      const importsByLocal =
        sourceTypeImportsByFacade.get(info.facadeDtsPath) ??
        new Map<string, SourceTypeImportBinding>();
      for (const signature of signatures) {
        for (const binding of collectSourceTypeImportsForSignature(
          signature,
          sourceIndex.typeImportsByLocalName
        )) {
          const existing = importsByLocal.get(binding.localName);
          if (existing) {
            if (
              existing.source !== binding.source ||
              existing.importedName !== binding.importedName
            ) {
              return {
                ok: false,
                error:
                  `Conflicting source type import alias '${binding.localName}' while augmenting ${info.facadeDtsPath}.\n` +
                  `- ${existing.importedName} from '${existing.source}'\n` +
                  `- ${binding.importedName} from '${binding.source}'\n` +
                  `Fix: disambiguate source type imports for exported function signatures.`,
              };
            }
            continue;
          }
          importsByLocal.set(binding.localName, binding);
        }
      }
      sourceTypeImportsByFacade.set(info.facadeDtsPath, importsByLocal);
    }

    for (const className of sourceModule.exportedClassNames) {
      const memberTypes = sourceIndex.memberTypesByClassAndMember.get(className);
      if (!memberTypes) continue;

      for (const [memberName, sourceMember] of memberTypes) {
        const wrappersResult = collectExtensionWrapperImportsFromSourceType({
          startModuleKey: sourceModule.fileKey,
          typeNode: sourceMember.typeNode,
          sourceIndexByFileKey,
          sourceModulesByFileKey: sourceModulesByFile,
        });
        if (!wrappersResult.ok) return wrappersResult;
        const wrappers = wrappersResult.value;
        const canUseSourceTypeText = !typeNodeUsesImportedTypeNames(
          sourceMember.typeNode,
          sourceIndex.typeImportsByLocalName
        );

        if (
          !canUseSourceTypeText &&
          wrappers.length === 0 &&
          !sourceMember.isOptional
        ) {
          continue;
        }

        const list =
          overridesByInternalIndex.get(info.internalIndexDtsPath) ?? [];
        list.push({
          namespace: sourceModule.namespace,
          className,
          memberName,
          sourceTypeText: canUseSourceTypeText
            ? sourceMember.typeText
            : undefined,
          replaceWithSourceType: canUseSourceTypeText,
          isOptional: sourceMember.isOptional,
          wrappers,
        });
        overridesByInternalIndex.set(info.internalIndexDtsPath, list);
      }
    }

    for (const interfaceName of sourceModule.exportedInterfaceNames) {
      const memberTypes = sourceIndex.memberTypesByClassAndMember.get(interfaceName);
      if (!memberTypes) continue;

      for (const [memberName, sourceMember] of memberTypes) {
        const wrappersResult = collectExtensionWrapperImportsFromSourceType({
          startModuleKey: sourceModule.fileKey,
          typeNode: sourceMember.typeNode,
          sourceIndexByFileKey,
          sourceModulesByFileKey: sourceModulesByFile,
        });
        if (!wrappersResult.ok) return wrappersResult;
        const wrappers = wrappersResult.value;

        const canUseSourceTypeText = !typeNodeUsesImportedTypeNames(
          sourceMember.typeNode,
          sourceIndex.typeImportsByLocalName
        );

        if (!canUseSourceTypeText && wrappers.length === 0) continue;

        const list =
          overridesByInternalIndex.get(info.internalIndexDtsPath) ?? [];
        list.push({
          namespace: sourceModule.namespace,
          className: interfaceName,
          memberName,
          sourceTypeText: canUseSourceTypeText
            ? sourceMember.typeText
            : undefined,
          replaceWithSourceType: canUseSourceTypeText,
          isOptional: sourceMember.isOptional,
          emitOptionalPropertySyntax: true,
          wrappers,
        });
        overridesByInternalIndex.set(info.internalIndexDtsPath, list);
      }
    }

    for (const aliasName of sourceModule.exportedTypeAliasNames) {
      const sourceAlias = sourceIndex.typeAliasesByName.get(aliasName);
      if (!sourceAlias) continue;
      const aliasType = unwrapParens(sourceAlias.type);
      if (!ts.isTypeLiteralNode(aliasType)) continue;
      const arity = sourceAlias.typeParameters.length;
      const internalAliasName = `${aliasName}__Alias${arity > 0 ? `_${arity}` : ""}`;

      for (const member of aliasType.members) {
        if (!ts.isPropertySignature(member)) continue;
        if (!member.name || !member.type) continue;
        const memberName = getPropertyNameText(member.name);
        if (!memberName) continue;

        const wrappersResult = collectExtensionWrapperImportsFromSourceType({
          startModuleKey: sourceModule.fileKey,
          typeNode: member.type,
          sourceIndexByFileKey,
          sourceModulesByFileKey: sourceModulesByFile,
        });
        if (!wrappersResult.ok) return wrappersResult;
        const wrappers = wrappersResult.value;

        const canUseSourceTypeText = !typeNodeUsesImportedTypeNames(
          member.type,
          sourceIndex.typeImportsByLocalName
        );
        if (!canUseSourceTypeText && wrappers.length === 0) continue;

        const list =
          overridesByInternalIndex.get(info.internalIndexDtsPath) ?? [];
        list.push({
          namespace: sourceModule.namespace,
          className: internalAliasName,
          memberName,
          sourceTypeText: canUseSourceTypeText
            ? printTypeNodeText(member.type, member.getSourceFile())
            : undefined,
          replaceWithSourceType: canUseSourceTypeText,
          isOptional: member.questionToken !== undefined,
          wrappers,
        });
        overridesByInternalIndex.set(info.internalIndexDtsPath, list);
      }
    }
  }

  for (const [internalIndex, overrides] of overridesByInternalIndex) {
    const result = patchInternalIndexWithMemberOverrides(internalIndex, overrides);
    if (!result.ok) return result;
  }

  for (const [internalIndex, typeNames] of brandOptionalTypesByInternalIndex) {
    const result = patchInternalIndexBrandMarkersOptional(
      internalIndex,
      Array.from(typeNames.values())
    );
    if (!result.ok) return result;
  }

  for (const [facadePath, signaturesByName] of functionSignaturesByFacade) {
    const result = patchFacadeWithSourceFunctionSignatures(
      facadePath,
      signaturesByName
    );
    if (!result.ok) return result;
  }

  for (const [facadePath, importsByLocalName] of sourceTypeImportsByFacade) {
    const result = ensureSourceTypeImportsForFacade(
      facadePath,
      importsByLocalName
    );
    if (!result.ok) return result;
  }

  for (const info of facadesByNamespace.values()) {
    const result = ensureInternalTypeImportsForFacade(info.facadeDtsPath);
    if (!result.ok) return result;
  }

  return { ok: true, value: undefined };
};
