/**
 * Binding manifest types - maps JS/TS names to external target types/members
 * See spec/bindings.md for full manifest format
 */

import type {
  IrOverloadFamilyMember,
  IrParameter,
  IrType,
} from "../ir/index.js";

/**
 * Parameter modifier for ref/out/in parameters
 * Matches the format from tsbindgen: { index: number, modifier: "ref" | "out" | "in" }
 */
export type ParameterModifier = {
  readonly index: number;
  readonly modifier: "ref" | "out" | "in";
};

export type EmitCallStyle = "receiver" | "static";
export type EmitCallableStaticAccessorKind = "property" | "field";

export type EmitSemantics = {
  readonly callStyle?: EmitCallStyle;
  readonly callableStaticAccessorKind?: EmitCallableStaticAccessorKind;
};

export type TypeSemantics = {
  readonly contributesTypeIdentity: boolean;
};

export type BindingSemanticSignature = {
  readonly typeParameters?: readonly string[];
  readonly parameters: readonly IrParameter[];
  readonly returnType?: IrType;
};

export type BindingOverloadFamily = IrOverloadFamilyMember;

/**
 * Member binding (method/property level)
 */
export type MemberBinding = {
  readonly kind: "method" | "property";
  readonly stableId?: string;
  readonly signature?: string; // Optional TS signature for diagnostics
  readonly semanticType?: IrType;
  readonly semanticOptional?: boolean;
  readonly semanticSignature?: BindingSemanticSignature;
  readonly receiverExpectedType?: IrType;
  readonly overloadFamily?: BindingOverloadFamily;
  /** Total target parameter count (includes extension receiver for extension methods). */
  readonly parameterCount?: number;
  readonly name: string; // Target member name (e.g., "SelectMany")
  readonly alias: string; // TS identifier (e.g., "selectMany")
  readonly binding: {
    readonly assembly: string;
    readonly type: string; // Full target type name (e.g., "Provider.Linq.Enumerable")
    readonly member: string; // Target member name
  };
  // Parameter modifiers for ref/out/in parameters (from tsbindgen)
  readonly parameterModifiers?: readonly ParameterModifier[];
  // Whether this member is an extension method (tsbindgen metadata).
  // Used by the emitter to lower instance-style calls to explicit static calls.
  readonly isExtensionMethod?: boolean;
  readonly emitSemantics?: EmitSemantics;
  readonly sourceOrigin?: {
    readonly filePath: string;
    readonly exportName: string;
    readonly memberName?: string;
  };
};

/**
 * Type binding (class/interface/struct/enum level)
 */
export type TypeBinding = {
  readonly stableId?: string;
  readonly stableIds?: readonly string[];
  readonly name: string; // Target type name (e.g., "Enumerable")
  readonly alias: string; // TS identifier (e.g., "enumerable")
  readonly kind: "class" | "interface" | "struct" | "enum" | "delegate";
  readonly members: readonly MemberBinding[];
};

/**
 * Namespace binding
 */
export type NamespaceBinding = {
  readonly name: string; // external namespace (e.g., "Provider.Linq")
  readonly alias: string; // TS identifier (e.g., "systemLinq")
  readonly types: readonly TypeBinding[];
};

/**
 * Full binding manifest structure (new format from bindings.md)
 */
export type FullBindingManifest = {
  readonly assembly: string;
  readonly namespaces: readonly NamespaceBinding[];
};

/**
 * Simple binding entry for global/module identifiers
 * Maps identifiers like `console`, `Math`, `fs` to external target types
 */
export type SimpleBindingDescriptor = {
  readonly kind: "global" | "module";
  readonly assembly: string;
  readonly type: string;
  readonly sourceImport?: string; // Optional: resolve the binding through a source-package import instead of a target module type
  readonly staticType?: string; // Optional: separate target type for static member access
  readonly providerMemberName?: string; // Optional target member name for generated calls/references
  readonly typeSemantics?: TypeSemantics;
};

/**
 * Simple binding file structure for global/module bindings
 */
export type SimpleBindingFile = {
  readonly bindings: Readonly<Record<string, SimpleBindingDescriptor>>;
};

/**
 * External target binding format - generated by binding providers.
 */
export type TsbindgenMethod = {
  readonly stableId?: string;
  readonly targetName: string;
  /** Normalized signature string (tsbindgen metadata, used for extension receiver inference) */
  readonly normalizedSignature?: string;
  readonly semanticSignature?: BindingSemanticSignature;
  readonly overloadFamily?: BindingOverloadFamily;
  /** Total parameter count in target signature (includes extension receiver) */
  readonly parameterCount?: number;
  readonly ownerQualifiedName?: string;
  readonly ownerIdentity?: string;
  // Parameter modifiers for ref/out/in parameters
  readonly parameterModifiers?: readonly ParameterModifier[];
  readonly isExtensionMethod?: boolean;
  readonly emitSemantics?: EmitSemantics;
};

export type TsbindgenProperty = {
  readonly stableId?: string;
  readonly targetName: string;
  readonly normalizedSignature?: string;
  readonly semanticType?: IrType;
  readonly semanticOptional?: boolean;
  readonly ownerQualifiedName?: string;
  readonly ownerIdentity?: string;
  readonly emitSemantics?: EmitSemantics;
};

export type TsbindgenField = {
  readonly stableId?: string;
  readonly targetName: string;
  readonly normalizedSignature?: string;
  readonly semanticType?: IrType;
  readonly semanticOptional?: boolean;
  readonly ownerQualifiedName?: string;
  readonly ownerIdentity?: string;
  readonly emitSemantics?: EmitSemantics;
};

export type TsbindgenTypeRef = {
  readonly stableId?: string;
  readonly targetName: string;
  readonly typeArguments?: readonly string[];
};

export type TsbindgenType = {
  readonly stableId?: string;
  readonly targetName: string; // Full target type name (e.g., "Provider.Console")
  readonly alias?: string; // Optional explicit TS lookup alias (used by first-party bindings)
  readonly ownerIdentity: string;
  readonly baseType?: TsbindgenTypeRef;
  readonly interfaces?: readonly TsbindgenTypeRef[];
  /**
   * Target type kind from the binding provider (e.g., "Class", "Interface", "Struct", "Enum", "Delegate").
   *
   * This is used for airplane-grade emission decisions (e.g., whether a name in
   * a TS `implements` clause is a target interface and should be emitted in the target
   * heritage list).
   */
  readonly kind?: "Class" | "Interface" | "Struct" | "Enum" | "Delegate";
  readonly methods: readonly TsbindgenMethod[];
  readonly properties: readonly TsbindgenProperty[];
  readonly fields: readonly TsbindgenField[];
};

/**
 * tsbindgen "flattened named export" descriptor.
 *
 * This is an additive surface to support JS-style named imports that bind to
 * a stable declaring target type + member (typically module container static types).
 *
 * Example (user code):
 *   import { buildSite } from "@tsumo/engine/Tsumo.Engine.js";
 *   buildSite(req);
 *
 * Example (bindings.json excerpt):
 *   "exports": {
 *     "buildSite": {
 *       "kind": "method",
 *       "targetName": "buildSite",
 *       "ownerQualifiedName": "Tsumo.Engine.BuildSite",
 *       "ownerIdentity": "Tsumo.Engine"
 *     }
 *   }
 */
export type TsbindgenExport = {
  readonly kind: "method" | "property" | "field" | "functionType";
  readonly stableId?: string;
  readonly targetName: string;
  readonly ownerQualifiedName: string;
  readonly ownerIdentity: string;
  readonly semanticType?: IrType;
  readonly semanticOptional?: boolean;
  readonly semanticSignature?: BindingSemanticSignature;
};

export type TsbindgenBindingFile = {
  readonly namespace: string;
  readonly types: readonly TsbindgenType[];
  readonly exports?: Readonly<Record<string, TsbindgenExport>>;
};

export type FirstPartySemanticSurfaceFile = {
  readonly types: readonly unknown[];
  readonly exports?: Readonly<Record<string, unknown>>;
};

export type FirstPartyBindingsFileV2 = {
  readonly namespace: string;
  readonly contributingAssemblies?: readonly string[];
  readonly producer: {
    readonly tool: "tsonic";
    readonly mode: "tsonic-firstparty";
  };
  readonly semanticSurface: FirstPartySemanticSurfaceFile;
  readonly targetSurface: {
    readonly types: readonly TsbindgenType[];
    readonly exports?: Readonly<Record<string, TsbindgenExport>>;
  };
};

const isValidEmitCallStyle = (value: unknown): value is EmitCallStyle =>
  value === "receiver" || value === "static";

const isValidEmitCallableStaticAccessorKind = (
  value: unknown
): value is EmitCallableStaticAccessorKind =>
  value === "property" || value === "field";

const validateEmitSemantics = (
  value: unknown,
  filePath: string,
  label: string
): string | undefined => {
  if (value === undefined) return undefined;
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return `${filePath}: '${label}' must be an object`;
  }

  const record = value as Record<string, unknown>;
  if (
    "callStyle" in record &&
    record.callStyle !== undefined &&
    !isValidEmitCallStyle(record.callStyle)
  ) {
    return `${filePath}: '${label}.callStyle' must be 'receiver' or 'static'`;
  }
  if (
    "callableStaticAccessorKind" in record &&
    record.callableStaticAccessorKind !== undefined &&
    !isValidEmitCallableStaticAccessorKind(record.callableStaticAccessorKind)
  ) {
    return `${filePath}: '${label}.callableStaticAccessorKind' must be 'property' or 'field'`;
  }
  if (
    record.callStyle === undefined &&
    record.callableStaticAccessorKind === undefined
  ) {
    return `${filePath}: '${label}' must define at least one known emit semantics property`;
  }

  return undefined;
};

const validateTypeSemantics = (
  value: unknown,
  filePath: string,
  label: string
): string | undefined => {
  if (value === undefined) return undefined;
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return `${filePath}: '${label}' must be an object`;
  }

  const record = value as Record<string, unknown>;
  if (typeof record.contributesTypeIdentity !== "boolean") {
    return `${filePath}: '${label}.contributesTypeIdentity' must be a boolean`;
  }

  return undefined;
};

const validateBindingSemanticSignature = (
  value: unknown,
  filePath: string,
  label: string
): string | undefined => {
  if (value === undefined) return undefined;
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return `${filePath}: '${label}' must be an object`;
  }

  const record = value as Record<string, unknown>;
  if (
    "typeParameters" in record &&
    record.typeParameters !== undefined &&
    !(
      Array.isArray(record.typeParameters) &&
      record.typeParameters.every((entry) => typeof entry === "string")
    )
  ) {
    return `${filePath}: '${label}.typeParameters' must be a string array when present`;
  }
  if (!Array.isArray(record.parameters)) {
    return `${filePath}: '${label}.parameters' must be an array`;
  }

  return undefined;
};

const validateTsbindgenExport = (
  value: unknown,
  filePath: string,
  label: string
): string | undefined => {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return `${filePath}: '${label}' must be an object`;
  }

  const record = value as Record<string, unknown>;
  const kind = record.kind;
  if (
    kind !== "method" &&
    kind !== "property" &&
    kind !== "field" &&
    kind !== "functionType"
  ) {
    return `${filePath}: '${label}.kind' must be 'method', 'property', 'field', or 'functionType'`;
  }
  if (typeof record.targetName !== "string") {
    return `${filePath}: '${label}.targetName' must be a string`;
  }
  if (typeof record.ownerQualifiedName !== "string") {
    return `${filePath}: '${label}.ownerQualifiedName' must be a string`;
  }
  if (typeof record.ownerIdentity !== "string") {
    return `${filePath}: '${label}.ownerIdentity' must be a string`;
  }

  const semanticSignatureError = validateBindingSemanticSignature(
    record.semanticSignature,
    filePath,
    `${label}.semanticSignature`
  );
  if (semanticSignatureError) return semanticSignatureError;

  if (
    "semanticOptional" in record &&
    record.semanticOptional !== undefined &&
    typeof record.semanticOptional !== "boolean"
  ) {
    return `${filePath}: '${label}.semanticOptional' must be a boolean when present`;
  }

  return undefined;
};

/**
 * Union type for all binding formats
 */
export type BindingFile =
  | FullBindingManifest
  | SimpleBindingFile
  | TsbindgenBindingFile
  | FirstPartyBindingsFileV2;

/**
 * Type guard to check if a manifest is the full format
 */
export const isFullBindingManifest = (
  manifest: BindingFile
): manifest is FullBindingManifest => {
  return "assembly" in manifest && "namespaces" in manifest;
};

/**
 * Type guard to check if a manifest is the tsbindgen format
 */
export const isTsbindgenBindingFile = (
  manifest: BindingFile
): manifest is TsbindgenBindingFile => {
  return (
    "namespace" in manifest &&
    "types" in manifest &&
    !("namespaces" in manifest) &&
    !("targetSurface" in manifest)
  );
};

/**
 * Validate that a parsed JSON object is a valid binding file format.
 * Returns an error message if invalid, undefined if valid.
 */
export const validateBindingFile = (
  obj: unknown,
  filePath: string
): string | undefined => {
  if (obj === null || typeof obj !== "object") {
    return `${filePath}: Expected object, got ${typeof obj}`;
  }

  const manifest = obj as Record<string, unknown>;

  if ("namespace" in manifest && "targetSurface" in manifest) {
    if (typeof manifest.namespace !== "string") {
      return `${filePath}: 'namespace' must be a string`;
    }
    if (
      manifest.targetSurface === null ||
      typeof manifest.targetSurface !== "object" ||
      Array.isArray(manifest.targetSurface)
    ) {
      return `${filePath}: 'targetSurface' must be an object`;
    }
    const targetSurfaceRecord = manifest.targetSurface as Record<
      string,
      unknown
    >;
    if (!Array.isArray(targetSurfaceRecord.types)) {
      return `${filePath}: 'targetSurface.types' must be an array`;
    }
    if (
      "exports" in targetSurfaceRecord &&
      targetSurfaceRecord.exports !== undefined &&
      (targetSurfaceRecord.exports === null ||
        typeof targetSurfaceRecord.exports !== "object" ||
        Array.isArray(targetSurfaceRecord.exports))
    ) {
      return `${filePath}: 'targetSurface.exports' must be an object when present`;
    }
    if (
      !("semanticSurface" in manifest) ||
      manifest.semanticSurface === null ||
      typeof manifest.semanticSurface !== "object" ||
      Array.isArray(manifest.semanticSurface)
    ) {
      return `${filePath}: 'semanticSurface' must be an object`;
    }
    const semanticSurface = manifest.semanticSurface as Record<string, unknown>;
    if (!Array.isArray(semanticSurface.types)) {
      return `${filePath}: 'semanticSurface.types' must be an array`;
    }
    if (
      "exports" in semanticSurface &&
      semanticSurface.exports !== undefined &&
      (semanticSurface.exports === null ||
        typeof semanticSurface.exports !== "object" ||
        Array.isArray(semanticSurface.exports))
    ) {
      return `${filePath}: 'semanticSurface.exports' must be an object when present`;
    }
    const producer = manifest.producer;
    if (
      producer === null ||
      typeof producer !== "object" ||
      Array.isArray(producer)
    ) {
      return `${filePath}: 'producer' must be an object`;
    }
    const producerRecord = producer as Record<string, unknown>;
    if (producerRecord.tool !== "tsonic") {
      return `${filePath}: 'producer.tool' must be "tsonic"`;
    }
    if (producerRecord.mode !== "tsonic-firstparty") {
      return `${filePath}: 'producer.mode' must be "tsonic-firstparty"`;
    }
    const normalizedV2: Record<string, unknown> = {
      namespace: manifest.namespace,
      types: targetSurfaceRecord.types,
      exports: targetSurfaceRecord.exports,
    };
    return validateBindingFile(normalizedV2, filePath);
  }

  // Check for tsbindgen format
  if ("namespace" in manifest && "types" in manifest) {
    if (typeof manifest.namespace !== "string") {
      return `${filePath}: 'namespace' must be a string`;
    }
    if (!Array.isArray(manifest.types)) {
      return `${filePath}: 'types' must be an array`;
    }
    for (const [typeIndex, typeValue] of manifest.types.entries()) {
      if (typeValue === null || typeof typeValue !== "object") continue;
      const typeRecord = typeValue as Record<string, unknown>;
      if (
        "alias" in typeRecord &&
        typeRecord.alias !== undefined &&
        typeof typeRecord.alias !== "string"
      ) {
        return `${filePath}: 'types[${typeIndex}].alias' must be a string when present`;
      }
      const methods = Array.isArray(typeRecord.methods)
        ? typeRecord.methods
        : [];
      for (const [methodIndex, methodValue] of methods.entries()) {
        if (methodValue === null || typeof methodValue !== "object") continue;
        const error = validateEmitSemantics(
          (methodValue as Record<string, unknown>).emitSemantics,
          filePath,
          `types[${typeIndex}].methods[${methodIndex}].emitSemantics`
        );
        if (error) return error;
      }
    }
    if ("exports" in manifest) {
      const exportsValue = manifest.exports;
      if (
        exportsValue !== undefined &&
        (exportsValue === null ||
          typeof exportsValue !== "object" ||
          Array.isArray(exportsValue))
      ) {
        return `${filePath}: 'exports' must be an object when present`;
      }
      if (exportsValue && typeof exportsValue === "object") {
        for (const [exportName, exportValue] of Object.entries(exportsValue)) {
          const error = validateTsbindgenExport(
            exportValue,
            filePath,
            `exports.${exportName}`
          );
          if (error) return error;
        }
      }
    }
    return undefined; // Valid tsbindgen format
  }

  // Check for full manifest format
  if ("assembly" in manifest && "namespaces" in manifest) {
    if (typeof manifest.assembly !== "string") {
      return `${filePath}: 'assembly' must be a string`;
    }
    if (!Array.isArray(manifest.namespaces)) {
      return `${filePath}: 'namespaces' must be an array`;
    }
    for (const [
      namespaceIndex,
      namespaceValue,
    ] of manifest.namespaces.entries()) {
      if (namespaceValue === null || typeof namespaceValue !== "object")
        continue;
      const namespaceRecord = namespaceValue as Record<string, unknown>;
      const types = Array.isArray(namespaceRecord.types)
        ? namespaceRecord.types
        : [];
      for (const [typeIndex, typeValue] of types.entries()) {
        if (typeValue === null || typeof typeValue !== "object") continue;
        const typeRecord = typeValue as Record<string, unknown>;
        const members = Array.isArray(typeRecord.members)
          ? typeRecord.members
          : [];
        for (const [memberIndex, memberValue] of members.entries()) {
          if (memberValue === null || typeof memberValue !== "object") continue;
          const error = validateEmitSemantics(
            (memberValue as Record<string, unknown>).emitSemantics,
            filePath,
            `namespaces[${namespaceIndex}].types[${typeIndex}].members[${memberIndex}].emitSemantics`
          );
          if (error) return error;
        }
      }
    }
    return undefined; // Valid full format
  }

  // Check for simple format (global/module bindings)
  if ("bindings" in manifest) {
    if (typeof manifest.bindings !== "object" || manifest.bindings === null) {
      return `${filePath}: 'bindings' must be an object`;
    }
    for (const [bindingName, bindingValue] of Object.entries(
      manifest.bindings as Record<string, unknown>
    )) {
      if (bindingValue === null || typeof bindingValue !== "object") continue;
      const error = validateTypeSemantics(
        (bindingValue as Record<string, unknown>).typeSemantics,
        filePath,
        `bindings.${bindingName}.typeSemantics`
      );
      if (error) return error;
    }
    return undefined; // Valid simple format
  }

  return `${filePath}: Unrecognized binding file format. Expected tsbindgen (namespace+types), full (assembly+namespaces), or simple (bindings) format.`;
};
