import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { IrModule } from "@tsonic/frontend";
import type { Result } from "../../../types.js";
import {
  classifyExportKind,
  resolveLocalModuleFile,
} from "../source-modules.js";
import {
  stripExistingSection,
  upsertSection,
  upsertSectionAfterImports,
} from "../shared.js";
import type { FacadeInfo } from "../types.js";

export const ensureFacade = (
  facadesByNamespace: Map<string, FacadeInfo>,
  bindingsOutDir: string,
  namespace: string
): FacadeInfo => {
  const existing = facadesByNamespace.get(namespace);
  if (existing) return existing;

  const baseName = namespace;
  const facadeDtsPath = join(bindingsOutDir, `${baseName}.d.ts`);
  const facadeJsPath = join(bindingsOutDir, `${baseName}.js`);
  const moduleSpecifier = `./${baseName}.js`;
  const internalIndexDtsPath = join(bindingsOutDir, "internal", "index.d.ts");

  const internalImport = existsSync(internalIndexDtsPath)
    ? `import * as Internal from './internal/index.js';\n\n`
    : "";

  if (!existsSync(facadeDtsPath)) {
    let content = `// Namespace: ${namespace}\n// Generated by Tsonic (source bindings augmentation)\n\n`;
    if (internalImport) content += internalImport;
    content += "export {};\n";
    writeFileSync(facadeDtsPath, content, "utf-8");
  }

  if (!existsSync(facadeJsPath)) {
    writeFileSync(
      facadeJsPath,
      [
        `// Namespace: ${namespace}`,
        `// Generated by Tsonic (source bindings augmentation)`,
        ``,
        `export {};`,
        ``,
      ].join("\n"),
      "utf-8"
    );
  }

  const created: FacadeInfo = {
    namespace,
    facadeDtsPath,
    facadeJsPath,
    moduleSpecifier,
    internalIndexDtsPath,
  };
  facadesByNamespace.set(namespace, created);
  return created;
};

export const writeExportedAliases = (opts: {
  readonly facadesByNamespace: ReadonlyMap<string, FacadeInfo>;
  readonly exportedAliasesByNamespace: ReadonlyMap<
    string,
    {
      readonly lines: readonly string[];
      readonly internalAliasImports: ReadonlySet<string>;
    }
  >;
}): Result<void, string> => {
  const aliasStart = "// Tsonic source type aliases (generated)";
  const aliasEnd = "// End Tsonic source type aliases";
  const aliasImportsStart = "// Tsonic source alias imports (generated)";
  const aliasImportsEnd = "// End Tsonic source alias imports";

  for (const [namespace, aliasData] of opts.exportedAliasesByNamespace) {
    const info = opts.facadesByNamespace.get(namespace);
    if (!info) continue;
    if (aliasData.lines.length === 0) continue;

    const unique = Array.from(new Set(aliasData.lines)).sort((a, b) =>
      a.localeCompare(b)
    );
    const body = unique.join("\n");

    const current = readFileSync(info.facadeDtsPath, "utf-8");
    const internalImportMatch = current.match(
      /^import\s+\*\s+as\s+Internal\s+from\s+['"](.+)['"];\s*$/m
    );
    let next = current;
    if (internalImportMatch?.[1] && aliasData.internalAliasImports.size > 0) {
      const internalAliasImportLine = `import type { ${Array.from(
        aliasData.internalAliasImports
      )
        .sort((a, b) => a.localeCompare(b))
        .join(", ")} } from '${internalImportMatch[1]}';`;
      next = upsertSectionAfterImports(
        next,
        aliasImportsStart,
        aliasImportsEnd,
        internalAliasImportLine
      );
    } else {
      next = stripExistingSection(next, aliasImportsStart, aliasImportsEnd);
    }
    next = upsertSectionAfterImports(next, aliasStart, aliasEnd, body);
    writeFileSync(info.facadeDtsPath, next, "utf-8");
  }

  return { ok: true, value: undefined };
};

export const writeEntrypointReexports = (opts: {
  readonly bindingsOutDir: string;
  readonly entryFacade: FacadeInfo;
  readonly entryModule: IrModule;
  readonly modulesByFile: ReadonlyMap<string, IrModule>;
  readonly facadesByNamespace: Map<string, FacadeInfo>;
}): Result<void, string> => {
  const reexports = opts.entryModule.exports.filter(
    (entry) => entry.kind === "reexport"
  );
  if (reexports.length === 0) {
    return { ok: true, value: undefined };
  }

  type GroupKey = `${string}|${"type" | "value"}`;
  const grouped = new Map<GroupKey, string[]>();

  for (const exp of reexports) {
    const targetModule = resolveLocalModuleFile(
      exp.fromModule,
      opts.entryModule.filePath,
      opts.modulesByFile
    );
    if (!targetModule) {
      return {
        ok: false,
        error:
          `Failed to resolve re-export '${exp.name}' from '${exp.fromModule}' in ${opts.entryModule.filePath}.\n` +
          "Ensure the target module is within sourceRoot and is part of the build graph.",
      };
    }

    if (targetModule.namespace === opts.entryModule.namespace) {
      continue;
    }

    const targetFacade = ensureFacade(
      opts.facadesByNamespace,
      opts.bindingsOutDir,
      targetModule.namespace
    );

    const kind = classifyExportKind(targetModule, exp.originalName);
    if (kind === "unknown") {
      return {
        ok: false,
        error:
          `Failed to classify re-export '${exp.name}' from '${exp.fromModule}'.\n` +
          `Could not find an exported declaration named '${exp.originalName}' in ${targetModule.filePath}.`,
      };
    }
    const spec =
      exp.name === exp.originalName
        ? exp.name
        : `${exp.originalName} as ${exp.name}`;
    const isTypeOnly = kind === "type";
    const key: GroupKey = `${targetFacade.moduleSpecifier}|${
      isTypeOnly ? "type" : "value"
    }`;
    const list = grouped.get(key) ?? [];
    list.push(spec);
    grouped.set(key, list);
  }

  const start = "// Tsonic entrypoint re-exports (generated)";
  const end = "// End Tsonic entrypoint re-exports";

  const statements: string[] = [];
  for (const [key, specs] of Array.from(grouped.entries()).sort((a, b) =>
    a[0].localeCompare(b[0])
  )) {
    const [moduleSpecifier, kind] = key.split("|") as [
      string,
      "type" | "value",
    ];
    const unique = Array.from(new Set(specs)).sort((a, b) =>
      a.localeCompare(b)
    );
    if (kind === "type") {
      statements.push(
        `export type { ${unique.join(", ")} } from '${moduleSpecifier}';`
      );
    } else {
      statements.push(
        `export { ${unique.join(", ")} } from '${moduleSpecifier}';`
      );
    }
  }

  if (statements.length > 0) {
    const current = readFileSync(opts.entryFacade.facadeDtsPath, "utf-8");
    const next = upsertSection(current, start, end, statements.join("\n"));
    writeFileSync(opts.entryFacade.facadeDtsPath, next, "utf-8");
  }

  const valueStatements = statements.filter(
    (statement) => !statement.startsWith("export type ")
  );
  if (valueStatements.length > 0) {
    const jsStart = "// Tsonic entrypoint value re-exports (generated)";
    const jsEnd = "// End Tsonic entrypoint value re-exports";
    const current = existsSync(opts.entryFacade.facadeJsPath)
      ? readFileSync(opts.entryFacade.facadeJsPath, "utf-8")
      : "";
    const next = upsertSection(
      current,
      jsStart,
      jsEnd,
      valueStatements.join("\n")
    );
    writeFileSync(opts.entryFacade.facadeJsPath, next, "utf-8");
  }

  return { ok: true, value: undefined };
};
