import { describe, expect, identifierType, it, printCompilationUnit, printExpression, printType } from "./helpers.js";
describe("backend-ast printer", () => {
  it("prints type reference expressions structurally", () => {
    expect(
      printExpression({
        kind: "typeReferenceExpression",
        type: identifierType("global::System.Collections.Generic.Dictionary", [
          { kind: "predefinedType", keyword: "string" },
          { kind: "predefinedType", keyword: "int" },
        ]),
      })
    ).to.equal("global::System.Collections.Generic.Dictionary<string, int>");
  });

  it("prints all supported predefined type keywords", () => {
    const keywords = [
      "bool",
      "byte",
      "sbyte",
      "short",
      "ushort",
      "int",
      "uint",
      "long",
      "ulong",
      "nint",
      "nuint",
      "float",
      "double",
      "decimal",
      "char",
      "string",
      "object",
      "void",
    ] as const;

    for (const keyword of keywords) {
      expect(printType({ kind: "predefinedType", keyword })).to.equal(keyword);
    }
  });

  it("prints exact BCL numeric value types as identifier types, not imaginary keywords", () => {
    expect(printType(identifierType("global::System.Int128"))).to.equal(
      "global::System.Int128"
    );

    expect(printType(identifierType("global::System.UInt128"))).to.equal(
      "global::System.UInt128"
    );

    expect(printType(identifierType("global::System.Half"))).to.equal(
      "global::System.Half"
    );
  });

  it("rejects illegally qualified simple identifier nodes", () => {
    expect(() =>
      printType({
        kind: "identifierType",
        name: "global::System.String",
      })
    ).to.throw(
      "ICE: Simple identifierType 'global::System.String' contains qualification. Use qualifiedIdentifierType AST instead."
    );

    expect(() =>
      printExpression({
        kind: "identifierExpression",
        identifier: "global::System.String",
      })
    ).to.throw(
      "ICE: Simple identifierExpression 'global::System.String' contains qualification. Use qualifiedIdentifierExpression AST instead."
    );
  });

  it("prints compilation-unit leading trivia structurally", () => {
    expect(
      printCompilationUnit({
        kind: "compilationUnit",
        leadingTrivia: [
          { kind: "singleLineCommentTrivia", text: "<auto-generated/>" },
          { kind: "singleLineCommentTrivia", text: "Generated by Tsonic" },
          { kind: "blankLineTrivia" },
        ],
        usings: [],
        members: [],
      })
    ).to.equal("// <auto-generated/>\n// Generated by Tsonic\n");
  });

  it("uses structural unary analysis instead of operand text lookups", () => {
    expect(
      printExpression({
        kind: "prefixUnaryExpression",
        operatorToken: "-",
        operand: {
          kind: "prefixUnaryExpression",
          operatorToken: "-",
          operand: { kind: "identifierExpression", identifier: "value" },
        },
      })
    ).to.equal("- -value");

    expect(
      printExpression({
        kind: "prefixUnaryExpression",
        operatorToken: "+",
        operand: {
          kind: "prefixUnaryExpression",
          operatorToken: "+",
          operand: { kind: "identifierExpression", identifier: "count" },
        },
      })
    ).to.equal("+ +count");
  });

  it("parenthesizes interpolations structurally when the AST can print colons", () => {
    expect(
      printExpression({
        kind: "interpolatedStringExpression",
        parts: [
          {
            kind: "interpolation",
            expression: {
              kind: "conditionalExpression",
              condition: { kind: "identifierExpression", identifier: "flag" },
              whenTrue: { kind: "identifierExpression", identifier: "left" },
              whenFalse: { kind: "identifierExpression", identifier: "right" },
            },
          },
        ],
      })
    ).to.equal('$"{(flag ? left : right)}"');

    expect(
      printExpression({
        kind: "interpolatedStringExpression",
        parts: [
          {
            kind: "interpolation",
            expression: {
              kind: "memberAccessExpression",
              expression: {
                kind: "typeReferenceExpression",
                type: identifierType("global::System.String"),
              },
              memberName: "Empty",
            },
          },
        ],
      })
    ).to.equal('$"{(global::System.String.Empty)}"');
  });

  it("prints block-bodied lambdas from printer indentation context, not emitter string hints", () => {
    expect(
      printExpression(
        {
          kind: "lambdaExpression",
          isAsync: false,
          parameters: [],
          body: {
            kind: "blockStatement",
            statements: [
              {
                kind: "returnStatement",
                expression: {
                  kind: "stringLiteralExpression",
                  value: "ok",
                },
              },
            ],
          },
        },
        "        "
      )
    ).to.equal('() =>\n            {\n            return "ok";\n            }');
  });

  it("prints block-bodied lambdas consistently inside nested expression contexts", () => {
    expect(
      printExpression(
        {
          kind: "invocationExpression",
          expression: {
            kind: "parenthesizedExpression",
            expression: {
              kind: "castExpression",
              type: identifierType("global::System.Func", [
                { kind: "predefinedType", keyword: "object" },
              ]),
              expression: {
                kind: "lambdaExpression",
                isAsync: false,
                parameters: [],
                body: {
                  kind: "blockStatement",
                  statements: [
                    {
                      kind: "expressionStatement",
                      expression: {
                        kind: "invocationExpression",
                        expression: {
                          kind: "identifierExpression",
                          identifier: "sideEffect",
                        },
                        arguments: [],
                      },
                    },
                    {
                      kind: "returnStatement",
                      expression: {
                        kind: "defaultExpression",
                        type: {
                          kind: "nullableType",
                          underlyingType: {
                            kind: "predefinedType",
                            keyword: "object",
                          },
                        },
                      },
                    },
                  ],
                },
              },
            },
          },
          arguments: [],
        },
        "            "
      )
    ).to.equal(
      "((global::System.Func<object>)(() =>\n" +
        "                {\n" +
        "                sideEffect();\n" +
        "                return default(object?);\n" +
        "                }))()"
    );
  });

  it("prints interpolated string text and format clauses structurally", () => {
    expect(
      printExpression({
        kind: "interpolatedStringExpression",
        parts: [
          { kind: "text", text: "count = " },
          {
            kind: "interpolation",
            expression: { kind: "identifierExpression", identifier: "value" },
            formatClause: "D4",
          },
          { kind: "text", text: ", raw = " },
          {
            kind: "interpolation",
            expression: {
              kind: "numericLiteralExpression",
              base: "hexadecimal",
              wholePart: "FF",
            },
          },
        ],
      })
    ).to.equal('$"count = {value:D4}, raw = {0xFF}"');
  });

});
