/**
 * Tests for Module Generation
 * Tests emission of static containers and regular classes
 */

import { describe, it } from "mocha";
import { expect } from "chai";
import { emitCSharpFiles, emitModule } from "../../emitter.js";
import { assumeEmittableIrModule, IrModule } from "@tsonic/frontend";
import {
  createJsSurfaceBindingRegistry,
  jsSurfaceCapabilities,
} from "../../expressions/index-cases/helpers.js";

const jsSurfaceBindingRegistry = createJsSurfaceBindingRegistry();

describe("Module Generation", () => {
  it("should emit a static container class", () => {
    const module: IrModule = {
      kind: "module",
      filePath: "/src/math.ts",
      namespace: "MyApp",
      className: "Math",
      isStaticContainer: true,
      imports: [],
      body: [
        {
          kind: "variableDeclaration",
          declarationKind: "const",
          declarations: [
            {
              kind: "variableDeclarator",
              name: { kind: "identifierPattern", name: "PI" },
              initializer: { kind: "literal", value: 3.14159 },
            },
          ],
          isExported: true,
        },
        {
          kind: "functionDeclaration",
          name: "add",
          parameters: [
            {
              kind: "parameter",
              pattern: { kind: "identifierPattern", name: "a" },
              type: { kind: "primitiveType", name: "number" },
              isOptional: false,
              isRest: false,
              passing: "value",
            },
            {
              kind: "parameter",
              pattern: { kind: "identifierPattern", name: "b" },
              type: { kind: "primitiveType", name: "number" },
              isOptional: false,
              isRest: false,
              passing: "value",
            },
          ],
          returnType: { kind: "primitiveType", name: "number" },
          body: {
            kind: "blockStatement",
            statements: [
              {
                kind: "returnStatement",
                expression: {
                  kind: "binary",
                  operator: "+",
                  left: { kind: "identifier", name: "a" },
                  right: { kind: "identifier", name: "b" },
                },
              },
            ],
          },
          isExported: true,
          isAsync: false,
          isGenerator: false,
        },
      ],
      exports: [],
    };

    const result = emitModule(module);

    expect(result).to.include(
      "[global::Tsonic.Internal.ModuleContainerAttribute]"
    );
    expect(result).to.include("public static class Math");
    // Static fields cannot use 'var' in C#; type is inferred from literal
    expect(result).to.include("public static readonly double PI = 3.14159");
    expect(result).to.include("public static double add(double a, double b)");
    expect(result).to.include("return a + b");
    expect(result).to.include("namespace MyApp");
  });

  it("should emit the module container marker attribute file when needed", () => {
    const module: IrModule = {
      kind: "module",
      filePath: "/src/math.ts",
      namespace: "MyApp",
      className: "Math",
      isStaticContainer: true,
      imports: [],
      body: [
        {
          kind: "functionDeclaration",
          name: "add",
          parameters: [
            {
              kind: "parameter",
              pattern: { kind: "identifierPattern", name: "a" },
              type: { kind: "primitiveType", name: "number" },
              isOptional: false,
              isRest: false,
              passing: "value",
            },
            {
              kind: "parameter",
              pattern: { kind: "identifierPattern", name: "b" },
              type: { kind: "primitiveType", name: "number" },
              isOptional: false,
              isRest: false,
              passing: "value",
            },
          ],
          returnType: { kind: "primitiveType", name: "number" },
          body: {
            kind: "blockStatement",
            statements: [
              {
                kind: "returnStatement",
                expression: {
                  kind: "binary",
                  operator: "+",
                  left: { kind: "identifier", name: "a" },
                  right: { kind: "identifier", name: "b" },
                },
              },
            ],
          },
          isExported: true,
          isAsync: false,
          isGenerator: false,
        },
      ],
      exports: [],
    };

    const result = emitCSharpFiles([assumeEmittableIrModule(module)], {
      rootNamespace: "MyApp",
    });
    expect(result.ok).to.equal(true);
    if (!result.ok) return;

    const marker = result.files.get("__tsonic_module_containers.g.cs");
    expect(marker).to.not.equal(undefined);
    expect(marker).to.include("// <auto-generated/>");
    expect(marker).to.include("namespace Tsonic.Internal");
    expect(marker).to.include("ModuleContainerAttribute");
  });

  it("suffixes module containers that collide with static value members", () => {
    const module: IrModule = {
      kind: "module",
      filePath: "/src/render.ts",
      namespace: "MyApp",
      className: "render",
      isStaticContainer: true,
      imports: [],
      body: [
        {
          kind: "functionDeclaration",
          name: "render",
          parameters: [],
          returnType: { kind: "primitiveType", name: "string" },
          body: {
            kind: "blockStatement",
            statements: [
              {
                kind: "returnStatement",
                expression: { kind: "literal", value: "ok", raw: '"ok"' },
              },
            ],
          },
          isExported: true,
          isAsync: false,
          isGenerator: false,
        },
      ],
      exports: [],
    };

    const result = emitModule(module);

    expect(result).to.include("public static class render__Module");
    expect(result).to.include("public static string render()");
    expect(result).not.to.include("public static class render\n");
  });

  it("does not emit readonly for mutable top-level array const bindings", () => {
    const module: IrModule = {
      kind: "module",
      filePath: "/src/store.ts",
      namespace: "MyApp",
      className: "Store",
      isStaticContainer: true,
      imports: [],
      body: [
        {
          kind: "variableDeclaration",
          declarationKind: "const",
          declarations: [
            {
              kind: "variableDeclarator",
              name: { kind: "identifierPattern", name: "items" },
              type: {
                kind: "arrayType",
                elementType: { kind: "primitiveType", name: "string" },
              },
              initializer: { kind: "array", elements: [] },
            },
          ],
          isExported: false,
        },
        {
          kind: "functionDeclaration",
          name: "addItem",
          parameters: [],
          returnType: { kind: "voidType" },
          body: {
            kind: "blockStatement",
            statements: [
              {
                kind: "expressionStatement",
                expression: {
                  kind: "call",
                  callee: {
                    kind: "memberAccess",
                    object: {
                      kind: "identifier",
                      name: "items",
                      inferredType: {
                        kind: "arrayType",
                        elementType: { kind: "primitiveType", name: "string" },
                      },
                    },
                    property: "push",
                    isComputed: false,
                    isOptional: false,
                    inferredType: {
                      kind: "functionType",
                      parameters: [
                        {
                          kind: "parameter",
                          pattern: {
                            kind: "identifierPattern",
                            name: "item",
                          },
                          type: {
                            kind: "primitiveType",
                            name: "string",
                          },
                          isOptional: false,
                          isRest: false,
                          passing: "value",
                        },
                      ],
                      returnType: { kind: "primitiveType", name: "number" },
                    },
                    memberBinding: {
                      kind: "method",
                      assembly: "js",
                      type: "js.Array",
                      member: "push",
                    },
                  },
                  arguments: [{ kind: "literal", value: "value" }],
                  isOptional: false,
                },
              },
            ],
          },
          isExported: false,
          isAsync: false,
          isGenerator: false,
        },
      ],
      exports: [],
    };

    const result = emitModule(module, {
      surface: "@tsonic/js",
      bindingRegistry: jsSurfaceBindingRegistry,
      surfaceCapabilities: jsSurfaceCapabilities,
    });
    expect(result).to.include("internal static string[] items");
    expect(result).to.not.include("internal static readonly string[] items");
  });

  it("keeps readonly for non-mutated top-level array const bindings", () => {
    const module: IrModule = {
      kind: "module",
      filePath: "/src/store.ts",
      namespace: "MyApp",
      className: "Store",
      isStaticContainer: true,
      imports: [],
      body: [
        {
          kind: "variableDeclaration",
          declarationKind: "const",
          declarations: [
            {
              kind: "variableDeclarator",
              name: { kind: "identifierPattern", name: "items" },
              type: {
                kind: "arrayType",
                elementType: { kind: "primitiveType", name: "string" },
              },
              initializer: { kind: "array", elements: [] },
            },
          ],
          isExported: false,
        },
      ],
      exports: [],
    };

    const result = emitModule(module);
    expect(result).to.include("internal static readonly string[] items");
  });

  it("suffixes module containers that collide with runtime union alias carriers", () => {
    const module: IrModule = {
      kind: "module",
      filePath: "/src/runtime-value.ts",
      namespace: "MyApp",
      className: "RuntimeValue",
      isStaticContainer: true,
      imports: [],
      body: [
        {
          kind: "typeAliasDeclaration",
          name: "RuntimeValue",
          type: {
            kind: "unionType",
            runtimeUnionLayout: "carrierSlotOrder",
            runtimeCarrierFamilyKey: "runtime-union:alias:MyApp.RuntimeValue",
            runtimeCarrierName: "RuntimeValue",
            runtimeCarrierNamespace: "MyApp",
            types: [
              { kind: "primitiveType", name: "string" },
              { kind: "primitiveType", name: "number" },
            ],
          },
          isExported: true,
          isStruct: false,
        },
        {
          kind: "functionDeclaration",
          name: "fromString",
          parameters: [
            {
              kind: "parameter",
              pattern: { kind: "identifierPattern", name: "value" },
              type: { kind: "primitiveType", name: "string" },
              isOptional: false,
              isRest: false,
              passing: "value",
            },
          ],
          returnType: {
            kind: "referenceType",
            name: "RuntimeValue",
            resolvedClrType: "MyApp.RuntimeValue",
          },
          body: {
            kind: "blockStatement",
            statements: [
              {
                kind: "returnStatement",
                expression: { kind: "identifier", name: "value" },
              },
            ],
          },
          isExported: true,
          isAsync: false,
          isGenerator: false,
        },
      ],
      exports: [],
    };

    const result = emitCSharpFiles([assumeEmittableIrModule(module)], {
      rootNamespace: "MyApp",
    });
    expect(result.ok).to.equal(true);
    if (!result.ok) return;

    const moduleFile = result.files.get("runtime-value.cs");
    const unionsFile = result.files.get("__tsonic_unions.g.cs");
    expect(moduleFile).to.include("public static class RuntimeValue__Module");
    expect(moduleFile).to.not.include("public static class RuntimeValue\n");
    expect(unionsFile).to.include("public sealed class RuntimeValue");
  });
});
