/**
 * Type definitions for .NET bindings.json files generated by tsbindgen.
 *
 * These types represent runtime binding information used for reflection-based dispatch.
 * All property names use camelCase (JavaScript convention).
 *
 * The bindings format uses a dual-version structure:
 * - V1 Definitions: Full method signatures for reference
 * - V2 Exposures: Lightweight binding info for runtime dispatch
 *
 * @see spec/bindings.md for complete schema documentation
 */

/**
 * Root bindings file structure.
 * Represents a single namespace with all its type bindings.
 */
export type BindingsFile = {
  readonly namespace: string;
  readonly types: TypeBinding[];
};

/**
 * Complete binding information for a CLR type.
 * Includes both V1 definitions and V2 exposures.
 */
export type TypeBinding = {
  readonly clrName: string;
  readonly tsEmitName: string;
  readonly assemblyName: string;
  readonly metadataToken: number;
  readonly methods?: MethodBinding[]; // V1: Full signatures
  readonly properties?: PropertyBinding[]; // V1: Property info
  readonly fields?: FieldBinding[]; // V1: Field info
  readonly events?: EventBinding[]; // V1: Event info
  readonly exposedMethods?: ExposedMethodBinding[]; // V2: Runtime dispatch
  readonly exposedProperties?: ExposedPropertyBinding[]; // V2: Runtime access
  readonly exposedFields?: ExposedFieldBinding[]; // V2: Runtime access
  readonly exposedEvents?: ExposedEventBinding[]; // V2: Runtime access
};

/**
 * V1 Definition: Complete method signature.
 * Used for type checking and reference.
 */
export type MethodBinding = {
  readonly name: string;
  readonly clrName: string;
  readonly tsEmitName: string;
  readonly isStatic: boolean;
  readonly arity: number;
  readonly parameters: ParameterBinding[];
  readonly returnType: string;
  readonly metadataToken: number;
};

/**
 * V1 Definition: Property information.
 */
export type PropertyBinding = {
  readonly name: string;
  readonly clrName: string;
  readonly tsEmitName: string;
  readonly isStatic: boolean;
  readonly type: string;
  readonly hasGetter: boolean;
  readonly hasSetter: boolean;
  readonly getterToken?: number;
  readonly setterToken?: number;
};

/**
 * V1 Definition: Field information.
 */
export type FieldBinding = {
  readonly name: string;
  readonly clrName: string;
  readonly tsEmitName: string;
  readonly isStatic: boolean;
  readonly type: string;
  readonly metadataToken: number;
};

/**
 * V1 Definition: Event information.
 */
export type EventBinding = {
  readonly name: string;
  readonly clrName: string;
  readonly tsEmitName: string;
  readonly isStatic: boolean;
  readonly type: string;
  readonly adderToken: number;
  readonly removerToken: number;
};

/**
 * Parameter binding information.
 */
export type ParameterBinding = {
  readonly name: string;
  readonly type: string;
  readonly isRef: boolean;
  readonly isOut: boolean;
  readonly isIn?: boolean;
  readonly isParams: boolean;
};

/**
 * V2 Exposure: Lightweight method binding for runtime dispatch.
 * Optimized format with minimal data for fast lookups.
 */
export type ExposedMethodBinding = {
  readonly tsEmitName: string;
  readonly isStatic: boolean;
  readonly arity: number;
  readonly overloads: MethodOverloadBinding[];
};

/**
 * Method overload binding.
 * One entry per unique parameter count.
 */
export type MethodOverloadBinding = {
  readonly parameterCount: number;
  readonly metadataToken: number;
};

/**
 * V2 Exposure: Lightweight property binding for runtime access.
 */
export type ExposedPropertyBinding = {
  readonly tsEmitName: string;
  readonly isStatic: boolean;
  readonly getterToken?: number;
  readonly setterToken?: number;
};

/**
 * V2 Exposure: Lightweight field binding for runtime access.
 */
export type ExposedFieldBinding = {
  readonly tsEmitName: string;
  readonly isStatic: boolean;
  readonly metadataToken: number;
};

/**
 * V2 Exposure: Lightweight event binding for runtime access.
 */
export type ExposedEventBinding = {
  readonly tsEmitName: string;
  readonly isStatic: boolean;
  readonly adderToken: number;
  readonly removerToken: number;
};

/**
 * Helper type: Extract V1 definitions from a type binding.
 */
export type V1Definitions = Pick<
  TypeBinding,
  "methods" | "properties" | "fields" | "events"
>;

/**
 * Helper type: Extract V2 exposures from a type binding.
 */
export type V2Exposures = Pick<
  TypeBinding,
  "exposedMethods" | "exposedProperties" | "exposedFields" | "exposedEvents"
>;
