/**
 * Type definitions for .NET metadata.json files generated by tsbindgen.
 *
 * These types represent the CLR type system metadata in a TypeScript-friendly format.
 * All property names use camelCase (JavaScript convention).
 *
 * @see spec/metadata.md for complete schema documentation
 */

/**
 * Root metadata file structure.
 * Represents a single namespace with all its types.
 */
export type MetadataFile = {
  readonly namespace: string;
  readonly contributingAssemblies: string[];
  readonly types: TypeMetadata[];
};

/**
 * Type kind enumeration.
 * Represents the fundamental kind of CLR type.
 */
export type TypeKind = "Class" | "Interface" | "Struct" | "Enum" | "Delegate";

/**
 * Accessibility level enumeration.
 * Represents CLR accessibility modifiers.
 */
export type Accessibility =
  | "Public"
  | "Internal"
  | "Protected"
  | "ProtectedInternal"
  | "PrivateProtected"
  | "Private";

/**
 * Emit scope enumeration.
 * Determines where a member should be emitted in TypeScript declarations.
 */
export type EmitScope =
  | "ClassSurface" // Emit on main class
  | "ViewOnly" // Emit only in explicit interface views
  | "Omitted"; // Don't emit (not accessible from TypeScript)

/**
 * Provenance enumeration.
 * Tracks the origin of a member in the type hierarchy.
 */
export type Provenance =
  | "Original" // Declared on this type
  | "Declared" // Explicitly declared (alias of Original)
  | "InlineFromInterface" // Implicit interface implementation
  | "InlineFromBase" // Inherited from base class
  | "SynthesizedViewOnly" // Generated for view-only access
  | "ExplicitView"; // Explicit interface implementation

/**
 * Complete metadata for a CLR type.
 */
export type TypeMetadata = {
  readonly clrName: string;
  readonly tsEmitName: string;
  readonly kind: TypeKind;
  readonly accessibility: Accessibility;
  readonly isAbstract: boolean;
  readonly isSealed: boolean;
  readonly isStatic: boolean;
  readonly arity: number;
  readonly baseType?: string | null;
  readonly interfaces?: string[];
  readonly isValueType?: boolean;
  readonly methods: MethodMetadata[];
  readonly properties: PropertyMetadata[];
  readonly fields: FieldMetadata[];
  readonly events: EventMetadata[];
  readonly constructors: ConstructorMetadata[];
  readonly intentionalOmissions?: IntentionalOmissions;
  readonly explicitViews?: ExplicitView[];
};

/**
 * Method metadata.
 */
export type MethodMetadata = {
  readonly name: string;
  readonly clrName: string;
  readonly tsEmitName: string;
  readonly accessibility: Accessibility;
  readonly isStatic: boolean;
  readonly isAbstract: boolean;
  readonly isVirtual: boolean;
  readonly isFinal: boolean;
  readonly arity: number;
  readonly parameters: ParameterMetadata[];
  readonly returnType: string;
  readonly emitScope: EmitScope;
  readonly provenance: Provenance;
};

/**
 * Property metadata.
 */
export type PropertyMetadata = {
  readonly name: string;
  readonly clrName: string;
  readonly tsEmitName: string;
  readonly accessibility: Accessibility;
  readonly isStatic: boolean;
  readonly type: string;
  readonly hasGetter: boolean;
  readonly hasSetter: boolean;
  readonly emitScope: EmitScope;
  readonly provenance: Provenance;
};

/**
 * Field metadata.
 */
export type FieldMetadata = {
  readonly name: string;
  readonly clrName: string;
  readonly tsEmitName: string;
  readonly accessibility: Accessibility;
  readonly isStatic: boolean;
  readonly isReadonly: boolean;
  readonly type: string;
  readonly emitScope: EmitScope;
  readonly provenance: Provenance;
};

/**
 * Event metadata.
 */
export type EventMetadata = {
  readonly name: string;
  readonly clrName: string;
  readonly tsEmitName: string;
  readonly accessibility: Accessibility;
  readonly isStatic: boolean;
  readonly type: string;
  readonly emitScope: EmitScope;
  readonly provenance: Provenance;
};

/**
 * Constructor metadata.
 */
export type ConstructorMetadata = {
  readonly accessibility: Accessibility;
  readonly parameters: ParameterMetadata[];
  readonly emitScope: EmitScope;
};

/**
 * Parameter metadata.
 */
export type ParameterMetadata = {
  readonly name: string;
  readonly type: string;
  readonly isRef: boolean;
  readonly isOut: boolean;
  readonly isIn?: boolean;
  readonly isParams: boolean;
  readonly defaultValue?: any | null;
};

/**
 * Intentional omissions from TypeScript declarations.
 * Tracks members that are deliberately not emitted.
 */
export type IntentionalOmissions = {
  readonly methods?: OmittedMethod[];
  readonly properties?: OmittedProperty[];
  readonly fields?: OmittedField[];
  readonly events?: OmittedEvent[];
};

/**
 * Omitted method information.
 */
export type OmittedMethod = {
  readonly name: string;
  readonly reason: string;
};

/**
 * Omitted property information.
 */
export type OmittedProperty = {
  readonly name: string;
  readonly reason: string;
};

/**
 * Omitted field information.
 */
export type OmittedField = {
  readonly name: string;
  readonly reason: string;
};

/**
 * Omitted event information.
 */
export type OmittedEvent = {
  readonly name: string;
  readonly reason: string;
};

/**
 * Explicit interface view metadata.
 * Represents an As_IInterface property for explicit interface implementations.
 */
export type ExplicitView = {
  readonly interfaceName: string;
  readonly tsPropertyName: string;
  readonly members: ExplicitViewMember[];
};

/**
 * Member within an explicit interface view.
 */
export type ExplicitViewMember = {
  readonly kind: "Method" | "Property" | "Event";
  readonly name: string;
  readonly clrName: string;
};
