/**
 * Backend AST module exports
 */

export type {
  // Type AST
  CSharpTypeAst,
  CSharpPredefinedTypeAst,
  CSharpIdentifierTypeAst,
  CSharpNullableTypeAst,
  CSharpArrayTypeAst,
  CSharpPointerTypeAst,
  CSharpTupleTypeAst,
  CSharpTupleElementAst,
  // Expression AST
  CSharpExpressionAst,
  CSharpLiteralExpressionAst,
  CSharpIdentifierExpressionAst,
  CSharpParenthesizedExpressionAst,
  CSharpMemberAccessExpressionAst,
  CSharpConditionalMemberAccessExpressionAst,
  CSharpElementAccessExpressionAst,
  CSharpConditionalElementAccessExpressionAst,
  CSharpInvocationExpressionAst,
  CSharpObjectCreationExpressionAst,
  CSharpArrayCreationExpressionAst,
  CSharpStackAllocArrayCreationExpressionAst,
  CSharpAssignmentExpressionAst,
  CSharpBinaryExpressionAst,
  CSharpPrefixUnaryExpressionAst,
  CSharpPostfixUnaryExpressionAst,
  CSharpConditionalExpressionAst,
  CSharpCastExpressionAst,
  CSharpAsExpressionAst,
  CSharpIsExpressionAst,
  CSharpDefaultExpressionAst,
  CSharpAwaitExpressionAst,
  CSharpLambdaExpressionAst,
  CSharpLambdaParameterAst,
  CSharpInterpolatedStringExpressionAst,
  CSharpInterpolatedStringPart,
  CSharpThrowExpressionAst,
  CSharpSuppressNullableWarningExpressionAst,
  CSharpTypeofExpressionAst,
  CSharpSwitchExpressionAst,
  CSharpSwitchExpressionArmAst,
  // Pattern AST
  CSharpPatternAst,
  CSharpTypePatternAst,
  CSharpDeclarationPatternAst,
  CSharpVarPatternAst,
  CSharpConstantPatternAst,
  CSharpDiscardPatternAst,
  CSharpNegatedPatternAst,
  // Statement AST
  CSharpStatementAst,
  CSharpBlockStatementAst,
  CSharpLocalDeclarationStatementAst,
  CSharpLocalFunctionStatementAst,
  CSharpExpressionStatementAst,
  CSharpIfStatementAst,
  CSharpWhileStatementAst,
  CSharpForStatementAst,
  CSharpForeachStatementAst,
  CSharpSwitchStatementAst,
  CSharpSwitchSectionAst,
  CSharpSwitchLabelAst,
  CSharpTryStatementAst,
  CSharpCatchClauseAst,
  CSharpThrowStatementAst,
  CSharpReturnStatementAst,
  CSharpBreakStatementAst,
  CSharpContinueStatementAst,
  CSharpEmptyStatementAst,
  CSharpYieldStatementAst,
  CSharpVariableDeclaratorAst,
  CSharpParameterAst,
  // Declaration/Member AST
  CSharpMemberAst,
  CSharpFieldDeclarationAst,
  CSharpPropertyDeclarationAst,
  CSharpMethodDeclarationAst,
  CSharpConstructorDeclarationAst,
  CSharpAttributeAst,
  CSharpEnumMemberAst,
  CSharpTypeParameterAst,
  CSharpTypeParameterConstraintAst,
  CSharpTypeDeclarationAst,
  CSharpClassDeclarationAst,
  CSharpStructDeclarationAst,
  CSharpInterfaceDeclarationAst,
  CSharpEnumDeclarationAst,
  // Top-level
  CSharpUsingDirectiveAst,
  CSharpNamespaceDeclarationAst,
  CSharpCompilationUnitAst,
} from "./types.js";

export {
  printType,
  printExpression,
  printPattern,
  printStatement,
  printMember,
  printTypeDeclaration,
  printCompilationUnit,
} from "./printer.js";

export { extractCalleeNameFromAst } from "./utils.js";
