/**
 * Backend AST module exports
 */

export type {
  // Type AST
  CSharpTypeAst,
  CSharpPredefinedTypeAst,
  CSharpIdentifierTypeAst,
  CSharpQualifiedNameAst,
  CSharpQualifiedIdentifierTypeAst,
  CSharpNullableTypeAst,
  CSharpArrayTypeAst,
  CSharpPointerTypeAst,
  CSharpTupleTypeAst,
  CSharpTupleElementAst,
  // Expression AST
  CSharpExpressionAst,
  CSharpNullLiteralExpressionAst,
  CSharpBooleanLiteralExpressionAst,
  CSharpStringLiteralExpressionAst,
  CSharpCharLiteralExpressionAst,
  CSharpNumericLiteralExpressionAst,
  CSharpNumericLiteralBase,
  CSharpNumericLiteralSuffix,
  CSharpIdentifierExpressionAst,
  CSharpQualifiedIdentifierExpressionAst,
  CSharpTypeReferenceExpressionAst,
  CSharpParenthesizedExpressionAst,
  CSharpMemberAccessExpressionAst,
  CSharpConditionalMemberAccessExpressionAst,
  CSharpElementAccessExpressionAst,
  CSharpConditionalElementAccessExpressionAst,
  CSharpImplicitElementAccessExpressionAst,
  CSharpInvocationExpressionAst,
  CSharpObjectCreationExpressionAst,
  CSharpArrayCreationExpressionAst,
  CSharpStackAllocArrayCreationExpressionAst,
  CSharpAssignmentExpressionAst,
  CSharpBinaryExpressionAst,
  CSharpPrefixUnaryExpressionAst,
  CSharpPostfixUnaryExpressionAst,
  CSharpConditionalExpressionAst,
  CSharpCastExpressionAst,
  CSharpAsExpressionAst,
  CSharpIsExpressionAst,
  CSharpDefaultExpressionAst,
  CSharpSizeOfExpressionAst,
  CSharpAwaitExpressionAst,
  CSharpLambdaExpressionAst,
  CSharpLambdaParameterAst,
  CSharpInterpolatedStringExpressionAst,
  CSharpInterpolatedStringPart,
  CSharpThrowExpressionAst,
  CSharpSuppressNullableWarningExpressionAst,
  CSharpTypeofExpressionAst,
  CSharpSwitchExpressionAst,
  CSharpSwitchExpressionArmAst,
  // Pattern AST
  CSharpPatternAst,
  CSharpTypePatternAst,
  CSharpDeclarationPatternAst,
  CSharpVarPatternAst,
  CSharpConstantPatternAst,
  CSharpDiscardPatternAst,
  CSharpNegatedPatternAst,
  // Statement AST
  CSharpStatementAst,
  CSharpBlockStatementAst,
  CSharpLocalDeclarationStatementAst,
  CSharpLocalFunctionStatementAst,
  CSharpExpressionStatementAst,
  CSharpIfStatementAst,
  CSharpWhileStatementAst,
  CSharpForStatementAst,
  CSharpForeachStatementAst,
  CSharpSwitchStatementAst,
  CSharpSwitchSectionAst,
  CSharpSwitchLabelAst,
  CSharpTryStatementAst,
  CSharpCatchClauseAst,
  CSharpThrowStatementAst,
  CSharpReturnStatementAst,
  CSharpBreakStatementAst,
  CSharpContinueStatementAst,
  CSharpEmptyStatementAst,
  CSharpYieldStatementAst,
  CSharpVariableDeclaratorAst,
  CSharpParameterAst,
  // Declaration/Member AST
  CSharpMemberAst,
  CSharpFieldDeclarationAst,
  CSharpPropertyDeclarationAst,
  CSharpMethodDeclarationAst,
  CSharpConstructorDeclarationAst,
  CSharpAttributeAst,
  CSharpEnumMemberAst,
  CSharpTypeParameterAst,
  CSharpTypeParameterConstraintNodeAst,
  CSharpTypeParameterConstraintAst,
  CSharpTypeDeclarationAst,
  CSharpClassDeclarationAst,
  CSharpStructDeclarationAst,
  CSharpInterfaceDeclarationAst,
  CSharpEnumDeclarationAst,
  // Top-level
  CSharpUsingDirectiveAst,
  CSharpTriviaAst,
  CSharpSingleLineCommentTriviaAst,
  CSharpBlankLineTriviaAst,
  CSharpNamespaceDeclarationAst,
  CSharpCompilationUnitAst,
} from "./types.js";

export {
  printType,
  printExpression,
  printPattern,
  printStatement,
  printMember,
  printTypeDeclaration,
  printCompilationUnit,
  printAttributes,
  printParameter,
} from "./printer.js";

export {
  clrTypeNameToTypeAst,
  extractCalleeNameFromAst,
  getIdentifierTypeLeafName,
  getIdentifierTypeName,
  globallyQualifyTypeAst,
  stableTypeKeyFromAst,
  stableIdentifierSuffixFromTypeAst,
  stripNullableTypeAst,
} from "./utils.js";

export {
  nullLiteral,
  booleanLiteral,
  stringLiteral,
  charLiteral,
  decimalIntegerLiteral,
  qualifiedName,
  identifierExpression,
  identifierType,
  numericLiteral,
  parseNumericLiteral,
  withTypeArguments,
} from "./builders.js";
